# Generated by nebius_generator. DO NOT EDIT!
"""Direct protobuf classes for this package."""

from __future__ import annotations

from builtins import (
    bool as _NebiusBool, bytes as _NebiusBytes, dict as _NebiusDict,
    float as _NebiusFloat, int as _NebiusInt, object as _NebiusObject,
    property as _NebiusProperty, str as _NebiusStr,
)
from collections.abc import (
    AsyncIterable as _NebiusAsyncIterable, Iterable as _NebiusIterable,
    Mapping as _NebiusMapping, MutableMapping as _NebiusMutableMapping,
    MutableSequence as _NebiusMutableSequence,
)
from datetime import datetime as _NebiusDatetime, timedelta as _NebiusTimedelta
from logging import getLogger as _nebius_get_logger
from typing import (
    TYPE_CHECKING as _NEBIUS_TYPE_CHECKING, ClassVar as _NebiusClassVar,
    Literal as _NebiusLiteral, TypeAlias as _NebiusTypeAlias, cast as _nebius_cast,
)
from typing_extensions import Unpack as _NebiusUnpack

from ......aio.client import Client as _NebiusClient, ClientWithOperations as _NebiusClientWithOperations
from ......aio.operation import Operation as _NebiusOperation
from ......aio.request import Request as _NebiusRequest
from ......aio.request_kwargs import RequestKwargs as _NebiusRequestKwargs, StreamRequestKwargs as _NebiusStreamRequestKwargs
from ......aio.stream import StreamRequest as _NebiusStreamRequest
from ......base.protos.codec import (
    BOOL, BYTES, DOUBLE, FIXED32, FIXED64, FLOAT, INT32, INT64,
    SFIXED32, SFIXED64, SINT32, SINT64, STRING, UINT32, UINT64, enum_codec,
)
from ......base.protos.direct import (
    Field, Message, OneOf as _NebiusOneOf,
    OneOfMatchError as _NebiusOneOfMatchError,
    SerializableMessage as _NebiusSerializableMessage, message_codec,
)
from ......base.fieldmask_protobuf import ensure_reset_mask_in_metadata
from ......base.protos.pb_enum import Enum
from ......base.protos.extensions import Extension as _NebiusExtension
from ......base.protos.unset import Unset as _NEBIUS_UNSET, UnsetType as _NebiusUnsetType
from ......aio.request_status import RequestStatus as _NebiusRequestStatus
from ......base.protos.well_known_direct import (
    datetime_to_timestamp as _nebius_datetime_to_timestamp,
    duration_to_timedelta as _nebius_duration_to_timedelta,
    request_status_to_status as _nebius_request_status_to_status,
    status_to_request_status as _nebius_status_to_request_status,
    timedelta_to_duration as _nebius_timedelta_to_duration,
    timestamp_to_datetime as _nebius_timestamp_to_datetime,
)
from ....._registry import EXTENSION_HANDLES, EXTENSIONS, REGISTRY

# @@nebius-section:type_imports@@
# @@nebius-section:enums@@
# @@nebius-section:messages@@
class MigrateSkypilotRequest(Message):
    __PROTO_FULL_NAME__ = 'nebius.msp.skypilot.v1alpha1.MigrateSkypilotRequest'
    """Fully qualified protobuf message name."""
    __REGISTRY__ = REGISTRY
    """Registry for this message and its descriptor."""
    __EXTENSION_REGISTRY__ = EXTENSIONS
    """Registry that decodes extensions for this message."""
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.msp.skypilot.v1alpha1.MigrateSkypilotRequest')
    """Protobuf message descriptor from the registry."""
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    """Alias for code that expects a protobuf message descriptor."""

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        id: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        """Create a message from a source message and field values."""
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if id is not _NEBIUS_UNSET:
            values['id'] = id
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def id(self) -> _NebiusStr:
        'ID of the entity to migrate.'
        value = self._get_field(_NEBIUS_MSP_SKYPILOT_V1ALPHA1_MIGRATESKYPILOTREQUEST_ID, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @id.setter
    def id(self, value: _NebiusStr | None) -> None:
        """Set or clear the generated ``id`` field."""
        self._set_field(_NEBIUS_MSP_SKYPILOT_V1ALPHA1_MIGRATESKYPILOTREQUEST_ID, value)

    __PY_TO_PB2__ = {'id': 'id'}
    """Mapping from Python member names to protobuf names."""
_NebiusType_nebius_msp_skypilot_v1alpha1_MigrateSkypilotRequest_518de797 = MigrateSkypilotRequest

# @@nebius-section:fields@@
_NEBIUS_MSP_SKYPILOT_V1ALPHA1_MIGRATESKYPILOTREQUEST_ID = Field('id', 'id', 1, STRING, json_name='id')
MigrateSkypilotRequest.__FIELDS__ = (_NEBIUS_MSP_SKYPILOT_V1ALPHA1_MIGRATESKYPILOTREQUEST_ID,)

# @@nebius-section:attachments@@
# @@nebius-section:extensions@@
# @@nebius-section:services@@
# @@nebius-section:exports@@
__all__ = ['MigrateSkypilotRequest']
