# Generated by nebius_generator. DO NOT EDIT!
"""Direct protobuf classes for this package."""

from __future__ import annotations

from builtins import (
    bool as _NebiusBool, bytes as _NebiusBytes, dict as _NebiusDict,
    float as _NebiusFloat, int as _NebiusInt, object as _NebiusObject,
    property as _NebiusProperty, str as _NebiusStr,
)
from collections.abc import (
    AsyncIterable as _NebiusAsyncIterable, Iterable as _NebiusIterable,
    Mapping as _NebiusMapping, MutableMapping as _NebiusMutableMapping,
    MutableSequence as _NebiusMutableSequence,
)
from datetime import datetime as _NebiusDatetime, timedelta as _NebiusTimedelta
from logging import getLogger as _nebius_get_logger
from typing import (
    TYPE_CHECKING as _NEBIUS_TYPE_CHECKING, ClassVar as _NebiusClassVar,
    Literal as _NebiusLiteral, TypeAlias as _NebiusTypeAlias, cast as _nebius_cast,
)
from typing_extensions import Unpack as _NebiusUnpack

from nebius.aio.client import Client as _NebiusClient, ClientWithOperations as _NebiusClientWithOperations
from nebius.aio.operation import Operation as _NebiusOperation
from nebius.aio.request import Request as _NebiusRequest
from nebius.aio.request_kwargs import RequestKwargs as _NebiusRequestKwargs, StreamRequestKwargs as _NebiusStreamRequestKwargs
from nebius.aio.stream import StreamRequest as _NebiusStreamRequest
from nebius.base.protos.codec import (
    BOOL, BYTES, DOUBLE, FIXED32, FIXED64, FLOAT, INT32, INT64,
    SFIXED32, SFIXED64, SINT32, SINT64, STRING, UINT32, UINT64, enum_codec,
)
from nebius.base.protos.direct import (
    Field, Message, OneOf as _NebiusOneOf,
    OneOfMatchError as _NebiusOneOfMatchError,
    SerializableMessage as _NebiusSerializableMessage, message_codec,
)
from nebius.base.fieldmask_protobuf import ensure_reset_mask_in_metadata
from nebius.base.protos.pb_enum import Enum
from nebius.base.protos.extensions import Extension as _NebiusExtension
from nebius.base.protos.unset import Unset as _NEBIUS_UNSET, UnsetType as _NebiusUnsetType
from nebius.aio.request_status import RequestStatus as _NebiusRequestStatus
from nebius.base.protos.well_known_direct import (
    datetime_to_timestamp as _nebius_datetime_to_timestamp,
    duration_to_timedelta as _nebius_duration_to_timedelta,
    request_status_to_status as _nebius_request_status_to_status,
    status_to_request_status as _nebius_status_to_request_status,
    timedelta_to_duration as _nebius_timedelta_to_duration,
    timestamp_to_datetime as _nebius_timestamp_to_datetime,
)
from ......_registry import EXTENSION_HANDLES, EXTENSIONS, REGISTRY

# @@nebius-section:type_imports@@
# @@nebius-section:enums@@
# @@nebius-section:messages@@
class PostgresqlConfig16(Message):
    __PROTO_FULL_NAME__ = 'nebius.msp.postgresql.v1alpha1.config.PostgresqlConfig16'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.msp.postgresql.v1alpha1.config.PostgresqlConfig16')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    class __OneOfClass__autovacuum_work_mem__(_NebiusOneOf):
        name: str = '_autovacuum_work_mem'

    class __OneOfClass__autovacuum_work_mem_autovacuum_work_mem__(__OneOfClass__autovacuum_work_mem__):
        field: _NebiusLiteral['autovacuum_work_mem'] = 'autovacuum_work_mem'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_WORK_MEM),)

    @_NebiusProperty
    def _autovacuum_work_mem(self) -> __OneOfClass__autovacuum_work_mem_autovacuum_work_mem__ | None:
        selected = self.which_field_in_oneof('_autovacuum_work_mem')
        match selected:
            case 'autovacuum_work_mem':
                return self.__OneOfClass__autovacuum_work_mem_autovacuum_work_mem__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__statement_timeout__(_NebiusOneOf):
        name: str = '_statement_timeout'

    class __OneOfClass__statement_timeout_statement_timeout__(__OneOfClass__statement_timeout__):
        field: _NebiusLiteral['statement_timeout'] = 'statement_timeout'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_STATEMENT_TIMEOUT),)

    @_NebiusProperty
    def _statement_timeout(self) -> __OneOfClass__statement_timeout_statement_timeout__ | None:
        selected = self.which_field_in_oneof('_statement_timeout')
        match selected:
            case 'statement_timeout':
                return self.__OneOfClass__statement_timeout_statement_timeout__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__idle_in_transaction_session_timeout__(_NebiusOneOf):
        name: str = '_idle_in_transaction_session_timeout'

    class __OneOfClass__idle_in_transaction_session_timeout_idle_in_transaction_session_timeout__(__OneOfClass__idle_in_transaction_session_timeout__):
        field: _NebiusLiteral['idle_in_transaction_session_timeout'] = 'idle_in_transaction_session_timeout'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_IDLE_IN_TRANSACTION_SESSION_TIMEOUT),)

    @_NebiusProperty
    def _idle_in_transaction_session_timeout(self) -> __OneOfClass__idle_in_transaction_session_timeout_idle_in_transaction_session_timeout__ | None:
        selected = self.which_field_in_oneof('_idle_in_transaction_session_timeout')
        match selected:
            case 'idle_in_transaction_session_timeout':
                return self.__OneOfClass__idle_in_transaction_session_timeout_idle_in_transaction_session_timeout__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__autovacuum_vacuum_cost_delay__(_NebiusOneOf):
        name: str = '_autovacuum_vacuum_cost_delay'

    class __OneOfClass__autovacuum_vacuum_cost_delay_autovacuum_vacuum_cost_delay__(__OneOfClass__autovacuum_vacuum_cost_delay__):
        field: _NebiusLiteral['autovacuum_vacuum_cost_delay'] = 'autovacuum_vacuum_cost_delay'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_DELAY),)

    @_NebiusProperty
    def _autovacuum_vacuum_cost_delay(self) -> __OneOfClass__autovacuum_vacuum_cost_delay_autovacuum_vacuum_cost_delay__ | None:
        selected = self.which_field_in_oneof('_autovacuum_vacuum_cost_delay')
        match selected:
            case 'autovacuum_vacuum_cost_delay':
                return self.__OneOfClass__autovacuum_vacuum_cost_delay_autovacuum_vacuum_cost_delay__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__autovacuum_vacuum_cost_limit__(_NebiusOneOf):
        name: str = '_autovacuum_vacuum_cost_limit'

    class __OneOfClass__autovacuum_vacuum_cost_limit_autovacuum_vacuum_cost_limit__(__OneOfClass__autovacuum_vacuum_cost_limit__):
        field: _NebiusLiteral['autovacuum_vacuum_cost_limit'] = 'autovacuum_vacuum_cost_limit'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_LIMIT),)

    @_NebiusProperty
    def _autovacuum_vacuum_cost_limit(self) -> __OneOfClass__autovacuum_vacuum_cost_limit_autovacuum_vacuum_cost_limit__ | None:
        selected = self.which_field_in_oneof('_autovacuum_vacuum_cost_limit')
        match selected:
            case 'autovacuum_vacuum_cost_limit':
                return self.__OneOfClass__autovacuum_vacuum_cost_limit_autovacuum_vacuum_cost_limit__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__autovacuum_naptime__(_NebiusOneOf):
        name: str = '_autovacuum_naptime'

    class __OneOfClass__autovacuum_naptime_autovacuum_naptime__(__OneOfClass__autovacuum_naptime__):
        field: _NebiusLiteral['autovacuum_naptime'] = 'autovacuum_naptime'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_NAPTIME),)

    @_NebiusProperty
    def _autovacuum_naptime(self) -> __OneOfClass__autovacuum_naptime_autovacuum_naptime__ | None:
        selected = self.which_field_in_oneof('_autovacuum_naptime')
        match selected:
            case 'autovacuum_naptime':
                return self.__OneOfClass__autovacuum_naptime_autovacuum_naptime__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__autovacuum_vacuum_scale_factor__(_NebiusOneOf):
        name: str = '_autovacuum_vacuum_scale_factor'

    class __OneOfClass__autovacuum_vacuum_scale_factor_autovacuum_vacuum_scale_factor__(__OneOfClass__autovacuum_vacuum_scale_factor__):
        field: _NebiusLiteral['autovacuum_vacuum_scale_factor'] = 'autovacuum_vacuum_scale_factor'

        @_NebiusProperty
        def value(self) -> _NebiusFloat:
            return _nebius_cast('_NebiusFloat', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_SCALE_FACTOR),)

    @_NebiusProperty
    def _autovacuum_vacuum_scale_factor(self) -> __OneOfClass__autovacuum_vacuum_scale_factor_autovacuum_vacuum_scale_factor__ | None:
        selected = self.which_field_in_oneof('_autovacuum_vacuum_scale_factor')
        match selected:
            case 'autovacuum_vacuum_scale_factor':
                return self.__OneOfClass__autovacuum_vacuum_scale_factor_autovacuum_vacuum_scale_factor__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__autovacuum_analyze_scale_factor__(_NebiusOneOf):
        name: str = '_autovacuum_analyze_scale_factor'

    class __OneOfClass__autovacuum_analyze_scale_factor_autovacuum_analyze_scale_factor__(__OneOfClass__autovacuum_analyze_scale_factor__):
        field: _NebiusLiteral['autovacuum_analyze_scale_factor'] = 'autovacuum_analyze_scale_factor'

        @_NebiusProperty
        def value(self) -> _NebiusFloat:
            return _nebius_cast('_NebiusFloat', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_ANALYZE_SCALE_FACTOR),)

    @_NebiusProperty
    def _autovacuum_analyze_scale_factor(self) -> __OneOfClass__autovacuum_analyze_scale_factor_autovacuum_analyze_scale_factor__ | None:
        selected = self.which_field_in_oneof('_autovacuum_analyze_scale_factor')
        match selected:
            case 'autovacuum_analyze_scale_factor':
                return self.__OneOfClass__autovacuum_analyze_scale_factor_autovacuum_analyze_scale_factor__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__default_transaction_read_only__(_NebiusOneOf):
        name: str = '_default_transaction_read_only'

    class __OneOfClass__default_transaction_read_only_default_transaction_read_only__(__OneOfClass__default_transaction_read_only__):
        field: _NebiusLiteral['default_transaction_read_only'] = 'default_transaction_read_only'

        @_NebiusProperty
        def value(self) -> _NebiusBool:
            return _nebius_cast('_NebiusBool', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_DEFAULT_TRANSACTION_READ_ONLY),)

    @_NebiusProperty
    def _default_transaction_read_only(self) -> __OneOfClass__default_transaction_read_only_default_transaction_read_only__ | None:
        selected = self.which_field_in_oneof('_default_transaction_read_only')
        match selected:
            case 'default_transaction_read_only':
                return self.__OneOfClass__default_transaction_read_only_default_transaction_read_only__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__search_path__(_NebiusOneOf):
        name: str = '_search_path'

    class __OneOfClass__search_path_search_path__(__OneOfClass__search_path__):
        field: _NebiusLiteral['search_path'] = 'search_path'

        @_NebiusProperty
        def value(self) -> _NebiusStr:
            return _nebius_cast('_NebiusStr', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SEARCH_PATH),)

    @_NebiusProperty
    def _search_path(self) -> __OneOfClass__search_path_search_path__ | None:
        selected = self.which_field_in_oneof('_search_path')
        match selected:
            case 'search_path':
                return self.__OneOfClass__search_path_search_path__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__max_connections__(_NebiusOneOf):
        name: str = '_max_connections'

    class __OneOfClass__max_connections_max_connections__(__OneOfClass__max_connections__):
        field: _NebiusLiteral['max_connections'] = 'max_connections'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_MAX_CONNECTIONS),)

    @_NebiusProperty
    def _max_connections(self) -> __OneOfClass__max_connections_max_connections__ | None:
        selected = self.which_field_in_oneof('_max_connections')
        match selected:
            case 'max_connections':
                return self.__OneOfClass__max_connections_max_connections__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    class __OneOfClass__shared_buffers__(_NebiusOneOf):
        name: str = '_shared_buffers'

    class __OneOfClass__shared_buffers_shared_buffers__(__OneOfClass__shared_buffers__):
        field: _NebiusLiteral['shared_buffers'] = 'shared_buffers'

        @_NebiusProperty
        def value(self) -> _NebiusInt:
            return _nebius_cast('_NebiusInt', self._message._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SHARED_BUFFERS),)

    @_NebiusProperty
    def _shared_buffers(self) -> __OneOfClass__shared_buffers_shared_buffers__ | None:
        selected = self.which_field_in_oneof('_shared_buffers')
        match selected:
            case 'shared_buffers':
                return self.__OneOfClass__shared_buffers_shared_buffers__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        autovacuum_work_mem: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        statement_timeout: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        idle_in_transaction_session_timeout: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autovacuum_vacuum_cost_delay: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autovacuum_vacuum_cost_limit: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autovacuum_naptime: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autovacuum_vacuum_scale_factor: _NebiusFloat | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autovacuum_analyze_scale_factor: _NebiusFloat | None | _NebiusUnsetType = _NEBIUS_UNSET,
        default_transaction_read_only: _NebiusBool | None | _NebiusUnsetType = _NEBIUS_UNSET,
        search_path: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        max_connections: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        shared_buffers: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if autovacuum_work_mem is not _NEBIUS_UNSET:
            values['autovacuum_work_mem'] = autovacuum_work_mem
        if statement_timeout is not _NEBIUS_UNSET:
            values['statement_timeout'] = statement_timeout
        if idle_in_transaction_session_timeout is not _NEBIUS_UNSET:
            values['idle_in_transaction_session_timeout'] = idle_in_transaction_session_timeout
        if autovacuum_vacuum_cost_delay is not _NEBIUS_UNSET:
            values['autovacuum_vacuum_cost_delay'] = autovacuum_vacuum_cost_delay
        if autovacuum_vacuum_cost_limit is not _NEBIUS_UNSET:
            values['autovacuum_vacuum_cost_limit'] = autovacuum_vacuum_cost_limit
        if autovacuum_naptime is not _NEBIUS_UNSET:
            values['autovacuum_naptime'] = autovacuum_naptime
        if autovacuum_vacuum_scale_factor is not _NEBIUS_UNSET:
            values['autovacuum_vacuum_scale_factor'] = autovacuum_vacuum_scale_factor
        if autovacuum_analyze_scale_factor is not _NEBIUS_UNSET:
            values['autovacuum_analyze_scale_factor'] = autovacuum_analyze_scale_factor
        if default_transaction_read_only is not _NEBIUS_UNSET:
            values['default_transaction_read_only'] = default_transaction_read_only
        if search_path is not _NEBIUS_UNSET:
            values['search_path'] = search_path
        if max_connections is not _NEBIUS_UNSET:
            values['max_connections'] = max_connections
        if shared_buffers is not _NEBIUS_UNSET:
            values['shared_buffers'] = shared_buffers
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def autovacuum_work_mem(self) -> _NebiusInt | None:
        'in kilobytes.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_WORK_MEM, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @autovacuum_work_mem.setter
    def autovacuum_work_mem(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_WORK_MEM, value)

    @_NebiusProperty
    def statement_timeout(self) -> _NebiusInt | None:
        'in milliseconds.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_STATEMENT_TIMEOUT, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @statement_timeout.setter
    def statement_timeout(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_STATEMENT_TIMEOUT, value)

    @_NebiusProperty
    def idle_in_transaction_session_timeout(self) -> _NebiusInt | None:
        'in milliseconds.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_IDLE_IN_TRANSACTION_SESSION_TIMEOUT, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @idle_in_transaction_session_timeout.setter
    def idle_in_transaction_session_timeout(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_IDLE_IN_TRANSACTION_SESSION_TIMEOUT, value)

    @_NebiusProperty
    def autovacuum_vacuum_cost_delay(self) -> _NebiusInt | None:
        'in milliseconds.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_DELAY, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @autovacuum_vacuum_cost_delay.setter
    def autovacuum_vacuum_cost_delay(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_DELAY, value)

    @_NebiusProperty
    def autovacuum_vacuum_cost_limit(self) -> _NebiusInt | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_LIMIT, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @autovacuum_vacuum_cost_limit.setter
    def autovacuum_vacuum_cost_limit(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_LIMIT, value)

    @_NebiusProperty
    def autovacuum_naptime(self) -> _NebiusInt | None:
        'in seconds.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_NAPTIME, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @autovacuum_naptime.setter
    def autovacuum_naptime(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_NAPTIME, value)

    @_NebiusProperty
    def autovacuum_vacuum_scale_factor(self) -> _NebiusFloat | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_SCALE_FACTOR, absent_is_none=True)
        return _nebius_cast('_NebiusFloat | None', value)

    @autovacuum_vacuum_scale_factor.setter
    def autovacuum_vacuum_scale_factor(self, value: _NebiusFloat | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_SCALE_FACTOR, value)

    @_NebiusProperty
    def autovacuum_analyze_scale_factor(self) -> _NebiusFloat | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_ANALYZE_SCALE_FACTOR, absent_is_none=True)
        return _nebius_cast('_NebiusFloat | None', value)

    @autovacuum_analyze_scale_factor.setter
    def autovacuum_analyze_scale_factor(self, value: _NebiusFloat | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_ANALYZE_SCALE_FACTOR, value)

    @_NebiusProperty
    def default_transaction_read_only(self) -> _NebiusBool | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_DEFAULT_TRANSACTION_READ_ONLY, absent_is_none=True)
        return _nebius_cast('_NebiusBool | None', value)

    @default_transaction_read_only.setter
    def default_transaction_read_only(self, value: _NebiusBool | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_DEFAULT_TRANSACTION_READ_ONLY, value)

    @_NebiusProperty
    def search_path(self) -> _NebiusStr | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SEARCH_PATH, absent_is_none=True)
        return _nebius_cast('_NebiusStr | None', value)

    @search_path.setter
    def search_path(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SEARCH_PATH, value)

    @_NebiusProperty
    def max_connections(self) -> _NebiusInt | None:
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_MAX_CONNECTIONS, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @max_connections.setter
    def max_connections(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_MAX_CONNECTIONS, value)

    @_NebiusProperty
    def shared_buffers(self) -> _NebiusInt | None:
        'in kilobytes.'
        value = self._get_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SHARED_BUFFERS, absent_is_none=True)
        return _nebius_cast('_NebiusInt | None', value)

    @shared_buffers.setter
    def shared_buffers(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SHARED_BUFFERS, value)

    __PY_TO_PB2__ = {'autovacuum_work_mem': 'autovacuum_work_mem', 'statement_timeout': 'statement_timeout', 'idle_in_transaction_session_timeout': 'idle_in_transaction_session_timeout', 'autovacuum_vacuum_cost_delay': 'autovacuum_vacuum_cost_delay', 'autovacuum_vacuum_cost_limit': 'autovacuum_vacuum_cost_limit', 'autovacuum_naptime': 'autovacuum_naptime', 'autovacuum_vacuum_scale_factor': 'autovacuum_vacuum_scale_factor', 'autovacuum_analyze_scale_factor': 'autovacuum_analyze_scale_factor', 'default_transaction_read_only': 'default_transaction_read_only', 'search_path': 'search_path', 'max_connections': 'max_connections', 'shared_buffers': 'shared_buffers', '_autovacuum_work_mem': '_autovacuum_work_mem', '_statement_timeout': '_statement_timeout', '_idle_in_transaction_session_timeout': '_idle_in_transaction_session_timeout', '_autovacuum_vacuum_cost_delay': '_autovacuum_vacuum_cost_delay', '_autovacuum_vacuum_cost_limit': '_autovacuum_vacuum_cost_limit', '_autovacuum_naptime': '_autovacuum_naptime', '_autovacuum_vacuum_scale_factor': '_autovacuum_vacuum_scale_factor', '_autovacuum_analyze_scale_factor': '_autovacuum_analyze_scale_factor', '_default_transaction_read_only': '_default_transaction_read_only', '_search_path': '_search_path', '_max_connections': '_max_connections', '_shared_buffers': '_shared_buffers'}
_NebiusType_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16_643e90df = PostgresqlConfig16

# @@nebius-section:fields@@
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_WORK_MEM = Field('autovacuum_work_mem', 'autovacuum_work_mem', 1, INT64, explicit_presence=True, oneof='_autovacuum_work_mem', json_name='autovacuumWorkMem')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_STATEMENT_TIMEOUT = Field('statement_timeout', 'statement_timeout', 2, INT64, explicit_presence=True, oneof='_statement_timeout', json_name='statementTimeout')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_IDLE_IN_TRANSACTION_SESSION_TIMEOUT = Field('idle_in_transaction_session_timeout', 'idle_in_transaction_session_timeout', 3, INT64, explicit_presence=True, oneof='_idle_in_transaction_session_timeout', json_name='idleInTransactionSessionTimeout')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_DELAY = Field('autovacuum_vacuum_cost_delay', 'autovacuum_vacuum_cost_delay', 4, INT64, explicit_presence=True, oneof='_autovacuum_vacuum_cost_delay', json_name='autovacuumVacuumCostDelay')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_LIMIT = Field('autovacuum_vacuum_cost_limit', 'autovacuum_vacuum_cost_limit', 5, INT64, explicit_presence=True, oneof='_autovacuum_vacuum_cost_limit', json_name='autovacuumVacuumCostLimit')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_NAPTIME = Field('autovacuum_naptime', 'autovacuum_naptime', 6, INT64, explicit_presence=True, oneof='_autovacuum_naptime', json_name='autovacuumNaptime')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_SCALE_FACTOR = Field('autovacuum_vacuum_scale_factor', 'autovacuum_vacuum_scale_factor', 7, DOUBLE, explicit_presence=True, oneof='_autovacuum_vacuum_scale_factor', json_name='autovacuumVacuumScaleFactor')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_ANALYZE_SCALE_FACTOR = Field('autovacuum_analyze_scale_factor', 'autovacuum_analyze_scale_factor', 8, DOUBLE, explicit_presence=True, oneof='_autovacuum_analyze_scale_factor', json_name='autovacuumAnalyzeScaleFactor')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_DEFAULT_TRANSACTION_READ_ONLY = Field('default_transaction_read_only', 'default_transaction_read_only', 9, BOOL, explicit_presence=True, oneof='_default_transaction_read_only', json_name='defaultTransactionReadOnly')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SEARCH_PATH = Field('search_path', 'search_path', 10, STRING, explicit_presence=True, oneof='_search_path', json_name='searchPath')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_MAX_CONNECTIONS = Field('max_connections', 'max_connections', 11, INT64, explicit_presence=True, oneof='_max_connections', json_name='maxConnections')
_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SHARED_BUFFERS = Field('shared_buffers', 'shared_buffers', 12, INT64, explicit_presence=True, oneof='_shared_buffers', json_name='sharedBuffers')
PostgresqlConfig16.__FIELDS__ = (_NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_WORK_MEM, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_STATEMENT_TIMEOUT, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_IDLE_IN_TRANSACTION_SESSION_TIMEOUT, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_DELAY, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_COST_LIMIT, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_NAPTIME, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_VACUUM_SCALE_FACTOR, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_AUTOVACUUM_ANALYZE_SCALE_FACTOR, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_DEFAULT_TRANSACTION_READ_ONLY, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SEARCH_PATH, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_MAX_CONNECTIONS, _NEBIUS_MSP_POSTGRESQL_V1ALPHA1_CONFIG_POSTGRESQLCONFIG16_SHARED_BUFFERS)

# @@nebius-section:attachments@@
# @@nebius-section:extensions@@
# @@nebius-section:services@@
# @@nebius-section:exports@@
__all__ = ['PostgresqlConfig16']
