"""Protobuf compiler entry point for generating Nebius SDK code."""

import argparse
import logging
import sys
from collections.abc import Sequence
from typing import Any

from google.protobuf.compiler import plugin_pb2 as plugin

from .descriptors import FileSet
from .generators import (
    configure_runtime_package,
    generate_exports,
    generate_file,
    generate_grpc_compat,
    generate_pb2_compat,
)
from .pygen import ImportPath, PyGenFile
from .well_known import configure_runtime_package as configure_well_known_runtime

# Set up a logger
log = logging.getLogger("NebiusGenerator")


def package_to_path(package: str) -> str:
    """Convert a package name to an ``__init__.py`` output path.

    :param package: Package name (dot-separated).
    :returns: File path suitable for the generator output.
    """
    return "/".join(package.split(".")) + "/__init__.py"


def module_to_path(module: str) -> str:
    """Convert a module name to its Python source output path."""
    return "/".join(module.split(".")) + ".py"


def registry_import_path(file_package: str, export_package: str) -> str:
    """Return the namespace-local descriptor registry for a proto package."""
    proto_suffix_length = len(file_package.split(".")) - 1
    export_parts = export_package.split(".")
    if proto_suffix_length:
        export_parts = export_parts[:-proto_suffix_length]
    return ".".join([*export_parts, "_registry"])


def generate_registry(
    protos: Sequence[Any],
) -> str:
    """Generate an isolated descriptor pool used only for wire conversion."""
    serialized = ",\n".join(f"    {proto.SerializeToString()!r}" for proto in protos)
    return f'''# Generated by nebius_generator.  DO NOT EDIT!

"""Namespace-local protobuf descriptors for direct SDK messages."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import message_factory as _message_factory

_SERIALIZED_FILES = (
{serialized},
)

_POOL = _descriptor_pool.DescriptorPool()
_pending = list(_SERIALIZED_FILES)
while _pending:
    _remaining = []
    for _serialized in _pending:
        try:
            _POOL.AddSerializedFile(_serialized)
        except TypeError:
            _remaining.append(_serialized)
    if len(_remaining) == len(_pending):
        raise RuntimeError(
            "Unable to load generated protobuf descriptor dependencies"
        )
    _pending = _remaining

del _pending, _remaining, _serialized


def message(name: str) -> type[_message.Message]:
    """Return the private protobuf class for a fully-qualified message name."""
    return _message_factory.GetMessageClass(
        _POOL.FindMessageTypeByName(name.lstrip("."))
    )


def message_descriptor(name: str) -> _descriptor.Descriptor:
    """Return a private message descriptor."""
    return _POOL.FindMessageTypeByName(name.lstrip("."))


def enum_descriptor(name: str) -> _descriptor.EnumDescriptor:
    """Return a private enum descriptor."""
    return _POOL.FindEnumTypeByName(name.lstrip("."))


def service_descriptor(name: str) -> _descriptor.ServiceDescriptor:
    """Return a private service descriptor."""
    return _POOL.FindServiceByName(name.lstrip("."))


def extension_descriptor(name: str) -> _descriptor.FieldDescriptor:
    """Return a private extension descriptor."""
    return _POOL.FindExtensionByName(name.lstrip("."))
'''


class KeyValueAction(argparse.Action):
    """argparse action for parsing ``key=value`` options into a dict."""

    def __call__(
        self,
        parser: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: str | Sequence[Any] | None,
        option_string: str | None = None,
    ) -> None:
        """Store a key/value pair on the argparse namespace."""
        kv_dict: dict[str, str] = getattr(namespace, self.dest, {}) or {}
        try:
            if isinstance(values, str):
                key, value = values.split("=", 1)
                kv_dict[key] = value
            else:
                raise argparse.ArgumentError(self, "Must be in the form key=value")
        except ValueError:
            raise argparse.ArgumentError(self, "Must be in the form key=value")
        setattr(namespace, self.dest, kv_dict)


def parse_options(parameter: str) -> argparse.Namespace:
    """Parses the `--md_opt` parameters using argparse."""
    parser = argparse.ArgumentParser(description="nebius generator options")
    parser.add_argument(
        "--log_level",
        type=str,
        default="WARNING",
        help="Set the log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)",
    )
    parser.add_argument(
        "--import_substitution",
        action=KeyValueAction,
        default={},
        metavar="package.prefix=your.substitution",
        help="Specify package substitutions for importing pb2 and grpc packages.",
    )
    parser.add_argument(
        "--export_substitution",
        action=KeyValueAction,
        default={},
        metavar="package.prefix=your.substitution",
        help="Specify package substitutions for exporting, if they differ from import"
        " substitutions.",
    )
    parser.add_argument(
        "--runtime_package",
        type=str,
        default="nebius",
        help="Python package containing the SDK runtime used by generated clients.",
    )
    parser.add_argument(
        "--debugger_connect",
        type=str,
        default="",
        help="connect to debugger, eg localhost:5678",
    )
    parser.add_argument(
        "--skip",
        action="append",
        default=[],
        metavar="some.package",
        help="Specify packages to skip. Can be used multiple times.",
    )

    # Split the parameter by commas and emulate command-line arguments
    args = ["--" + opt for opt in parameter.split(",") if opt]
    return parser.parse_args(args)


def main() -> None:
    """Generate Nebius SDK code from a protoc request."""
    # Read CodeGeneratorRequest from stdin
    input_data = sys.stdin.buffer.read()
    request = plugin.CodeGeneratorRequest()
    request.ParseFromString(input_data)

    options = parse_options(request.parameter)
    configure_runtime_package(options.runtime_package)
    configure_well_known_runtime(options.runtime_package)
    logging.basicConfig(
        level=options.log_level,
        stream=sys.stderr,
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    # Prepare CodeGeneratorResponse
    response = plugin.CodeGeneratorResponse()
    response.supported_features = (
        plugin.CodeGeneratorResponse.Feature.FEATURE_PROTO3_OPTIONAL
    )

    results = dict[str, PyGenFile]()

    file_set = FileSet(
        request.proto_file,
        request.file_to_generate,
        options.import_substitution,
        options.export_substitution,
        options.skip,
    )
    registry_paths: dict[str, str] = {}
    for file in file_set.files_generated:
        if file.skipped:
            continue
        top_level = file.package.split(".", 1)[0]
        registry_paths.setdefault(
            top_level,
            registry_import_path(file.package, file.export_path.import_path),
        )
    lock_file = ""
    if (
        options.debugger_connect != ""
        and "nebius/compute/v1/network_interface.proto" in file_set.files_dict
    ):
        from urllib.parse import urlparse

        from filelock import FileLock  # type: ignore[unused-ignore,import-not-found]

        # Path to the lock file
        lock_file = "script.lock"

        # Create a lock object
        lock = FileLock(lock_file)

        import debugpy  # type: ignore[unused-ignore,import-not-found,import-untyped]

        parsed_url = urlparse(f"//{options.debugger_connect}", scheme="tcp")
        lock.acquire()
        debugpy.listen((parsed_url.hostname, parsed_url.port))  # type: ignore[unused-ignore]
        log.info("Waiting for debugger to attach...")
        debugpy.wait_for_client()  # type: ignore[unused-ignore]
        log.debug("Debugger attached. Continuing execution...")

    for file in file_set.files_generated:
        if file.skipped:
            continue
        if file.package not in results:
            results[file.package] = PyGenFile(
                import_path=file.export_path.import_path,
                docstring=f"Auto-generated Nebius SDK package for ``{file.package}``",
            )
            results[file.package].registry = ImportPath(
                registry_paths[file.package.split(".", 1)[0]],
                localized=True,
            )
        results[file.package].append_used_names(list(file.collect_all_names()))

    file_set.check_names()

    for file in file_set.files_generated:
        if file.skipped:
            continue
        generate_file(
            file,
            results[file.package],
        )

    for package, g in results.items():
        g.p("__all__ = [")
        with g:
            g.p("#@ local import names here @#")
    for file in file_set.files_generated:
        if file.skipped:
            continue
        g = results[file.package]
        with g:
            generate_exports(
                file,
                g,
            )
    for package, g in results.items():
        g.p("]")

    for _, g in results.items():
        # Create a new file for each .proto file
        output_file = response.file.add()
        output_file.name = package_to_path(g.import_path)
        output_file.content = g.dumps()

    for file in file_set.files_generated:
        if file.skipped:
            continue
        registry = ImportPath(
            registry_paths[file.package.split(".", 1)[0]],
            localized=True,
        )
        pb2_file = PyGenFile(
            file.pb2,
            module=True,
            docstring=f"Compatibility facade for ``{file.name}``.",
        )
        pb2_file.registry = registry
        generate_pb2_compat(file, pb2_file)
        output_file = response.file.add()
        output_file.name = module_to_path(file.pb2.import_path)
        output_file.content = pb2_file.dumps()

        grpc_file = PyGenFile(
            file.grpc,
            module=True,
            docstring=f"gRPC compatibility helpers for ``{file.name}``.",
        )
        grpc_file.registry = registry
        generate_grpc_compat(file, grpc_file)
        output_file = response.file.add()
        output_file.name = module_to_path(file.grpc.import_path)
        output_file.content = grpc_file.dumps()

    for registry_path in sorted(set(registry_paths.values())):
        output_file = response.file.add()
        output_file.name = module_to_path(registry_path)
        output_file.content = generate_registry(request.proto_file)

    # Write the CodeGeneratorResponse to stdout
    sys.stdout.buffer.write(response.SerializeToString())

    if options.debugger_connect != "" and lock_file != "":
        lock.release()  # type: ignore[unused-ignore]


if __name__ == "__main__":
    main()
