# Code generated by protoc-gen-pysdk. DO NOT EDIT.
from __future__ import annotations

import builtins as _builtins
from collections.abc import (
    AsyncIterable as _AsyncIterable,
    Iterable as _Iterable,
    Mapping as _Mapping,
    MutableMapping as _MutableMapping,
    MutableSequence as _MutableSequence,
)
from datetime import datetime as _datetime, timedelta as _timedelta
from typing import Any as _Any, Literal as _Literal, TypeAlias as _TypeAlias
from typing_extensions import Unpack as _Unpack
from .....aio.client import Client as _Client, ClientWithOperations as _ClientWithOperations
from .....aio.operation import Operation as _AsyncOperation
from .....aio.request import Request as _Request
from .....aio.request_kwargs import RequestKwargs as _RequestKwargs, StreamRequestKwargs as _StreamRequestKwargs
from .....aio.request_status import RequestStatus as _RequestStatus
from .....aio.stream import StreamRequest as _StreamRequest
from .....base.protos.direct import Message as _Message, OneOf as _OneOf, SerializableMessage as _SerializableMessage
from .....base.protos.extensions import Extension as _Extension
from .....base.protos.extensions import ExtensionRegistry as _ExtensionRegistry
from .....base.protos.pb_enum import Enum as _Enum
from .....base.protos.registry import Registry as _Registry
from .....base.protos.unset import UnsetType as _UnsetType
from ....google.protobuf import Empty as _type_google_protobuf_Empty
from ...common.v1 import GetByNameRequest as _type_nebius_common_v1_GetByNameRequest
from ...common.v1 import Operation as _type_nebius_common_v1_Operation
from ...common.v1 import RecurrentResourceEvent as _type_nebius_common_v1_RecurrentResourceEvent
from ...common.v1 import ResourceMetadata as _type_nebius_common_v1_ResourceMetadata

REGISTRY: _Registry
EXTENSIONS: _ExtensionRegistry
EXTENSION_HANDLES: dict[str, _Extension[_Any]]

class Cluster(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec: ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    @property
    def status(self) -> ClusterStatus: ...
    @status.setter
    def status(self, value: ClusterStatus | None) -> None:
        """Set or clear the generated ``status`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
        status: ClusterStatus | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterSpec(_Message):
    @property
    def control_plane(self) -> ControlPlaneSpec: ...
    @control_plane.setter
    def control_plane(self, value: ControlPlaneSpec | None) -> None:
        """Set or clear the generated ``control_plane`` field."""
        ...
    @property
    def kube_network(self) -> KubeNetworkSpec:
        """Defines kubernetes network configuration, like IP allocation."""
        ...
    @kube_network.setter
    def kube_network(self, value: KubeNetworkSpec | None) -> None:
        """Set or clear the generated ``kube_network`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        control_plane: ControlPlaneSpec | None | _UnsetType = ...,
        kube_network: KubeNetworkSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ControlPlaneSpec(_Message):
    @property
    def version(self) -> _builtins.str:
        """Desired Kubernetes version of the cluster. May be lower than the actual cluster version\nif the desired version is no longer supported and the cluster has been automatically updated.\nFor now only acceptable format is ``<major>.<minor>`` like \"1.31\".\nOption for patch version update will be added later."""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def subnet_id(self) -> _builtins.str:
        """Nebius VPC Subnet ID where control plane instances will be located.\nAlso will be default NodeGroup subnet."""
        ...
    @subnet_id.setter
    def subnet_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``subnet_id`` field."""
        ...
    @property
    def endpoints(self) -> ControlPlaneEndpointsSpec:
        """Specification of endpoints of cluster control plane."""
        ...
    @endpoints.setter
    def endpoints(self, value: ControlPlaneEndpointsSpec | None) -> None:
        """Set or clear the generated ``endpoints`` field."""
        ...
    @property
    def etcd_cluster_size(self) -> _builtins.int:
        """Number of instances in etcd cluster.\n3 by default.\nControl plane with ``etcd_cluster_size: 3`` called \"Highly Available\" (\"HA\"), because it's Kubernetes API\nwill be available despite a failure of one control plane instance."""
        ...
    @etcd_cluster_size.setter
    def etcd_cluster_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``etcd_cluster_size`` field."""
        ...
    @property
    def audit_logs(self) -> AuditLogsSpec:
        """Specify configuration of the pushing k8s audit logs into service logs and show it in the UI.\nBy default cluster will be created without it."""
        ...
    @audit_logs.setter
    def audit_logs(self, value: AuditLogsSpec | None) -> None:
        """Set or clear the generated ``audit_logs`` field."""
        ...
    @property
    def karpenter(self) -> Karpenter:
        """Enables installation of the Karpenter inside a cluster.\nKarpenter will be installed as a helm chart inside cluster\nso it requires creation of at least one CPU public node group.\n\nPlease note that there is no feature parity between Karpenter node pools and\npublic node groups.\nBy default cluster will be created without it."""
        ...
    @karpenter.setter
    def karpenter(self, value: Karpenter | None) -> None:
        """Set or clear the generated ``karpenter`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        version: _builtins.str | None | _UnsetType = ...,
        subnet_id: _builtins.str | None | _UnsetType = ...,
        endpoints: ControlPlaneEndpointsSpec | None | _UnsetType = ...,
        etcd_cluster_size: _builtins.int | None | _UnsetType = ...,
        audit_logs: AuditLogsSpec | None | _UnsetType = ...,
        karpenter: Karpenter | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ControlPlaneEndpointsSpec(_Message):
    @property
    def public_endpoint(self) -> PublicEndpointSpec:
        """Public endpoint specification. When set, a public endpoint is created."""
        ...
    @public_endpoint.setter
    def public_endpoint(self, value: PublicEndpointSpec | None) -> None:
        """Set or clear the generated ``public_endpoint`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        public_endpoint: PublicEndpointSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PublicEndpointSpec(_Message):
    @property
    def allowed_cidrs(self) -> _MutableSequence[_builtins.str]:
        """List of CIDR blocks from which access to public endpoint is allowed.\nIf field is not set, or list is empty, it means that access is not restricted at all."""
        ...
    @allowed_cidrs.setter
    def allowed_cidrs(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``allowed_cidrs`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        allowed_cidrs: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class KubeNetworkSpec(_Message):
    @property
    def service_cidrs(self) -> _MutableSequence[_builtins.str]:
        """CIDR blocks for Service ClusterIP allocation.\nFor now, only one value is supported.\nMust be a valid CIDR block or prefix length.\nIn case of prefix length, certain CIDR is auto allocated.\nSpecified CIDR blocks will be reserved in Cluster.spec.control\\_plane.subnet\\_id to prevent address duplication.\nAllowed prefix length is from \"/12\" to \"/28\".\nEmpty value treated as [\"/16\"]."""
        ...
    @service_cidrs.setter
    def service_cidrs(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``service_cidrs`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        service_cidrs: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class AuditLogsSpec(_Message):
    def __init__(self, initial_message: _SerializableMessage | None = None) -> None:
        """Create a message from a source message and field values."""
        ...

class Karpenter(_Message):
    def __init__(self, initial_message: _SerializableMessage | None = None) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterStatus__State(_Enum):
    STATE_UNSPECIFIED = ...
    PROVISIONING = ...
    RUNNING = ...
    DELETING = ...

class ClusterStatus(_Message):
    State: _TypeAlias = ClusterStatus__State
    @property
    def state(self) -> ClusterStatus__State: ...
    @state.setter
    def state(self, value: ClusterStatus__State | None) -> None:
        """Set or clear the generated ``state`` field."""
        ...
    @property
    def control_plane(self) -> ControlPlaneStatus: ...
    @control_plane.setter
    def control_plane(self, value: ControlPlaneStatus | None) -> None:
        """Set or clear the generated ``control_plane`` field."""
        ...
    @property
    def events(self) -> _MutableSequence[_type_nebius_common_v1_RecurrentResourceEvent]: ...
    @events.setter
    def events(self, value: _Iterable[_type_nebius_common_v1_RecurrentResourceEvent] | None) -> None:
        """Set or clear the generated ``events`` field."""
        ...
    @property
    def reconciling(self) -> _builtins.bool:
        """Show that changes are in flight"""
        ...
    @reconciling.setter
    def reconciling(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``reconciling`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        state: ClusterStatus__State | None | _UnsetType = ...,
        control_plane: ControlPlaneStatus | None | _UnsetType = ...,
        events: _Iterable[_type_nebius_common_v1_RecurrentResourceEvent] | None | _UnsetType = ...,
        reconciling: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ControlPlaneStatus(_Message):
    @property
    def version(self) -> _builtins.str:
        """Actual Kubernetes and configuration version.\nVersion has format ``<major>.<minor>.<patch>-nebius-cp.<infra_version>`` like\n\"1.30.0-nebius-cp.3\", where ``<major>.<minor>.<patch>`` is Kubernetes version and ``<infra_version>`` is version of control plane\ninfrastructure and configuration, updating of which may include bug fixes, security updates and new features of components running on\ncontrol plane, like CCM or Cluster Autoscaler."""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def endpoints(self) -> ControlPlaneStatusEndpoints: ...
    @endpoints.setter
    def endpoints(self, value: ControlPlaneStatusEndpoints | None) -> None:
        """Set or clear the generated ``endpoints`` field."""
        ...
    @property
    def etcd_cluster_size(self) -> _builtins.int:
        """Number of instances in etcd cluster."""
        ...
    @etcd_cluster_size.setter
    def etcd_cluster_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``etcd_cluster_size`` field."""
        ...
    @property
    def auth(self) -> ControlPlaneStatusAuth: ...
    @auth.setter
    def auth(self, value: ControlPlaneStatusAuth | None) -> None:
        """Set or clear the generated ``auth`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        version: _builtins.str | None | _UnsetType = ...,
        endpoints: ControlPlaneStatusEndpoints | None | _UnsetType = ...,
        etcd_cluster_size: _builtins.int | None | _UnsetType = ...,
        auth: ControlPlaneStatusAuth | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ControlPlaneStatusEndpoints(_Message):
    """Endpoints of Kubernetes control plane. Kubernetes API can be accessed at ``https://endpoint/``."""
    @property
    def public_endpoint(self) -> _builtins.str:
        """DNS name or IP address accessible from the Internet."""
        ...
    @public_endpoint.setter
    def public_endpoint(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``public_endpoint`` field."""
        ...
    @property
    def private_endpoint(self) -> _builtins.str:
        """DNS name or IP address accessible from the user VPC."""
        ...
    @private_endpoint.setter
    def private_endpoint(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``private_endpoint`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        public_endpoint: _builtins.str | None | _UnsetType = ...,
        private_endpoint: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ControlPlaneStatusAuth(_Message):
    @property
    def cluster_ca_certificate(self) -> _builtins.str:
        """PEM with the Cluster Certificate Authority, that must be used for TLS connection to Kubernetes API."""
        ...
    @cluster_ca_certificate.setter
    def cluster_ca_certificate(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_ca_certificate`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_ca_certificate: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class CreateClusterRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec: ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def resource_version(self) -> _builtins.str: ...
    @resource_version.setter
    def resource_version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_version`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        resource_version: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClustersRequest(_Message):
    @property
    def parent_id(self) -> _builtins.str:
        """ID of the IAM container we are listing the resources in."""
        ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    @property
    def page_size(self) -> _builtins.int:
        """Specifies the maximum number of items to return in the response."""
        ...
    @page_size.setter
    def page_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``page_size`` field."""
        ...
    @property
    def page_token(self) -> _builtins.str:
        """Token for pagination, allowing the retrieval of the next set of results."""
        ...
    @page_token.setter
    def page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        parent_id: _builtins.str | None | _UnsetType = ...,
        page_size: _builtins.int | None | _UnsetType = ...,
        page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClustersResponse(_Message):
    @property
    def items(self) -> _MutableSequence[Cluster]: ...
    @items.setter
    def items(self, value: _Iterable[Cluster] | None) -> None:
        """Set or clear the generated ``items`` field."""
        ...
    @property
    def next_page_token(self) -> _builtins.str: ...
    @next_page_token.setter
    def next_page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``next_page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        items: _Iterable[Cluster] | None | _UnsetType = ...,
        next_page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class UpdateClusterRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata:
        """Metadata associated with the instance.\nIncludes ID of the instance to update."""
        ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec:
        """Updated specifications for the instance."""
        ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class DeleteClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClusterControlPlaneVersionsRequest(_Message):
    def __init__(self, initial_message: _SerializableMessage | None = None) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClusterControlPlaneVersionsResponse(_Message):
    @property
    def items(self) -> _MutableSequence[ClusterControlPlaneVersion]: ...
    @items.setter
    def items(self, value: _Iterable[ClusterControlPlaneVersion] | None) -> None:
        """Set or clear the generated ``items`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        items: _Iterable[ClusterControlPlaneVersion] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterControlPlaneVersion(_Message):
    @property
    def version(self) -> _builtins.str:
        """Format of the version includes only MAJOR.MINOR, the same as can be passed to cluster creation API. For example \"1.31\"."""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def restricted(self) -> _builtins.bool:
        """Restricted shows versions available only for internal Nebius use, mostly those about to get released to public.\nTo use such versions - a feature restricted\\_k8s\\_versions should be enabled on a cluster."""
        ...
    @restricted.setter
    def restricted(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``restricted`` field."""
        ...
    @property
    def end_of_life(self) -> _datetime | None:
        """EndOfLife determines when the version will be forced out of use."""
        ...
    @end_of_life.setter
    def end_of_life(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``end_of_life`` field."""
        ...
    @property
    def deprecated(self) -> _builtins.bool:
        """Deprecated marks version to be soon deleted from API.\nCreation of clusters with this version is forbidden."""
        ...
    @deprecated.setter
    def deprecated(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``deprecated`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        version: _builtins.str | None | _UnsetType = ...,
        restricted: _builtins.bool | None | _UnsetType = ...,
        end_of_life: _datetime | _SerializableMessage | None | _UnsetType = ...,
        deprecated: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class DiskSpec__DiskType(_Enum):
    UNSPECIFIED = ...
    NETWORK_SSD = ...
    NETWORK_HDD = ...
    NETWORK_SSD_IO_M3 = ...
    NETWORK_SSD_NON_REPLICATED = ...

class DiskSpec(_Message):
    DiskType: _TypeAlias = DiskSpec__DiskType
    class __OneOfClass_size__(_OneOf):
        name: _Literal["size"] = ...

    class __OneOfClass_size_size_bytes__(__OneOfClass_size__):
        field: _Literal["size_bytes"] = ...
        @property
        def value(self) -> _builtins.int: ...

    class __OneOfClass_size_size_kibibytes__(__OneOfClass_size__):
        field: _Literal["size_kibibytes"] = ...
        @property
        def value(self) -> _builtins.int: ...

    class __OneOfClass_size_size_mebibytes__(__OneOfClass_size__):
        field: _Literal["size_mebibytes"] = ...
        @property
        def value(self) -> _builtins.int: ...

    class __OneOfClass_size_size_gibibytes__(__OneOfClass_size__):
        field: _Literal["size_gibibytes"] = ...
        @property
        def value(self) -> _builtins.int: ...

    @property
    def size(
        self,
    ) -> (
        __OneOfClass_size_size_bytes__
        | __OneOfClass_size_size_kibibytes__
        | __OneOfClass_size_size_mebibytes__
        | __OneOfClass_size_size_gibibytes__
        | None
    ): ...
    @property
    def size_bytes(self) -> _builtins.int | None: ...
    @size_bytes.setter
    def size_bytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``size_bytes`` field."""
        ...
    @property
    def size_kibibytes(self) -> _builtins.int | None: ...
    @size_kibibytes.setter
    def size_kibibytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``size_kibibytes`` field."""
        ...
    @property
    def size_mebibytes(self) -> _builtins.int | None: ...
    @size_mebibytes.setter
    def size_mebibytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``size_mebibytes`` field."""
        ...
    @property
    def size_gibibytes(self) -> _builtins.int | None: ...
    @size_gibibytes.setter
    def size_gibibytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``size_gibibytes`` field."""
        ...
    @property
    def block_size_bytes(self) -> _builtins.int: ...
    @block_size_bytes.setter
    def block_size_bytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``block_size_bytes`` field."""
        ...
    @property
    def type(self) -> DiskSpec__DiskType: ...
    @type.setter
    def type(self, value: DiskSpec__DiskType | None) -> None:
        """Set or clear the generated ``type`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        size_bytes: _builtins.int | None | _UnsetType = ...,
        size_kibibytes: _builtins.int | None | _UnsetType = ...,
        size_mebibytes: _builtins.int | None | _UnsetType = ...,
        size_gibibytes: _builtins.int | None | _UnsetType = ...,
        block_size_bytes: _builtins.int | None | _UnsetType = ...,
        type: DiskSpec__DiskType | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourcesSpec(_Message):
    class __OneOfClass_size__(_OneOf):
        name: _Literal["size"] = ...

    class __OneOfClass_size_preset__(__OneOfClass_size__):
        field: _Literal["preset"] = ...
        @property
        def value(self) -> _builtins.str: ...

    @property
    def size(self) -> __OneOfClass_size_preset__ | None: ...
    @property
    def platform(self) -> _builtins.str: ...
    @platform.setter
    def platform(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``platform`` field."""
        ...
    @property
    def preset(self) -> _builtins.str | None: ...
    @preset.setter
    def preset(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``preset`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        platform: _builtins.str | None | _UnsetType = ...,
        preset: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ConditionStatus(_Enum):
    CONDITION_STATUS_UNSPECIFIED = ...
    TRUE = ...
    FALSE = ...
    UNKNOWN = ...

class NodeGroup(_Message):
    """NodeGroup represents Kubernetes node pool - set of worker machines having the same configuration.\nA Node is a Nebius Compute Instance created in Cluster.metadata.parent\\_id container, running kubelet\nthat registers in Kubernetes API and a Node object created."""
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> NodeGroupSpec: ...
    @spec.setter
    def spec(self, value: NodeGroupSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    @property
    def status(self) -> NodeGroupStatus: ...
    @status.setter
    def status(self, value: NodeGroupStatus | None) -> None:
        """Set or clear the generated ``status`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: NodeGroupSpec | None | _UnsetType = ...,
        status: NodeGroupStatus | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupSpec(_Message):
    class __OneOfClass_size__(_OneOf):
        name: _Literal["size"] = ...

    class __OneOfClass_size_fixed_node_count__(__OneOfClass_size__):
        """Number of nodes in the group. Can be changed manually at any time, except for a node group with NVLink."""

        field: _Literal["fixed_node_count"] = ...
        @property
        def value(self) -> _builtins.int:
            """Number of nodes in the group. Can be changed manually at any time, except for a node group with NVLink."""
            ...

    class __OneOfClass_size_autoscaling__(__OneOfClass_size__):
        """Enables `Kubernetes Cluster Autoscaler <https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler>`__\nfor that NodeGroup, and defines autoscaling parameters."""

        field: _Literal["autoscaling"] = ...
        @property
        def value(self) -> NodeGroupAutoscalingSpec:
            """Enables `Kubernetes Cluster Autoscaler <https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler>`__\nfor that NodeGroup, and defines autoscaling parameters."""
            ...

    @property
    def size(self) -> __OneOfClass_size_fixed_node_count__ | __OneOfClass_size_autoscaling__ | None: ...
    @property
    def version(self) -> _builtins.str:
        """Version is desired Kubernetes version of the cluster. For now only acceptable format is\n\\ ``<major>.<minor>`` like \"1.31\". Option for patch version update will be added later.\nBy default the cluster control plane ``<major>.<minor>`` version will be used."""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def fixed_node_count(self) -> _builtins.int | None:
        """Number of nodes in the group. Can be changed manually at any time, except for a node group with NVLink."""
        ...
    @fixed_node_count.setter
    def fixed_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``fixed_node_count`` field."""
        ...
    @property
    def autoscaling(self) -> NodeGroupAutoscalingSpec | None:
        """Enables `Kubernetes Cluster Autoscaler <https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler>`__\nfor that NodeGroup, and defines autoscaling parameters."""
        ...
    @autoscaling.setter
    def autoscaling(self, value: NodeGroupAutoscalingSpec | None) -> None:
        """Set or clear the generated ``autoscaling`` field."""
        ...
    @property
    def template(self) -> NodeTemplate:
        """Parameters for Kubernetes Node object and Nebius Compute Instance\nIf not written opposite a NodeTemplate field update will cause NodeGroup roll-out according NodeGroupDeploymentStrategy."""
        ...
    @template.setter
    def template(self, value: NodeTemplate | None) -> None:
        """Set or clear the generated ``template`` field."""
        ...
    @property
    def strategy(self) -> NodeGroupDeploymentStrategy:
        """Defines deployment - roll-out, or nodes re-creation during configuration change.\nAllows to setup compromise in roll-out speed, extra resources consumption and workloads disruption."""
        ...
    @strategy.setter
    def strategy(self, value: NodeGroupDeploymentStrategy | None) -> None:
        """Set or clear the generated ``strategy`` field."""
        ...
    @property
    def auto_repair(self) -> NodeGroupAutoRepairSpec:
        """Parameters for nodes auto repair."""
        ...
    @auto_repair.setter
    def auto_repair(self, value: NodeGroupAutoRepairSpec | None) -> None:
        """Set or clear the generated ``auto_repair`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        version: _builtins.str | None | _UnsetType = ...,
        fixed_node_count: _builtins.int | None | _UnsetType = ...,
        autoscaling: NodeGroupAutoscalingSpec | None | _UnsetType = ...,
        template: NodeTemplate | None | _UnsetType = ...,
        strategy: NodeGroupDeploymentStrategy | None | _UnsetType = ...,
        auto_repair: NodeGroupAutoRepairSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeTemplate(_Message):
    @property
    def metadata(self) -> NodeMetadataTemplate: ...
    @metadata.setter
    def metadata(self, value: NodeMetadataTemplate | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def taints(self) -> _MutableSequence[NodeTaint]:
        """Kubernetes Node taints.\nFor now change will not be propagated to existing nodes, so will be applied only to Kubernetes Nodes created after the field change.\nThat behaviour may change later.\nSo, for now you will need to manually set them to existing nodes, if that is needed.\nField change will NOT trigger NodeGroup roll out."""
        ...
    @taints.setter
    def taints(self, value: _Iterable[NodeTaint] | None) -> None:
        """Set or clear the generated ``taints`` field."""
        ...
    @property
    def resources(self) -> ResourcesSpec:
        """Resources that will have Nebius Compute Instance where Node kubelet will run."""
        ...
    @resources.setter
    def resources(self, value: ResourcesSpec | None) -> None:
        """Set or clear the generated ``resources`` field."""
        ...
    @property
    def boot_disk(self) -> DiskSpec:
        """Parameters of a Node Nebius Compute Instance boot disk."""
        ...
    @boot_disk.setter
    def boot_disk(self, value: DiskSpec | None) -> None:
        """Set or clear the generated ``boot_disk`` field."""
        ...
    @property
    def gpu_settings(self) -> GpuSettings:
        """GPU-related settings."""
        ...
    @gpu_settings.setter
    def gpu_settings(self, value: GpuSettings | None) -> None:
        """Set or clear the generated ``gpu_settings`` field."""
        ...
    @property
    def os(self) -> _builtins.str:
        """OS version that will be used to create the boot disk of Compute Instances in the NodeGroup.\nSupported OS depend on the platform and Kubernetes version.\nTo get the up-to-date list of supported OS for a given Kubernetes version and platform, run:\nnebius mk8s node-group get-compatibility-matrix --cluster-kubernetes-version VERSION --platform PLATFORM"""
        ...
    @os.setter
    def os(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``os`` field."""
        ...
    @property
    def gpu_cluster(self) -> GpuClusterSpec:
        """Nebius Compute GPUCluster ID that will be attached to node."""
        ...
    @gpu_cluster.setter
    def gpu_cluster(self, value: GpuClusterSpec | None) -> None:
        """Set or clear the generated ``gpu_cluster`` field."""
        ...
    @property
    def network_interfaces(self) -> _MutableSequence[NetworkInterfaceTemplate]: ...
    @network_interfaces.setter
    def network_interfaces(self, value: _Iterable[NetworkInterfaceTemplate] | None) -> None:
        """Set or clear the generated ``network_interfaces`` field."""
        ...
    @property
    def filesystems(self) -> _MutableSequence[AttachedFilesystemSpec]:
        """Static attachments of Compute Filesystem.\nCan be used as a workaround, until CSI for Compute Disk and Filesystem will be available."""
        ...
    @filesystems.setter
    def filesystems(self, value: _Iterable[AttachedFilesystemSpec] | None) -> None:
        """Set or clear the generated ``filesystems`` field."""
        ...
    @property
    def cloud_init_user_data(self) -> _builtins.str:
        """cloud-init user-data\nShould contain at least one SSH key."""
        ...
    @cloud_init_user_data.setter
    def cloud_init_user_data(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cloud_init_user_data`` field."""
        ...
    @property
    def service_account_id(self) -> _builtins.str:
        """the Nebius service account whose credentials will be available on the nodes of the group.\nWith these credentials, it is possible to make ``nebius`` CLI or public API requests from the nodes\nwithout the need for extra authentication.\nThis service account is also used to make requests to container registry.\n\n``resource.serviceaccount.issueAccessToken`` permission is required to use this field."""
        ...
    @service_account_id.setter
    def service_account_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``service_account_id`` field."""
        ...
    @property
    def preemptible(self) -> PreemptibleSpec:
        """Configures whether the nodes in the group are preemptible.\nSet to empty value to enable preemptible nodes."""
        ...
    @preemptible.setter
    def preemptible(self, value: PreemptibleSpec | None) -> None:
        """Set or clear the generated ``preemptible`` field."""
        ...
    @property
    def nvlink(self) -> NVLinkSpec:
        """NVLinkSpec configures NVLink settings for the NodeGroup."""
        ...
    @nvlink.setter
    def nvlink(self, value: NVLinkSpec | None) -> None:
        """Set or clear the generated ``nvlink`` field."""
        ...
    @property
    def reservation_policy(self) -> ReservationPolicy:
        """reservation\\_policy is an interface of the \"capacity block\" (or \"capacity block group\") mechanism of Nebius Compute."""
        ...
    @reservation_policy.setter
    def reservation_policy(self, value: ReservationPolicy | None) -> None:
        """Set or clear the generated ``reservation_policy`` field."""
        ...
    @property
    def local_disks(self) -> LocalDisksSpec:
        """local\\_disks enables the provisioning of fast local drives.\nThis type of storage is strictly ephemeral: on node restart, all data is erased, similar to RAM."""
        ...
    @local_disks.setter
    def local_disks(self, value: LocalDisksSpec | None) -> None:
        """Set or clear the generated ``local_disks`` field."""
        ...
    @property
    def max_pods(self) -> _builtins.int:
        """The maximum number of Pods per node for your cluster. If omitted, MK8S assigns the default value of 110. When you\nconfigure the maximum number of Pods per node for the cluster, MK8S uses this value to allocate a CIDR range for every node\nin group. The node CIDR prefix is calculated as ``32 - ceil(log2(2 * max_pods))``, i.e. the smallest IPv4 subnet whose total address\ncount is at least ``2 * max_pods``. Not all IPs are usable for workload Pods because some of them are consumed by system Pods."""
        ...
    @max_pods.setter
    def max_pods(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``max_pods`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: NodeMetadataTemplate | None | _UnsetType = ...,
        taints: _Iterable[NodeTaint] | None | _UnsetType = ...,
        resources: ResourcesSpec | None | _UnsetType = ...,
        boot_disk: DiskSpec | None | _UnsetType = ...,
        gpu_settings: GpuSettings | None | _UnsetType = ...,
        os: _builtins.str | None | _UnsetType = ...,
        gpu_cluster: GpuClusterSpec | None | _UnsetType = ...,
        network_interfaces: _Iterable[NetworkInterfaceTemplate] | None | _UnsetType = ...,
        filesystems: _Iterable[AttachedFilesystemSpec] | None | _UnsetType = ...,
        cloud_init_user_data: _builtins.str | None | _UnsetType = ...,
        service_account_id: _builtins.str | None | _UnsetType = ...,
        preemptible: PreemptibleSpec | None | _UnsetType = ...,
        nvlink: NVLinkSpec | None | _UnsetType = ...,
        reservation_policy: ReservationPolicy | None | _UnsetType = ...,
        local_disks: LocalDisksSpec | None | _UnsetType = ...,
        max_pods: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NVLinkSpec(_Message):
    class __OneOfClass_nvl_group__(_OneOf):
        name: _Literal["nvl_group"] = ...

    class __OneOfClass_nvl_group_nvl_instance_group_id__(__OneOfClass_nvl_group__):
        """Existing NVLInstanceGroup ID to use."""

        field: _Literal["nvl_instance_group_id"] = ...
        @property
        def value(self) -> _builtins.str:
            """Existing NVLInstanceGroup ID to use."""
            ...

    @property
    def nvl_group(self) -> __OneOfClass_nvl_group_nvl_instance_group_id__ | None: ...
    @property
    def nvl_instance_group_id(self) -> _builtins.str | None:
        """Existing NVLInstanceGroup ID to use."""
        ...
    @nvl_instance_group_id.setter
    def nvl_instance_group_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``nvl_instance_group_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        nvl_instance_group_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeMetadataTemplate(_Message):
    @property
    def labels(self) -> _MutableMapping[_builtins.str, _builtins.str]:
        """Kubernetes Node labels.\n\nKeys and values must follow Kubernetes label syntax:\nhttps://kubernetes.io/docs/concepts/overview/working-with-objects/labels/\n\nFor now change will not be propagated to existing nodes, so will be applied only to Kubernetes Nodes created after the field change.\nThat behavior may change later.\nSo, for now you will need to manually set them to existing nodes, if that is needed.\n\nSystem labels containing \"kubernetes.io\" and \"k8s.io\" will be ignored.\nField change will NOT trigger NodeGroup roll out."""
        ...
    @labels.setter
    def labels(self, value: _Mapping[_builtins.str, _builtins.str] | None) -> None:
        """Set or clear the generated ``labels`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        labels: _Mapping[_builtins.str, _builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GpuSettings(_Message):
    """GPU-related settings."""
    @property
    def drivers_preset(self) -> _builtins.str:
        """Identifier of the predefined set of drivers included in the ComputeImage deployed on ComputeInstances that are part of the NodeGroup.\nSupported presets depend on the platform and Kubernetes version.\nTo get the up-to-date list of supported presets for a given Kubernetes version and platform, run:\nnebius mk8s node-group get-compatibility-matrix --cluster-kubernetes-version VERSION --platform PLATFORM\nLeave empty for GPU nodes that do not have preinstalled drivers, including DRA-enabled node groups."""
        ...
    @drivers_preset.setter
    def drivers_preset(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``drivers_preset`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        drivers_preset: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GpuClusterSpec(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NetworkInterfaceTemplate(_Message):
    @property
    def public_ip_address(self) -> PublicIPAddress:
        """Parameters for Public IPv4 address associated with the interface.\nSet to empty value, to enable it."""
        ...
    @public_ip_address.setter
    def public_ip_address(self, value: PublicIPAddress | None) -> None:
        """Set or clear the generated ``public_ip_address`` field."""
        ...
    @property
    def subnet_id(self) -> _builtins.str:
        """Nebius VPC Subnet ID that will be attached to a node cloud instance network interface.\nBy default Cluster control plane subnet\\_id used.\nSubnet should be located in the same network with control plane."""
        ...
    @subnet_id.setter
    def subnet_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``subnet_id`` field."""
        ...
    @property
    def security_groups(self) -> _MutableSequence[SecurityGroup]:
        """User provided VPC Security Groups which will be assigned to all nodes of this NodeGroup."""
        ...
    @security_groups.setter
    def security_groups(self, value: _Iterable[SecurityGroup] | None) -> None:
        """Set or clear the generated ``security_groups`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        public_ip_address: PublicIPAddress | None | _UnsetType = ...,
        subnet_id: _builtins.str | None | _UnsetType = ...,
        security_groups: _Iterable[SecurityGroup] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PublicIPAddress(_Message):
    """Describes a public IP address."""
    def __init__(self, initial_message: _SerializableMessage | None = None) -> None:
        """Create a message from a source message and field values."""
        ...

class SecurityGroup(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class AttachedFilesystemSpec__AttachMode(_Enum):
    UNSPECIFIED = ...
    READ_ONLY = ...
    READ_WRITE = ...

class AttachedFilesystemSpec(_Message):
    AttachMode: _TypeAlias = AttachedFilesystemSpec__AttachMode
    class __OneOfClass_type__(_OneOf):
        name: _Literal["type"] = ...

    class __OneOfClass_type_existing_filesystem__(__OneOfClass_type__):
        field: _Literal["existing_filesystem"] = ...
        @property
        def value(self) -> ExistingFilesystem: ...

    @property
    def type(self) -> __OneOfClass_type_existing_filesystem__ | None: ...
    @property
    def attach_mode(self) -> AttachedFilesystemSpec__AttachMode: ...
    @attach_mode.setter
    def attach_mode(self, value: AttachedFilesystemSpec__AttachMode | None) -> None:
        """Set or clear the generated ``attach_mode`` field."""
        ...
    @property
    def mount_tag(self) -> _builtins.str:
        """Specifies the user-defined identifier, allowing to use it as a device in mount command."""
        ...
    @mount_tag.setter
    def mount_tag(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``mount_tag`` field."""
        ...
    @property
    def existing_filesystem(self) -> ExistingFilesystem | None: ...
    @existing_filesystem.setter
    def existing_filesystem(self, value: ExistingFilesystem | None) -> None:
        """Set or clear the generated ``existing_filesystem`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        attach_mode: AttachedFilesystemSpec__AttachMode | None | _UnsetType = ...,
        mount_tag: _builtins.str | None | _UnsetType = ...,
        existing_filesystem: ExistingFilesystem | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ExistingFilesystem(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupAutoscalingSpec(_Message):
    @property
    def min_node_count(self) -> _builtins.int: ...
    @min_node_count.setter
    def min_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``min_node_count`` field."""
        ...
    @property
    def max_node_count(self) -> _builtins.int: ...
    @max_node_count.setter
    def max_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``max_node_count`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        min_node_count: _builtins.int | None | _UnsetType = ...,
        max_node_count: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeTaint__Effect(_Enum):
    EFFECT_UNSPECIFIED = ...
    NO_EXECUTE = ...
    NO_SCHEDULE = ...
    PREFER_NO_SCHEDULE = ...

class NodeTaint(_Message):
    """See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/"""

    Effect: _TypeAlias = NodeTaint__Effect
    @property
    def key(self) -> _builtins.str: ...
    @key.setter
    def key(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``key`` field."""
        ...
    @property
    def value(self) -> _builtins.str: ...
    @value.setter
    def value(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``value`` field."""
        ...
    @property
    def effect(self) -> NodeTaint__Effect: ...
    @effect.setter
    def effect(self, value: NodeTaint__Effect | None) -> None:
        """Set or clear the generated ``effect`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        key: _builtins.str | None | _UnsetType = ...,
        value: _builtins.str | None | _UnsetType = ...,
        effect: NodeTaint__Effect | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupDeploymentStrategy(_Message):
    @property
    def max_unavailable(self) -> PercentOrCount:
        """The maximum number of nodes that can be simultaneously unavailable during the update process.\n\nThis value can be specified either as an absolute number (for example 3) or as a percentage of the desired\nnumber of nodes (for example 5%).\n\nWhen specified as a percentage, the actual number is calculated by rounding down to the nearest whole number.\nThis value cannot be 0 if ``max_surge`` is also set to 0.\n\nOn 2026-08-01, defaults to 0.\nIMPORTANT: starting from Q3 2026 new default is 1;\nfor new clusters it will default to 1,\nnode groups in existing clusters will be gradually migrated during Q3 to the default of 1 as well.\nTo get the actual value for your node group, please see 'strategy' in its status.\n\nExample: If set to 20%, up to 20% of the nodes can be taken offline at once during the update,\nensuring that at least 80% of the desired nodes remain operational."""
        ...
    @max_unavailable.setter
    def max_unavailable(self, value: PercentOrCount | None) -> None:
        """Set or clear the generated ``max_unavailable`` field."""
        ...
    @property
    def max_surge(self) -> PercentOrCount:
        """The maximum number of additional nodes that can be provisioned above the desired number of nodes during the update process.\n\nThis value can be specified either as an absolute number (for example 3) or as a percentage of the desired\nnumber of nodes (for example 5%).\n\nWhen specified as a percentage, the actual number is calculated by rounding up to the nearest whole number.\nThis value cannot be 0 if ``max_unavailable`` is also set to 0.\n\nOn 2026-08-01, defaults to 1.\nIMPORTANT: starting from Q3 2026 new default is 0;\nfor new clusters it will default to 0,\nnode groups in existing clusters will be gradually migrated during Q3 to the default of 0 as well.\nTo get the actual value for your node group, please see 'strategy' in its status.\n\nExample: If set to 25%, the node group can scale up by an additional 25% during the update,\nallowing new nodes to be added before old nodes are removed, which helps minimize workload disruption.\n\nNOTE:\n\nit is user responsibility to ensure that there are enough quota for provision nodes above the desired number.\nAvailable quota effectively limits ``max_surge``.\nIn case of not enough quota even for one extra node, update operation will hung because of quota exhausted error.\nSuch error will be visible in Operation.progress\\_data."""
        ...
    @max_surge.setter
    def max_surge(self, value: PercentOrCount | None) -> None:
        """Set or clear the generated ``max_surge`` field."""
        ...
    @property
    def drain_timeout(self) -> _timedelta | None:
        """Maximum amount of time that the service will spend attempting to gracefully drain a node\n(evicting its pods) before falling back to pod deletion.\nA value of 0 means no timeout: the node can be drained for an unlimited time.\nImportant consequence of that is if PodDisruptionBudget doesn't allow evicting a pod,\nthen NodeGroup update with node re-creation will hang on that pod eviction.\nNote that this is different from ``kubectl drain --timeout``, which gives up and returns an error.\n\nOn 2026-08-01, defaults to 0.\nIMPORTANT: starting from Q3 2026 new default is 10m;\nfor new clusters it will default to 10m,\nnode groups in existing clusters will be gradually migrated during Q3 to the default of 10m as well.\nTo get the actual value for your node group, please see 'strategy' in its status."""
        ...
    @drain_timeout.setter
    def drain_timeout(self, value: _timedelta | _SerializableMessage | None) -> None:
        """Set or clear the generated ``drain_timeout`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        max_unavailable: PercentOrCount | None | _UnsetType = ...,
        max_surge: PercentOrCount | None | _UnsetType = ...,
        drain_timeout: _timedelta | _SerializableMessage | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PercentOrCount(_Message):
    class __OneOfClass_value__(_OneOf):
        name: _Literal["value"] = ...

    class __OneOfClass_value_percent__(__OneOfClass_value__):
        field: _Literal["percent"] = ...
        @property
        def value(self) -> _builtins.int: ...

    class __OneOfClass_value_count__(__OneOfClass_value__):
        field: _Literal["count"] = ...
        @property
        def value(self) -> _builtins.int: ...

    @property
    def value(self) -> __OneOfClass_value_percent__ | __OneOfClass_value_count__ | None: ...
    @property
    def percent(self) -> _builtins.int | None: ...
    @percent.setter
    def percent(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``percent`` field."""
        ...
    @property
    def count(self) -> _builtins.int | None: ...
    @count.setter
    def count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``count`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        percent: _builtins.int | None | _UnsetType = ...,
        count: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupAutoRepairSpec(_Message):
    @property
    def conditions(self) -> _MutableSequence[NodeAutoRepairCondition]:
        """Conditions that determine whether a node should be auto repaired."""
        ...
    @conditions.setter
    def conditions(self, value: _Iterable[NodeAutoRepairCondition] | None) -> None:
        """Set or clear the generated ``conditions`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        conditions: _Iterable[NodeAutoRepairCondition] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeAutoRepairCondition(_Message):
    class __OneOfClass_trigger__(_OneOf):
        name: _Literal["trigger"] = ...

    class __OneOfClass_trigger_timeout__(__OneOfClass_trigger__):
        """The duration after which the node is automatically repaired if the condition remains in the specified status."""

        field: _Literal["timeout"] = ...
        @property
        def value(self) -> _timedelta:
            """The duration after which the node is automatically repaired if the condition remains in the specified status."""
            ...

    class __OneOfClass_trigger_disabled__(__OneOfClass_trigger__):
        """When true, disables the default auto-repair condition rules."""

        field: _Literal["disabled"] = ...
        @property
        def value(self) -> _builtins.bool:
            """When true, disables the default auto-repair condition rules."""
            ...

    @property
    def trigger(self) -> __OneOfClass_trigger_timeout__ | __OneOfClass_trigger_disabled__ | None: ...
    @property
    def type(self) -> _builtins.str:
        """Node condition type."""
        ...
    @type.setter
    def type(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``type`` field."""
        ...
    @property
    def status(self) -> ConditionStatus:
        """Node condition status."""
        ...
    @status.setter
    def status(self, value: ConditionStatus | None) -> None:
        """Set or clear the generated ``status`` field."""
        ...
    @property
    def timeout(self) -> _timedelta | None:
        """The duration after which the node is automatically repaired if the condition remains in the specified status."""
        ...
    @timeout.setter
    def timeout(self, value: _timedelta | _SerializableMessage | None) -> None:
        """Set or clear the generated ``timeout`` field."""
        ...
    @property
    def disabled(self) -> _builtins.bool | None:
        """When true, disables the default auto-repair condition rules."""
        ...
    @disabled.setter
    def disabled(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``disabled`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        type: _builtins.str | None | _UnsetType = ...,
        status: ConditionStatus | None | _UnsetType = ...,
        timeout: _timedelta | _SerializableMessage | None | _UnsetType = ...,
        disabled: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PreemptibleSpec(_Message):
    def __init__(self, initial_message: _SerializableMessage | None = None) -> None:
        """Create a message from a source message and field values."""
        ...

class ReservationPolicy__Policy(_Enum):
    AUTO = ...
    """#. Will try to launch instance in any reservation\\_ids if provided.\n#. Will try to launch instance in any of the available capacity block.\n#. Will try to launch instance in PAYG if 1 & 2 are not satisfied."""
    FORBID = ...
    """The instance is launched only using on-demand (PAYG) capacity.\nNo attempt is made to find or use a Capacity Block.\nIt's an error to provide reservation\\_ids with policy = FORBID"""
    STRICT = ...
    """#. Will try to launch the instance in Capacity Blocks from reservation\\_ids if provided.\n#. If reservation\\_ids are not provided will try to launch instance in suitable & available Capacity Block.\n#. Fail otherwise."""

class ReservationPolicy(_Message):
    """ReservationPolicy is copied as-is from NebiusAPI ``compute/v1/instance.proto``."""

    Policy: _TypeAlias = ReservationPolicy__Policy
    @property
    def policy(self) -> ReservationPolicy__Policy: ...
    @policy.setter
    def policy(self, value: ReservationPolicy__Policy | None) -> None:
        """Set or clear the generated ``policy`` field."""
        ...
    @property
    def reservation_ids(self) -> _MutableSequence[_builtins.str]:
        """Capacity block groups, order matters"""
        ...
    @reservation_ids.setter
    def reservation_ids(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``reservation_ids`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        policy: ReservationPolicy__Policy | None | _UnsetType = ...,
        reservation_ids: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class LocalDisksSpec(_Message):
    class __OneOfClass_request__(_OneOf):
        name: _Literal["request"] = ...

    class __OneOfClass_request_passthrough_group__(__OneOfClass_request__):
        """Requests passthrough local disks from the host.\nTopology of the provided disks is preserved during stop and start\nfor every instance of a specific platform and preset in the region."""

        field: _Literal["passthrough_group"] = ...
        @property
        def value(self) -> PassthroughGroupRequest:
            """Requests passthrough local disks from the host.\nTopology of the provided disks is preserved during stop and start\nfor every instance of a specific platform and preset in the region."""
            ...

    @property
    def request(self) -> __OneOfClass_request_passthrough_group__ | None: ...
    @property
    def passthrough_group(self) -> PassthroughGroupRequest | None:
        """Requests passthrough local disks from the host.\nTopology of the provided disks is preserved during stop and start\nfor every instance of a specific platform and preset in the region."""
        ...
    @passthrough_group.setter
    def passthrough_group(self, value: PassthroughGroupRequest | None) -> None:
        """Set or clear the generated ``passthrough_group`` field."""
        ...
    @property
    def config(self) -> LocalDisksSpecConfig:
        """config defines actions that managed Kubernetes service performs on mounted local disks\nto provide them inside Kubernetes cluster with a convenient interface.\n\nWhen omitted, a default value is generated."""
        ...
    @config.setter
    def config(self, value: LocalDisksSpecConfig | None) -> None:
        """Set or clear the generated ``config`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        passthrough_group: PassthroughGroupRequest | None | _UnsetType = ...,
        config: LocalDisksSpecConfig | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PassthroughGroupRequest(_Message):
    @property
    def requested(self) -> _builtins.bool:
        """Passthrough local disks from the underlying host.\n\nDevices are expected to appear in the guest as NVMe devices (nvme0, nvme1, ...),\nbut the exact number depends on the preset.\nEnabled only when this field is explicitly set."""
        ...
    @requested.setter
    def requested(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``requested`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        requested: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class LocalDisksSpecConfig(_Message):
    """LocalDisksSpecConfig defines actions that managed Kubernetes service performs on mounted local disks\nto provide them inside Kubernetes cluster with a convenient interface."""
    class __OneOfClass_type__(_OneOf):
        name: _Literal["type"] = ...

    class __OneOfClass_type_none__(__OneOfClass_type__):
        """none: \"do nothing\" - local disks will be provisioned as on a regular compute instance."""

        field: _Literal["none"] = ...
        @property
        def value(self) -> _builtins.bool:
            """none: \"do nothing\" - local disks will be provisioned as on a regular compute instance."""
            ...

    class __OneOfClass_type_kubelet_ephemeral__(__OneOfClass_type__):
        """kubelet\\_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node\nSee also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/\n\nThe default when LocalDisksSpecConfig is not set."""

        field: _Literal["kubelet_ephemeral"] = ...
        @property
        def value(self) -> _builtins.bool:
            """kubelet\\_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node\nSee also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/\n\nThe default when LocalDisksSpecConfig is not set."""
            ...

    @property
    def type(self) -> __OneOfClass_type_none__ | __OneOfClass_type_kubelet_ephemeral__ | None: ...
    @property
    def none(self) -> _builtins.bool | None:
        """none: \"do nothing\" - local disks will be provisioned as on a regular compute instance."""
        ...
    @none.setter
    def none(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``none`` field."""
        ...
    @property
    def kubelet_ephemeral(self) -> _builtins.bool | None:
        """kubelet\\_ephemeral: combine all local disks into a single storage volume and use it as kubelet's local ephemeral storage on the node\nSee also https://kubernetes.io/docs/concepts/storage/ephemeral-storage/\n\nThe default when LocalDisksSpecConfig is not set."""
        ...
    @kubelet_ephemeral.setter
    def kubelet_ephemeral(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``kubelet_ephemeral`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        none: _builtins.bool | None | _UnsetType = ...,
        kubelet_ephemeral: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupStatus__State(_Enum):
    STATE_UNSPECIFIED = ...
    PROVISIONING = ...
    RUNNING = ...
    DELETING = ...

class NodeGroupStatus(_Message):
    State: _TypeAlias = NodeGroupStatus__State
    @property
    def state(self) -> NodeGroupStatus__State: ...
    @state.setter
    def state(self, value: NodeGroupStatus__State | None) -> None:
        """Set or clear the generated ``state`` field."""
        ...
    @property
    def version(self) -> _builtins.str:
        """Actual version of NodeGroup. Have format ``<major>.<minor>.<patch>-nebius-node.<infra_version>`` like \"1.30.0-nebius-node.10\".\nWhere ``<major>.<minor>.<patch>`` is Kubernetes version and ``<infra_version>`` is version of Node infrastructure and configuration,\nwhich update may include bug fixes, security updates and new features depending on worker node configuration."""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def target_node_count(self) -> _builtins.int:
        """Desired total number of nodes that should be in the node group.\nIt is either ``NodeGroupSpec.fixed_node_count`` or arbitrary number between\n\\ ``NodeGroupAutoscalingSpec.min_node_count`` and ``NodeGroupAutoscalingSpec.max_node_count`` decided by autoscaler."""
        ...
    @target_node_count.setter
    def target_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``target_node_count`` field."""
        ...
    @property
    def node_count(self) -> _builtins.int:
        """Total number of nodes that are currently in the node group.\nBoth ready and not ready nodes are counted."""
        ...
    @node_count.setter
    def node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``node_count`` field."""
        ...
    @property
    def outdated_node_count(self) -> _builtins.int:
        """Total number of nodes that has outdated node configuration.\nThese nodes will be replaced by new nodes with up-to-date configuration."""
        ...
    @outdated_node_count.setter
    def outdated_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``outdated_node_count`` field."""
        ...
    @property
    def ready_node_count(self) -> _builtins.int:
        """Total number of nodes that successfully joined the cluster and are ready to serve workloads.\nBoth outdated and up-to-date nodes are counted."""
        ...
    @ready_node_count.setter
    def ready_node_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``ready_node_count`` field."""
        ...
    @property
    def events(self) -> _MutableSequence[_type_nebius_common_v1_RecurrentResourceEvent]: ...
    @events.setter
    def events(self, value: _Iterable[_type_nebius_common_v1_RecurrentResourceEvent] | None) -> None:
        """Set or clear the generated ``events`` field."""
        ...
    @property
    def strategy(self) -> NodeGroupDeploymentStrategy:
        """Deployment strategy used by the service for node group rollouts and node deletions.\nIt includes default values applied by the service. A drain\\_timeout value of 0 means\nthat node draining is not time-limited."""
        ...
    @strategy.setter
    def strategy(self, value: NodeGroupDeploymentStrategy | None) -> None:
        """Set or clear the generated ``strategy`` field."""
        ...
    @property
    def reconciling(self) -> _builtins.bool:
        """Show that there are changes are in flight."""
        ...
    @reconciling.setter
    def reconciling(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``reconciling`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        state: NodeGroupStatus__State | None | _UnsetType = ...,
        version: _builtins.str | None | _UnsetType = ...,
        target_node_count: _builtins.int | None | _UnsetType = ...,
        node_count: _builtins.int | None | _UnsetType = ...,
        outdated_node_count: _builtins.int | None | _UnsetType = ...,
        ready_node_count: _builtins.int | None | _UnsetType = ...,
        events: _Iterable[_type_nebius_common_v1_RecurrentResourceEvent] | None | _UnsetType = ...,
        strategy: NodeGroupDeploymentStrategy | None | _UnsetType = ...,
        reconciling: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetNodeGroupCompatibilityMatrixRequest(_Message):
    @property
    def cluster_kubernetes_version(self) -> _builtins.str:
        """Cluster kubernetes version."""
        ...
    @cluster_kubernetes_version.setter
    def cluster_kubernetes_version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_kubernetes_version`` field."""
        ...
    @property
    def platform(self) -> _builtins.str:
        """Hardware platform for which the capabilities are requested."""
        ...
    @platform.setter
    def platform(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``platform`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_kubernetes_version: _builtins.str | None | _UnsetType = ...,
        platform: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupCompatibilityMatrix(_Message):
    @property
    def versions(self) -> _MutableSequence[NodeGroupCompatibilityVersion]:
        """List of available versions."""
        ...
    @versions.setter
    def versions(self, value: _Iterable[NodeGroupCompatibilityVersion] | None) -> None:
        """Set or clear the generated ``versions`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        versions: _Iterable[NodeGroupCompatibilityVersion] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupCompatibilityVersion(_Message):
    @property
    def kubernetes_version(self) -> _builtins.str:
        """Kubernetes version."""
        ...
    @kubernetes_version.setter
    def kubernetes_version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``kubernetes_version`` field."""
        ...
    @property
    def items(self) -> _MutableSequence[NodeGroupCompatibilityVersionItem]:
        """List of available images."""
        ...
    @items.setter
    def items(self, value: _Iterable[NodeGroupCompatibilityVersionItem] | None) -> None:
        """Set or clear the generated ``items`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        kubernetes_version: _builtins.str | None | _UnsetType = ...,
        items: _Iterable[NodeGroupCompatibilityVersionItem] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NodeGroupCompatibilityVersionItem(_Message):
    @property
    def os(self) -> _builtins.str:
        """Operating system."""
        ...
    @os.setter
    def os(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``os`` field."""
        ...
    @property
    def drivers_preset(self) -> _builtins.str:
        """Drivers preset name."""
        ...
    @drivers_preset.setter
    def drivers_preset(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``drivers_preset`` field."""
        ...
    @property
    def compatible_platforms(self) -> _MutableSequence[_builtins.str]:
        """Hardware platforms."""
        ...
    @compatible_platforms.setter
    def compatible_platforms(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``compatible_platforms`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        os: _builtins.str | None | _UnsetType = ...,
        drivers_preset: _builtins.str | None | _UnsetType = ...,
        compatible_platforms: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class CreateNodeGroupRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> NodeGroupSpec: ...
    @spec.setter
    def spec(self, value: NodeGroupSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: NodeGroupSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetNodeGroupRequest(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def resource_version(self) -> _builtins.str: ...
    @resource_version.setter
    def resource_version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_version`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        resource_version: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListNodeGroupsRequest(_Message):
    @property
    def parent_id(self) -> _builtins.str:
        """ID of the parent Cluster."""
        ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    @property
    def page_size(self) -> _builtins.int:
        """Specifies the maximum number of items to return in the response."""
        ...
    @page_size.setter
    def page_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``page_size`` field."""
        ...
    @property
    def page_token(self) -> _builtins.str:
        """Token for pagination, allowing the retrieval of the next set of results."""
        ...
    @page_token.setter
    def page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        parent_id: _builtins.str | None | _UnsetType = ...,
        page_size: _builtins.int | None | _UnsetType = ...,
        page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListNodeGroupsResponse(_Message):
    @property
    def items(self) -> _MutableSequence[NodeGroup]: ...
    @items.setter
    def items(self, value: _Iterable[NodeGroup] | None) -> None:
        """Set or clear the generated ``items`` field."""
        ...
    @property
    def next_page_token(self) -> _builtins.str: ...
    @next_page_token.setter
    def next_page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``next_page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        items: _Iterable[NodeGroup] | None | _UnsetType = ...,
        next_page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class UpdateNodeGroupRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> NodeGroupSpec: ...
    @spec.setter
    def spec(self, value: NodeGroupSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: NodeGroupSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class DeleteNodeGroupRequest(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class UpgradeNodeGroupRequest(_Message):
    class __OneOfClass_upgrade_type__(_OneOf):
        name: _Literal["upgrade_type"] = ...

    class __OneOfClass_upgrade_type_latest_infra_version__(__OneOfClass_upgrade_type__):
        """Upgrades to the latest infra version, which includes latest supported kubernetes patch version. Kubernetes minor version remain the\nsame."""

        field: _Literal["latest_infra_version"] = ...
        @property
        def value(self) -> _type_google_protobuf_Empty:
            """Upgrades to the latest infra version, which includes latest supported kubernetes patch version. Kubernetes minor version remain the\nsame."""
            ...

    @property
    def upgrade_type(self) -> __OneOfClass_upgrade_type_latest_infra_version__ | None: ...
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def latest_infra_version(self) -> _type_google_protobuf_Empty | None:
        """Upgrades to the latest infra version, which includes latest supported kubernetes patch version. Kubernetes minor version remain the\nsame."""
        ...
    @latest_infra_version.setter
    def latest_infra_version(self, value: _type_google_protobuf_Empty | None) -> None:
        """Set or clear the generated ``latest_infra_version`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        latest_infra_version: _type_google_protobuf_Empty | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ProgressData(_Message):
    @property
    def problems(self) -> _MutableSequence[Problem]:
        """Problems encountered during the operation execution."""
        ...
    @problems.setter
    def problems(self, value: _Iterable[Problem] | None) -> None:
        """Set or clear the generated ``problems`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        problems: _Iterable[Problem] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Problem(_Message):
    @property
    def stage(self) -> _builtins.str:
        """Stage on which the problem occurred."""
        ...
    @stage.setter
    def stage(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``stage`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """Message describing the problem."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        stage: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterServiceClient(_ClientWithOperations[_type_nebius_common_v1_Operation, _Any]):
    """This class provides client methods for the ``nebius.mk8s.v1.ClusterService`` service."""
    def get(
        self, request: GetClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetClusterRequest, Cluster]:
        """Returns a specific mk8s cluster by its unique identifier.\n\nThe request object is returned without starting the RPC."""
        ...
    def get_by_name(
        self, request: _type_nebius_common_v1_GetByNameRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[_type_nebius_common_v1_GetByNameRequest, Cluster]:
        """Returns a specific mk8s cluster by its unique name.\n\nThe request object is returned without starting the RPC."""
        ...
    def list(
        self, request: ListClustersRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListClustersRequest, ListClustersResponse]:
        """Returns a list of all mk8s clusters in the specified project.\n\nThe request object is returned without starting the RPC."""
        ...
    def create(
        self, request: CreateClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[CreateClusterRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """Creates a new mk8s cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def update(
        self, request: UpdateClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[UpdateClusterRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """Modifies an existing mk8s cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def delete(
        self, request: DeleteClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[DeleteClusterRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """Deletes an mk8s cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def list_control_plane_versions(
        self, request: ListClusterControlPlaneVersionsRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListClusterControlPlaneVersionsRequest, ListClusterControlPlaneVersionsResponse]:
        """ListControlPlaneVersions returns all k8s release versions available in Nebius API.\n\nThe request object is returned without starting the RPC."""
        ...

class NodeGroupServiceClient(_ClientWithOperations[_type_nebius_common_v1_Operation, _Any]):
    """This class provides client methods for the ``nebius.mk8s.v1.NodeGroupService`` service."""
    def get(
        self, request: GetNodeGroupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetNodeGroupRequest, NodeGroup]:
        """The request object is returned without starting the RPC."""
        ...
    def get_by_name(
        self, request: _type_nebius_common_v1_GetByNameRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[_type_nebius_common_v1_GetByNameRequest, NodeGroup]:
        """The request object is returned without starting the RPC."""
        ...
    def list(
        self, request: ListNodeGroupsRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListNodeGroupsRequest, ListNodeGroupsResponse]:
        """The request object is returned without starting the RPC."""
        ...
    def create(
        self, request: CreateNodeGroupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[CreateNodeGroupRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """The request object is returned without starting the RPC."""
        ...
    def update(
        self, request: UpdateNodeGroupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[UpdateNodeGroupRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """The request object is returned without starting the RPC."""
        ...
    def delete(
        self, request: DeleteNodeGroupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[DeleteNodeGroupRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """The request object is returned without starting the RPC."""
        ...
    def upgrade(
        self, request: UpgradeNodeGroupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[UpgradeNodeGroupRequest, _AsyncOperation[_type_nebius_common_v1_Operation]]:
        """The request object is returned without starting the RPC."""
        ...
    def get_compatibility_matrix(
        self, request: GetNodeGroupCompatibilityMatrixRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetNodeGroupCompatibilityMatrixRequest, NodeGroupCompatibilityMatrix]:
        """The request object is returned without starting the RPC."""
        ...

__all__ = [
    "AttachedFilesystemSpec",
    "AuditLogsSpec",
    "Cluster",
    "ClusterControlPlaneVersion",
    "ClusterServiceClient",
    "ClusterSpec",
    "ClusterStatus",
    "ConditionStatus",
    "ControlPlaneEndpointsSpec",
    "ControlPlaneSpec",
    "ControlPlaneStatus",
    "ControlPlaneStatusAuth",
    "ControlPlaneStatusEndpoints",
    "CreateClusterRequest",
    "CreateNodeGroupRequest",
    "DeleteClusterRequest",
    "DeleteNodeGroupRequest",
    "DiskSpec",
    "ExistingFilesystem",
    "GetClusterRequest",
    "GetNodeGroupCompatibilityMatrixRequest",
    "GetNodeGroupRequest",
    "GpuClusterSpec",
    "GpuSettings",
    "Karpenter",
    "KubeNetworkSpec",
    "ListClusterControlPlaneVersionsRequest",
    "ListClusterControlPlaneVersionsResponse",
    "ListClustersRequest",
    "ListClustersResponse",
    "ListNodeGroupsRequest",
    "ListNodeGroupsResponse",
    "LocalDisksSpec",
    "LocalDisksSpecConfig",
    "NVLinkSpec",
    "NetworkInterfaceTemplate",
    "NodeAutoRepairCondition",
    "NodeGroup",
    "NodeGroupAutoRepairSpec",
    "NodeGroupAutoscalingSpec",
    "NodeGroupCompatibilityMatrix",
    "NodeGroupCompatibilityVersion",
    "NodeGroupCompatibilityVersionItem",
    "NodeGroupDeploymentStrategy",
    "NodeGroupServiceClient",
    "NodeGroupSpec",
    "NodeGroupStatus",
    "NodeMetadataTemplate",
    "NodeTaint",
    "NodeTemplate",
    "PassthroughGroupRequest",
    "PercentOrCount",
    "PreemptibleSpec",
    "Problem",
    "ProgressData",
    "PublicEndpointSpec",
    "PublicIPAddress",
    "ReservationPolicy",
    "ResourcesSpec",
    "SecurityGroup",
    "UpdateClusterRequest",
    "UpdateNodeGroupRequest",
    "UpgradeNodeGroupRequest",
]
