# Code generated by protoc-gen-pysdk. DO NOT EDIT.
from __future__ import annotations

import builtins as _builtins
from collections.abc import (
    AsyncIterable as _AsyncIterable,
    Iterable as _Iterable,
    Mapping as _Mapping,
    MutableMapping as _MutableMapping,
    MutableSequence as _MutableSequence,
)
from datetime import datetime as _datetime, timedelta as _timedelta
from typing import Any as _Any, Literal as _Literal, TypeAlias as _TypeAlias
from typing_extensions import Unpack as _Unpack
from .....aio.client import Client as _Client, ClientWithOperations as _ClientWithOperations
from .....aio.operation import Operation as _AsyncOperation
from .....aio.request import Request as _Request
from .....aio.request_kwargs import RequestKwargs as _RequestKwargs, StreamRequestKwargs as _StreamRequestKwargs
from .....aio.request_status import RequestStatus as _RequestStatus
from .....aio.stream import StreamRequest as _StreamRequest
from .....base.protos.direct import Message as _Message, OneOf as _OneOf, SerializableMessage as _SerializableMessage
from .....base.protos.extensions import Extension as _Extension
from .....base.protos.extensions import ExtensionRegistry as _ExtensionRegistry
from .....base.protos.pb_enum import Enum as _Enum
from .....base.protos.registry import Registry as _Registry
from .....base.protos.unset import UnsetType as _UnsetType
from ....google.protobuf import Any as _type_google_protobuf_Any

REGISTRY: _Registry
EXTENSIONS: _ExtensionRegistry
EXTENSION_HANDLES: dict[str, _Extension[_Any]]

class ServiceError__RetryType(_Enum):
    UNSPECIFIED = ...
    CALL = ...
    """Just retry the failed call."""
    UNIT_OF_WORK = ...
    """Retry whole logic before call and make a new one."""
    NOTHING = ...
    """Do not retry, this is a fatal error."""

class ServiceError(_Message):
    RetryType: _TypeAlias = ServiceError__RetryType
    class __OneOfClass_details__(_OneOf):
        """Additional message describing the error, if any."""

        name: _Literal["details"] = ...

    class __OneOfClass_details_bad_request__(__OneOfClass_details__):
        field: _Literal["bad_request"] = ...
        @property
        def value(self) -> BadRequest: ...

    class __OneOfClass_details_bad_resource_state__(__OneOfClass_details__):
        field: _Literal["bad_resource_state"] = ...
        @property
        def value(self) -> BadResourceState: ...

    class __OneOfClass_details_resource_not_found__(__OneOfClass_details__):
        field: _Literal["resource_not_found"] = ...
        @property
        def value(self) -> ResourceNotFound: ...

    class __OneOfClass_details_resource_already_exists__(__OneOfClass_details__):
        field: _Literal["resource_already_exists"] = ...
        @property
        def value(self) -> ResourceAlreadyExists: ...

    class __OneOfClass_details_out_of_range__(__OneOfClass_details__):
        field: _Literal["out_of_range"] = ...
        @property
        def value(self) -> OutOfRange: ...

    class __OneOfClass_details_permission_denied__(__OneOfClass_details__):
        field: _Literal["permission_denied"] = ...
        @property
        def value(self) -> PermissionDenied: ...

    class __OneOfClass_details_resource_conflict__(__OneOfClass_details__):
        field: _Literal["resource_conflict"] = ...
        @property
        def value(self) -> ResourceConflict: ...

    class __OneOfClass_details_operation_aborted__(__OneOfClass_details__):
        field: _Literal["operation_aborted"] = ...
        @property
        def value(self) -> OperationAborted: ...

    class __OneOfClass_details_operation_conflict__(__OneOfClass_details__):
        field: _Literal["operation_conflict"] = ...
        @property
        def value(self) -> OperationConflict: ...

    class __OneOfClass_details_too_many_requests__(__OneOfClass_details__):
        field: _Literal["too_many_requests"] = ...
        @property
        def value(self) -> TooManyRequests: ...

    class __OneOfClass_details_quota_failure__(__OneOfClass_details__):
        field: _Literal["quota_failure"] = ...
        @property
        def value(self) -> QuotaFailure: ...

    class __OneOfClass_details_not_enough_resources__(__OneOfClass_details__):
        field: _Literal["not_enough_resources"] = ...
        @property
        def value(self) -> NotEnoughResources: ...

    class __OneOfClass_details_internal_error__(__OneOfClass_details__):
        field: _Literal["internal_error"] = ...
        @property
        def value(self) -> InternalError: ...

    @property
    def details(
        self,
    ) -> (
        __OneOfClass_details_bad_request__
        | __OneOfClass_details_bad_resource_state__
        | __OneOfClass_details_resource_not_found__
        | __OneOfClass_details_resource_already_exists__
        | __OneOfClass_details_out_of_range__
        | __OneOfClass_details_permission_denied__
        | __OneOfClass_details_resource_conflict__
        | __OneOfClass_details_operation_aborted__
        | __OneOfClass_details_operation_conflict__
        | __OneOfClass_details_too_many_requests__
        | __OneOfClass_details_quota_failure__
        | __OneOfClass_details_not_enough_resources__
        | __OneOfClass_details_internal_error__
        | None
    ):
        """Additional message describing the error, if any."""
        ...
    @property
    def service(self) -> _builtins.str:
        """ID of Service which the error originated in. E.g. \"dns\"."""
        ...
    @service.setter
    def service(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``service`` field."""
        ...
    @property
    def code(self) -> _builtins.str:
        """Detailed error code, service-specific. E.g. \"DnsZoneNotEmpty\".\nName of the exception, without Exception suffix if not set.\nExample: for PermissionDeniedException -> code == PermissionDenied."""
        ...
    @code.setter
    def code(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``code`` field."""
        ...
    @property
    def bad_request(self) -> BadRequest | None: ...
    @bad_request.setter
    def bad_request(self, value: BadRequest | None) -> None:
        """Set or clear the generated ``bad_request`` field."""
        ...
    @property
    def bad_resource_state(self) -> BadResourceState | None: ...
    @bad_resource_state.setter
    def bad_resource_state(self, value: BadResourceState | None) -> None:
        """Set or clear the generated ``bad_resource_state`` field."""
        ...
    @property
    def resource_not_found(self) -> ResourceNotFound | None: ...
    @resource_not_found.setter
    def resource_not_found(self, value: ResourceNotFound | None) -> None:
        """Set or clear the generated ``resource_not_found`` field."""
        ...
    @property
    def resource_already_exists(self) -> ResourceAlreadyExists | None: ...
    @resource_already_exists.setter
    def resource_already_exists(self, value: ResourceAlreadyExists | None) -> None:
        """Set or clear the generated ``resource_already_exists`` field."""
        ...
    @property
    def out_of_range(self) -> OutOfRange | None: ...
    @out_of_range.setter
    def out_of_range(self, value: OutOfRange | None) -> None:
        """Set or clear the generated ``out_of_range`` field."""
        ...
    @property
    def permission_denied(self) -> PermissionDenied | None: ...
    @permission_denied.setter
    def permission_denied(self, value: PermissionDenied | None) -> None:
        """Set or clear the generated ``permission_denied`` field."""
        ...
    @property
    def resource_conflict(self) -> ResourceConflict | None: ...
    @resource_conflict.setter
    def resource_conflict(self, value: ResourceConflict | None) -> None:
        """Set or clear the generated ``resource_conflict`` field."""
        ...
    @property
    def operation_aborted(self) -> OperationAborted | None: ...
    @operation_aborted.setter
    def operation_aborted(self, value: OperationAborted | None) -> None:
        """Set or clear the generated ``operation_aborted`` field."""
        ...
    @property
    def operation_conflict(self) -> OperationConflict | None: ...
    @operation_conflict.setter
    def operation_conflict(self, value: OperationConflict | None) -> None:
        """Set or clear the generated ``operation_conflict`` field."""
        ...
    @property
    def too_many_requests(self) -> TooManyRequests | None: ...
    @too_many_requests.setter
    def too_many_requests(self, value: TooManyRequests | None) -> None:
        """Set or clear the generated ``too_many_requests`` field."""
        ...
    @property
    def quota_failure(self) -> QuotaFailure | None: ...
    @quota_failure.setter
    def quota_failure(self, value: QuotaFailure | None) -> None:
        """Set or clear the generated ``quota_failure`` field."""
        ...
    @property
    def not_enough_resources(self) -> NotEnoughResources | None: ...
    @not_enough_resources.setter
    def not_enough_resources(self, value: NotEnoughResources | None) -> None:
        """Set or clear the generated ``not_enough_resources`` field."""
        ...
    @property
    def internal_error(self) -> InternalError | None: ...
    @internal_error.setter
    def internal_error(self, value: InternalError | None) -> None:
        """Set or clear the generated ``internal_error`` field."""
        ...
    @property
    def retry_type(self) -> ServiceError__RetryType:
        """Retry type tells how to provide retry, e.g.: just a single call or the whole logic before it."""
        ...
    @retry_type.setter
    def retry_type(self, value: ServiceError__RetryType | None) -> None:
        """Set or clear the generated ``retry_type`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        service: _builtins.str | None | _UnsetType = ...,
        code: _builtins.str | None | _UnsetType = ...,
        bad_request: BadRequest | None | _UnsetType = ...,
        bad_resource_state: BadResourceState | None | _UnsetType = ...,
        resource_not_found: ResourceNotFound | None | _UnsetType = ...,
        resource_already_exists: ResourceAlreadyExists | None | _UnsetType = ...,
        out_of_range: OutOfRange | None | _UnsetType = ...,
        permission_denied: PermissionDenied | None | _UnsetType = ...,
        resource_conflict: ResourceConflict | None | _UnsetType = ...,
        operation_aborted: OperationAborted | None | _UnsetType = ...,
        operation_conflict: OperationConflict | None | _UnsetType = ...,
        too_many_requests: TooManyRequests | None | _UnsetType = ...,
        quota_failure: QuotaFailure | None | _UnsetType = ...,
        not_enough_resources: NotEnoughResources | None | _UnsetType = ...,
        internal_error: InternalError | None | _UnsetType = ...,
        retry_type: ServiceError__RetryType | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BadRequest__Violation(_Message):
    @property
    def field(self) -> _builtins.str:
        """What field value is invalid."""
        ...
    @field.setter
    def field(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``field`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """Description why the value is invalid, in English."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    @property
    def related_fields(self) -> _MutableSequence[_builtins.str]:
        """Other fields whose values contribute to this violation.\nDoes not include the primary field."""
        ...
    @related_fields.setter
    def related_fields(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``related_fields`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        field: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
        related_fields: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BadRequest(_Message):
    """The request is invalid."""

    Violation: _TypeAlias = BadRequest__Violation
    @property
    def violations(self) -> _MutableSequence[BadRequest__Violation]:
        """Describes all violations."""
        ...
    @violations.setter
    def violations(self, value: _Iterable[BadRequest__Violation] | None) -> None:
        """Set or clear the generated ``violations`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        violations: _Iterable[BadRequest__Violation] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BadResourceState(_Message):
    """The resource we are trying to use, create, change or delete is in a bad state and cannot be used."""
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the resource which is bad."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """The reason why this state is bad and cannot be used."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourceNotFound(_Message):
    """Resource we are trying to interact with does not exist."""
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the requested resource."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourceAlreadyExists(_Message):
    """Resource we are trying to create already exists."""
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the existing resource."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourceConflict(_Message):
    """There is a difference between the actual resource state and the expected one."""
    @property
    def resource_id(self) -> _builtins.str:
        """ID of conflicting resource."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """Detailed info about conflict."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class OperationAborted(_Message):
    """Operation on the resource has been aborted by a subsequent operation."""
    @property
    def operation_id(self) -> _builtins.str:
        """ID of the aborted operation."""
        ...
    @operation_id.setter
    def operation_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``operation_id`` field."""
        ...
    @property
    def aborted_by_operation_id(self) -> _builtins.str:
        """ID of the subsequent operation."""
        ...
    @aborted_by_operation_id.setter
    def aborted_by_operation_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``aborted_by_operation_id`` field."""
        ...
    @property
    def resource_id(self) -> _builtins.str:
        """Resource ID corresponding to both of the operations."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        operation_id: _builtins.str | None | _UnsetType = ...,
        aborted_by_operation_id: _builtins.str | None | _UnsetType = ...,
        resource_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class OperationConflict(_Message):
    """Operation cannot be started because a conflicting operation is already running on the same resource.\nWait until the conflicting operation finishes, then you can retry starting your operation."""
    @property
    def conflicting_operation_id(self) -> _builtins.str:
        """ID of the conflicting operation (the one that's running)."""
        ...
    @conflicting_operation_id.setter
    def conflicting_operation_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``conflicting_operation_id`` field."""
        ...
    @property
    def resource_id(self) -> _builtins.str:
        """Resource ID corresponding to the conflicting operation."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        conflicting_operation_id: _builtins.str | None | _UnsetType = ...,
        resource_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class OutOfRange(_Message):
    """Indicates that element with requested parameters is exceeding the particular range."""
    @property
    def requested(self) -> _builtins.str:
        """Requested value."""
        ...
    @requested.setter
    def requested(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``requested`` field."""
        ...
    @property
    def limit(self) -> _builtins.str:
        """Available limit."""
        ...
    @limit.setter
    def limit(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``limit`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        requested: _builtins.str | None | _UnsetType = ...,
        limit: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PermissionDenied(_Message):
    """Indicates that the action cannot be performed because there are insufficient access rights to a resource."""
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the resource that cannot be accessed."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class InternalError(_Message):
    """Generic internal error."""
    @property
    def request_id(self) -> _builtins.str:
        """Error request ID."""
        ...
    @request_id.setter
    def request_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``request_id`` field."""
        ...
    @property
    def trace_id(self) -> _builtins.str:
        """Trace ID for the failing request."""
        ...
    @trace_id.setter
    def trace_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``trace_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        request_id: _builtins.str | None | _UnsetType = ...,
        trace_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class TooManyRequests(_Message):
    """You initiated too many requests to the service at once. Enhance your calm."""
    @property
    def violation(self) -> _builtins.str:
        """What request limit is exceeded (service-dependent)."""
        ...
    @violation.setter
    def violation(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``violation`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, violation: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class QuotaFailure__Violation(_Message):
    @property
    def quota(self) -> _builtins.str:
        """Which quota check failed."""
        ...
    @quota.setter
    def quota(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``quota`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """A description of how the quota check failed."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    @property
    def limit(self) -> _builtins.str:
        """Maximum permissible value."""
        ...
    @limit.setter
    def limit(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``limit`` field."""
        ...
    @property
    def requested(self) -> _builtins.str:
        """Requested value."""
        ...
    @requested.setter
    def requested(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``requested`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        quota: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
        limit: _builtins.str | None | _UnsetType = ...,
        requested: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class QuotaFailure(_Message):
    """Indicates a failure due to exceeding specified limits or allocations in a system or service."""

    Violation: _TypeAlias = QuotaFailure__Violation
    @property
    def violations(self) -> _MutableSequence[QuotaFailure__Violation]:
        """Describes all quota violations."""
        ...
    @violations.setter
    def violations(self, value: _Iterable[QuotaFailure__Violation] | None) -> None:
        """Set or clear the generated ``violations`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        violations: _Iterable[QuotaFailure__Violation] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NotEnoughResources__Violation(_Message):
    @property
    def resource_type(self) -> _builtins.str:
        """The type of resource that is insufficient.\nThis field is populated when it is possible to determine the lacking resource type.\n**Not for programmatic use.**"""
        ...
    @resource_type.setter
    def resource_type(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_type`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """A description of how the resource is insufficient."""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    @property
    def requested(self) -> _builtins.str:
        """Requested value."""
        ...
    @requested.setter
    def requested(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``requested`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_type: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
        requested: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class NotEnoughResources(_Message):
    """Indicates that there are not enough resources available to perform the requested action."""

    Violation: _TypeAlias = NotEnoughResources__Violation
    @property
    def violations(self) -> _MutableSequence[NotEnoughResources__Violation]:
        """Describes all resource violations."""
        ...
    @violations.setter
    def violations(self, value: _Iterable[NotEnoughResources__Violation] | None) -> None:
        """Set or clear the generated ``violations`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        violations: _Iterable[NotEnoughResources__Violation] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourceMetadata(_Message):
    """Common resource metadata."""
    @property
    def id(self) -> _builtins.str:
        """Identifier for the resource, unique for its resource type."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def parent_id(self) -> _builtins.str:
        """Identifier of the parent resource to which the resource belongs."""
        ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    @property
    def name(self) -> _builtins.str:
        """Human readable name for the resource."""
        ...
    @name.setter
    def name(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``name`` field."""
        ...
    @property
    def resource_version(self) -> _builtins.int:
        """Version of the resource for safe concurrent modifications and consistent reads.\nPositive and monotonically increases on each resource spec change (but *not* on each change of the\nresource's container(s) or status).\nService allows zero value or current."""
        ...
    @resource_version.setter
    def resource_version(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``resource_version`` field."""
        ...
    @property
    def created_at(self) -> _datetime | None:
        """Timestamp indicating when the resource was created."""
        ...
    @created_at.setter
    def created_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``created_at`` field."""
        ...
    @property
    def updated_at(self) -> _datetime | None:
        """Timestamp indicating when the resource was last updated."""
        ...
    @updated_at.setter
    def updated_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``updated_at`` field."""
        ...
    @property
    def labels(self) -> _MutableMapping[_builtins.str, _builtins.str]:
        """Labels associated with the resource."""
        ...
    @labels.setter
    def labels(self, value: _Mapping[_builtins.str, _builtins.str] | None) -> None:
        """Set or clear the generated ``labels`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        parent_id: _builtins.str | None | _UnsetType = ...,
        name: _builtins.str | None | _UnsetType = ...,
        resource_version: _builtins.int | None | _UnsetType = ...,
        created_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        updated_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        labels: _Mapping[_builtins.str, _builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetByNameRequest(_Message):
    """This message is used as the request for the ``GetByName`` method in services supporting uniqueness\nof ``ResourceMetadata.name`` within tuple (scope) <resource\\_type, ``parent_id``>."""
    @property
    def parent_id(self) -> _builtins.str: ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    @property
    def name(self) -> _builtins.str: ...
    @name.setter
    def name(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``name`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        parent_id: _builtins.str | None | _UnsetType = ...,
        name: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Operation__RequestHeader(_Message):
    """Request header is a container for all the values of a particular header of a request because there is no such thing as\n\\ ``map<string, repeated string>``"""
    @property
    def values(self) -> _MutableSequence[_builtins.str]:
        """The values of a particular header from a request"""
        ...
    @values.setter
    def values(self, value: _Iterable[_builtins.str] | None) -> None:
        """Set or clear the generated ``values`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        values: _Iterable[_builtins.str] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Operation(_Message):
    RequestHeader: _TypeAlias = Operation__RequestHeader
    @property
    def id(self) -> _builtins.str:
        """ID of the operation."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def description(self) -> _builtins.str:
        """Human-readable description of the operation. 0-256 characters long."""
        ...
    @description.setter
    def description(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``description`` field."""
        ...
    @property
    def created_at(self) -> _datetime | None:
        """Creation timestamp."""
        ...
    @created_at.setter
    def created_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``created_at`` field."""
        ...
    @property
    def created_by(self) -> _builtins.str:
        """ID of the user or service account who initiated the operation."""
        ...
    @created_by.setter
    def created_by(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``created_by`` field."""
        ...
    @property
    def finished_at(self) -> _datetime | None:
        """The time when the operation has finished."""
        ...
    @finished_at.setter
    def finished_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``finished_at`` field."""
        ...
    @property
    def request(self) -> _type_google_protobuf_Any:
        """The request that generated this operation."""
        ...
    @request.setter
    def request(self, value: _type_google_protobuf_Any | None) -> None:
        """Set or clear the generated ``request`` field."""
        ...
    @property
    def request_headers(self) -> _MutableMapping[_builtins.str, Operation__RequestHeader]:
        """The request headers that are essential for the request that generated the operation.\nFor instance, ``x-resetmask``. Without these headers the request might have been processed\ndifferently if repeated.\nAll the header names *must* be converted to lower case.\nValidator is based on:\nhttps://httpwg.org/specs/rfc9110.html#considerations.for.new.field.names"""
        ...
    @request_headers.setter
    def request_headers(self, value: _Mapping[_builtins.str, Operation__RequestHeader] | None) -> None:
        """Set or clear the generated ``request_headers`` field."""
        ...
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the resource that this operation creates, updates, deletes or otherwise changes.\n\nIf the operation affects multiple resources or does not affect any API resources at all\n(e.g. a routine maintenance operation visible to the user), the [resource\\_id] must be empty."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    @property
    def status(self) -> _RequestStatus | None:
        """The status of this operation. Set when this operation is completed.\nSee https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto.\n\n[status.code] is https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto:\n\n* If [status.code] == OK, the operation has completed successfully.\n* If [status.code] != OK, the operation has failed or has been cancelled.\n\n  * [status.message] will contain a user-readable and actionable error message.\n  * [status.details] will contain additional diagnostic information in the form of [ServiceError] from nebius/common/v1/error.proto\n* [status.code] must belong to an Operation-compatible subset of GRPC codes:\n  OK, CANCELLED, PERMISSION\\_DENIED, RESOURCE\\_EXHAUSTED, FAILED\\_PRECONDITION, ABORTED, INTERNAL"""
        ...
    @status.setter
    def status(self, value: _RequestStatus | _SerializableMessage | None) -> None:
        """Set or clear the generated ``status`` field."""
        ...
    @property
    def progress_tracker(self) -> ProgressTracker:
        """Information about this operation's progress, if this operation tracks its progress.\nIf the operation tracks its progress, ``progress_tracker`` MUST be present both while\nthe operation is running and after it has been completed."""
        ...
    @progress_tracker.setter
    def progress_tracker(self, value: ProgressTracker | None) -> None:
        """Set or clear the generated ``progress_tracker`` field."""
        ...
    @property
    def progress_data(self) -> _type_google_protobuf_Any:
        """Extra information about this operation's progress. MAY be absent while the operation is running, MUST be absent after the operation has\ncompleted.\n\nType of message that's stored inside [progress\\_data] is service-dependent."""
        ...
    @progress_data.setter
    def progress_data(self, value: _type_google_protobuf_Any | None) -> None:
        """Set or clear the generated ``progress_data`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        description: _builtins.str | None | _UnsetType = ...,
        created_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        created_by: _builtins.str | None | _UnsetType = ...,
        finished_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        request: _type_google_protobuf_Any | None | _UnsetType = ...,
        request_headers: _Mapping[_builtins.str, Operation__RequestHeader] | None | _UnsetType = ...,
        resource_id: _builtins.str | None | _UnsetType = ...,
        status: _RequestStatus | _SerializableMessage | None | _UnsetType = ...,
        progress_tracker: ProgressTracker | None | _UnsetType = ...,
        progress_data: _type_google_protobuf_Any | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetOperationRequest(_Message):
    @property
    def id(self) -> _builtins.str: ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListOperationsRequest(_Message):
    @property
    def resource_id(self) -> _builtins.str:
        """ID of the Resource to list operations for."""
        ...
    @resource_id.setter
    def resource_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``resource_id`` field."""
        ...
    @property
    def page_size(self) -> _builtins.int:
        """Page size. [1...1000]. Optional, if not specified, a reasonable default will be chosen by the service."""
        ...
    @page_size.setter
    def page_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``page_size`` field."""
        ...
    @property
    def page_token(self) -> _builtins.str:
        """Listing continuation token. Empty to start listing from the first page."""
        ...
    @page_token.setter
    def page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resource_id: _builtins.str | None | _UnsetType = ...,
        page_size: _builtins.int | None | _UnsetType = ...,
        page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListOperationsResponse(_Message):
    @property
    def operations(self) -> _MutableSequence[Operation]: ...
    @operations.setter
    def operations(self, value: _Iterable[Operation] | None) -> None:
        """Set or clear the generated ``operations`` field."""
        ...
    @property
    def next_page_token(self) -> _builtins.str: ...
    @next_page_token.setter
    def next_page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``next_page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        operations: _Iterable[Operation] | None | _UnsetType = ...,
        next_page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PreflightCheckContext__Action(_Enum):
    """Operation evaluated by the preflight check."""

    UNSPECIFIED = ...
    """Infer UPDATE when the request metadata contains a resource ID; otherwise infer CREATE."""
    CREATE = ...
    """Evaluate resource creation."""
    UPDATE = ...
    """Evaluate a resource update."""
    DELETE = ...
    """Evaluate resource deletion. Reserved until delete preflight requests are supported."""
    RECREATE = ...
    """Evaluate resource recreation. This is the same as CREATE, but assumes that the resource\nwith the requested ID is deleted immediately before it is created."""

class PreflightCheckContext(_Message):
    """Context supplied by a caller when requesting a server-side preflight check."""

    Action: _TypeAlias = PreflightCheckContext__Action
    @property
    def action(self) -> PreflightCheckContext__Action:
        """Operation evaluated by the preflight check."""
        ...
    @action.setter
    def action(self, value: PreflightCheckContext__Action | None) -> None:
        """Set or clear the generated ``action`` field."""
        ...
    @property
    def tool(self) -> _builtins.str:
        """Lower-case name of the calling tool, such as \"terraform\", \"cli\", or \"console\".\nEmpty means that no tool-specific behavior is requested."""
        ...
    @tool.setter
    def tool(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``tool`` field."""
        ...
    @property
    def unknown_paths(self) -> _builtins.str:
        """Nebius mask identifying values in the proposed request that are unknown.\nAn unknown value is not available to the caller when it sends the preflight request.\nThe caller expects the actual value to be available when the create or update operation runs.\nThe mask is rooted at the request's metadata and spec fields. Empty means all supplied values are known;\n\"\\*\" means the complete proposed request is unknown."""
        ...
    @unknown_paths.setter
    def unknown_paths(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``unknown_paths`` field."""
        ...
    @property
    def paths_require_recreate(self) -> _builtins.str:
        """Additive Nebius mask of fields that require resource recreation when changed.\nFor RECREATE, the calling tool fills this mask with the paths that caused it to recreate the resource.\nIf a field at one of these paths changes, the calling tool must delete the existing resource\nand create a new resource with the requested values.\nEmpty means that the caller has not identified any such fields."""
        ...
    @paths_require_recreate.setter
    def paths_require_recreate(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``paths_require_recreate`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        action: PreflightCheckContext__Action | None | _UnsetType = ...,
        tool: _builtins.str | None | _UnsetType = ...,
        unknown_paths: _builtins.str | None | _UnsetType = ...,
        paths_require_recreate: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PreflightCheckDiagnostic__Severity(_Enum):
    """Effect of the diagnostic on the proposed operation."""

    UNSPECIFIED = ...
    """Invalid for a returned diagnostic."""
    ERROR = ...
    """The proposed operation cannot proceed."""
    WARNING = ...
    """The proposed operation can proceed, subject to requires\\_user\\_approval."""

class PreflightCheckDiagnostic(_Message):
    """A user-facing diagnostic produced by a preflight check."""

    Severity: _TypeAlias = PreflightCheckDiagnostic__Severity
    @property
    def severity(self) -> PreflightCheckDiagnostic__Severity:
        """Effect of the diagnostic on the proposed operation. Must not be UNSPECIFIED."""
        ...
    @severity.setter
    def severity(self, value: PreflightCheckDiagnostic__Severity | None) -> None:
        """Set or clear the generated ``severity`` field."""
        ...
    @property
    def summary(self) -> _builtins.str:
        """Required single-line, plain-text user-facing explanation."""
        ...
    @summary.setter
    def summary(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``summary`` field."""
        ...
    @property
    def details(self) -> _builtins.str:
        """Optional plain-text consequence and remediation details."""
        ...
    @details.setter
    def details(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``details`` field."""
        ...
    @property
    def path(self) -> _builtins.str:
        """Optional Nebius field path rooted at metadata or spec.\nEmpty means that the diagnostic applies to the resource or operation as a whole."""
        ...
    @path.setter
    def path(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``path`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        severity: PreflightCheckDiagnostic__Severity | None | _UnsetType = ...,
        summary: _builtins.str | None | _UnsetType = ...,
        details: _builtins.str | None | _UnsetType = ...,
        path: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class PreflightCheckResult(_Message):
    """Common preflight result for services that do not expose additional machine-readable impact fields.\nService-defined result messages implement the same structural interface by declaring these three fields\nwith the same names and types, and may add service-specific fields."""
    @property
    def diagnostics(self) -> _MutableSequence[PreflightCheckDiagnostic]:
        """Diagnostics produced while evaluating the proposed operation."""
        ...
    @diagnostics.setter
    def diagnostics(self, value: _Iterable[PreflightCheckDiagnostic] | None) -> None:
        """Set or clear the generated ``diagnostics`` field."""
        ...
    @property
    def paths_require_recreate(self) -> _builtins.str:
        """Additive Nebius mask of fields that the service identifies as requiring resource recreation when changed.\nFor UPDATE, the service may set these paths to notify the caller to use RECREATE instead of failing because\nthe resource cannot be updated. Empty means that the service has not identified any such fields; \"\\*\" means\nthat the resource must be recreated without an attributable field."""
        ...
    @paths_require_recreate.setter
    def paths_require_recreate(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``paths_require_recreate`` field."""
        ...
    @property
    def requires_user_approval(self) -> _builtins.bool:
        """Whether the caller must display the diagnostics and obtain explicit user approval before proceeding."""
        ...
    @requires_user_approval.setter
    def requires_user_approval(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``requires_user_approval`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        diagnostics: _Iterable[PreflightCheckDiagnostic] | None | _UnsetType = ...,
        paths_require_recreate: _builtins.str | None | _UnsetType = ...,
        requires_user_approval: _builtins.bool | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ProgressTracker__WorkDone(_Message):
    """Information about the work done by the task or its step, expressed in ticks (abstract work units).\nEach tick may represent a real measurement (e.g., VMs created, KiB uploaded), number of substeps or a percentage of work completed."""
    @property
    def total_tick_count(self) -> _builtins.int:
        """Total number of ticks (work units) to be completed. MUST be greater than 0."""
        ...
    @total_tick_count.setter
    def total_tick_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``total_tick_count`` field."""
        ...
    @property
    def done_tick_count(self) -> _builtins.int:
        """Number of ticks completed so far. MUST be between 0 and total\\_tick\\_count, inclusive.\nMUST equal total\\_tick\\_count if the task or step is finished."""
        ...
    @done_tick_count.setter
    def done_tick_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``done_tick_count`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        total_tick_count: _builtins.int | None | _UnsetType = ...,
        done_tick_count: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ProgressTracker__Step(_Message):
    """Represents a basic step in the task.\nFields are binary-compatible with ProgressTracker for easier processing."""
    @property
    def description(self) -> _builtins.str:
        """Human-readable description of the step, e.g., \"Connecting to localhost:8080\".\nMUST be suitable for display to public users.\nPrivate descriptions must be filtered server-side based on the use case."""
        ...
    @description.setter
    def description(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``description`` field."""
        ...
    @property
    def started_at(self) -> _datetime | None:
        """Timestamp when the step started."""
        ...
    @started_at.setter
    def started_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``started_at`` field."""
        ...
    @property
    def finished_at(self) -> _datetime | None:
        """Timestamp when the step finished.\nMUST be absent for running steps; MUST be present for completed steps."""
        ...
    @finished_at.setter
    def finished_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``finished_at`` field."""
        ...
    @property
    def work_done(self) -> ProgressTracker__WorkDone:
        """Details on the work to be done for this step and progress made.\nMAY be absent if unknown."""
        ...
    @work_done.setter
    def work_done(self, value: ProgressTracker__WorkDone | None) -> None:
        """Set or clear the generated ``work_done`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        description: _builtins.str | None | _UnsetType = ...,
        started_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        finished_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        work_done: ProgressTracker__WorkDone | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ProgressTracker(_Message):
    """Information for tracking the progress of a task (e.g., an API operation or background maintenance action).\nThis serves as a UI contract and may be directly reflected in CLI, Console, and other tools."""

    WorkDone: _TypeAlias = ProgressTracker__WorkDone
    Step: _TypeAlias = ProgressTracker__Step
    @property
    def description(self) -> _builtins.str:
        """Human-readable description of the currently executing task, e.g., \"Downloading dat-groot-llm.tar.xz\".\nRelates to the overall task, not individual steps.\nSHOULD match the Operation's ``description`` field when this ProgressTracker tracks an API Operation's progress.\nMAY provide more detailed overall information.\n\nMUST be suitable for display to public users.\nEven if the task is internal, this description may be shown to end users in overall task step descriptions.\n\nFor individual step descriptions, use ``Step.description``."""
        ...
    @description.setter
    def description(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``description`` field."""
        ...
    @property
    def started_at(self) -> _datetime | None:
        """Timestamp when the overall task started.\nMUST match the operation's created\\_at timestamp when tracking an API Operation's progress."""
        ...
    @started_at.setter
    def started_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``started_at`` field."""
        ...
    @property
    def estimated_finished_at(self) -> _datetime | None:
        """Estimated completion timestamp for the task.\nMUST be absent if the task is completed (i.e., finished\\_at is set).\nMAY be absent if the estimate is unknown.\nMAY be updated as the progress estimate changes."""
        ...
    @estimated_finished_at.setter
    def estimated_finished_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``estimated_finished_at`` field."""
        ...
    @property
    def finished_at(self) -> _datetime | None:
        """Completion timestamp of the task.\nMUST be absent for running tasks; MUST be present for completed tasks.\nMUST match the operation's finished\\_at timestamp when tracking an API Operation's progress."""
        ...
    @finished_at.setter
    def finished_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``finished_at`` field."""
        ...
    @property
    def work_done(self) -> ProgressTracker__WorkDone:
        """Overall work progress details.\nMAY be absent if unknown."""
        ...
    @work_done.setter
    def work_done(self, value: ProgressTracker__WorkDone | None) -> None:
        """Set or clear the generated ``work_done`` field."""
        ...
    @property
    def steps(self) -> _MutableSequence[ProgressTracker__Step]:
        """Detailed information about the task steps that are currently running or have been finished.\n\n* For a completed task, the step list MUST either be empty or contain finished steps only.\n* For a running task, the step list MAY be empty if the task consists of a single step or no detailed information is available.\n  A non-empty step list MUST include all currently running steps and MAY include some or all finished steps.\n* Service SHOULD provide both running and finished steps if the task has around 10-20 steps, and provide only running steps otherwise.\n  Service MUST consistently choose either the \"running steps only\" or the \"running + finished steps\" behavior.\n* The UI, CLI etc. MAY choose not to display all steps provided by the service."""
        ...
    @steps.setter
    def steps(self, value: _Iterable[ProgressTracker__Step] | None) -> None:
        """Set or clear the generated ``steps`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        description: _builtins.str | None | _UnsetType = ...,
        started_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        estimated_finished_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        finished_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        work_done: ProgressTracker__WorkDone | None | _UnsetType = ...,
        steps: _Iterable[ProgressTracker__Step] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ResourceEvent__Level(_Enum):
    UNSPECIFIED = ...
    """Unspecified event severity level"""
    DEBUG = ...
    """A debug event providing detailed insight. Such events are used to debug problems with specific resource(s) and process(es)"""
    INFO = ...
    """A normal event or state change. Informs what is happening with the API resource. Does not require user attention or interaction"""
    WARN = ...
    """Warning event. Indicates a potential or minor problem with the API resource and/or the corresponding processes. Needs user attention,\nbut requires no immediate action (yet)"""
    ERROR = ...
    """Error event. Indicates a serious problem with the API resource and/or the corresponding processes. Requires immediate user action"""

class ResourceEvent(_Message):
    """Represents an API Resource-related event which is potentially important to the end-user. What exactly constitutes an *event* to be\nreported is service-dependent"""

    Level: _TypeAlias = ResourceEvent__Level
    @property
    def occurred_at(self) -> _datetime | None:
        """Time at which the event has occurred"""
        ...
    @occurred_at.setter
    def occurred_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``occurred_at`` field."""
        ...
    @property
    def level(self) -> ResourceEvent__Level:
        """Severity level for the event"""
        ...
    @level.setter
    def level(self, value: ResourceEvent__Level | None) -> None:
        """Set or clear the generated ``level`` field."""
        ...
    @property
    def code(self) -> _builtins.str:
        """Event code (unique within the API service), in UpperCamelCase, e.g. ``\"DiskAttached\"``"""
        ...
    @code.setter
    def code(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``code`` field."""
        ...
    @property
    def message(self) -> _builtins.str:
        """A human-readable message describing what has happened\n(and suggested actions for the user, if this is a ``WARN`` or ``ERROR`` level event)"""
        ...
    @message.setter
    def message(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``message`` field."""
        ...
    @property
    def error(self) -> _RequestStatus | None:
        """Describes a GRPC error status associated with an ``ERROR`` or ``WARN`` level event, if known. The ``error`` **must** have a standard GRPC\n\\ ``code`` (which **must not** be ``OK`` (0)) and a human-readable ``message``. A standard ``common.v1.ServiceError`` **should** also be\nincluded in ``details``"""
        ...
    @error.setter
    def error(self, value: _RequestStatus | _SerializableMessage | None) -> None:
        """Set or clear the generated ``error`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        occurred_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        level: ResourceEvent__Level | None | _UnsetType = ...,
        code: _builtins.str | None | _UnsetType = ...,
        message: _builtins.str | None | _UnsetType = ...,
        error: _RequestStatus | _SerializableMessage | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class RecurrentResourceEvent(_Message):
    """A resource event that has occurred (more or less in the same way) multiple times across a service-defined aggregation interval"""
    @property
    def first_occurred_at(self) -> _datetime | None:
        """Time of the first occurrence of a recurrent event"""
        ...
    @first_occurred_at.setter
    def first_occurred_at(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``first_occurred_at`` field."""
        ...
    @property
    def last_occurrence(self) -> ResourceEvent:
        """Last occurrence of a recurrent event"""
        ...
    @last_occurrence.setter
    def last_occurrence(self, value: ResourceEvent | None) -> None:
        """Set or clear the generated ``last_occurrence`` field."""
        ...
    @property
    def occurrence_count(self) -> _builtins.int:
        """The number of times this event has occurred between ``first_occurred_at`` and ``last_occurrence.occurred_at``. Must be > 0"""
        ...
    @occurrence_count.setter
    def occurrence_count(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``occurrence_count`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        first_occurred_at: _datetime | _SerializableMessage | None | _UnsetType = ...,
        last_occurrence: ResourceEvent | None | _UnsetType = ...,
        occurrence_count: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Warnings(_Message):
    @property
    def warnings(self) -> _MutableSequence[Warning]:
        """List of warnings associated with the response."""
        ...
    @warnings.setter
    def warnings(self, value: _Iterable[Warning] | None) -> None:
        """Set or clear the generated ``warnings`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        warnings: _Iterable[Warning] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Warning__Target(_Enum):
    TARGET_UNSPECIFIED = ...
    """Target is not specified."""
    TARGET_CLI = ...
    """Warning is intended for CLI users."""
    TARGET_TF = ...
    """Warning is intended for Terraform provider users."""
    TARGET_CONSOLE = ...
    """Warning is intended for console users."""

class Warning__Code(_Enum):
    CODE_UNSPECIFIED = ...
    """Code is not specified."""
    CODE_REGION_ROUTING_FAILOVER = ...
    """The request was served via failover routing."""
    CODE_DEPRECATED_TOOL_VERSION = ...
    """Client tool version is deprecated."""
    CODE_DEPRECATED_ENDPOINT = ...
    """Endpoint is deprecated."""
    CODE_DEPRECATED_PROTO = ...
    """Proto field, message or service is deprecated."""
    CODE_DEPRECATED_SPEC_VALUE_REQUEST = ...
    """Deprecated value was used in the request."""
    CODE_DEPRECATED_SPEC_VALUE_RESPONSE = ...
    """Deprecated value was observed in the response."""
    CODE_NOT_RECOMMENDED_SPEC_VALUE_REQUEST = ...
    """Not-recommended value was used in the request."""
    CODE_INVALID_NEBIUS_ID_REQUEST = ...
    """Nebius ID in the request has an invalid resource type."""
    CODE_INVALID_NEBIUS_ID_FORMAT_REQUEST = ...
    """Nebius ID in the request has an invalid format."""
    CODE_LIST_AGGREGATED_PARTIAL = ...
    """ListAggregated returned incomplete results because one or more regions could not be queried."""

class Warning(_Message):
    Target: _TypeAlias = Warning__Target
    Code: _TypeAlias = Warning__Code
    @property
    def target(self) -> Warning__Target:
        """Target client or tool for which this warning is intended."""
        ...
    @target.setter
    def target(self, value: Warning__Target | None) -> None:
        """Set or clear the generated ``target`` field."""
        ...
    @property
    def code(self) -> Warning__Code:
        """Warning category."""
        ...
    @code.setter
    def code(self, value: Warning__Code | None) -> None:
        """Set or clear the generated ``code`` field."""
        ...
    @property
    def summary(self) -> _builtins.str:
        """User-facing summary text. Can contain a liquid format template which must be executed on client side.\nEmpty means use summary\\_fallback."""
        ...
    @summary.setter
    def summary(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``summary`` field."""
        ...
    @property
    def summary_fallback(self) -> _builtins.str:
        """Summary text to use when summary is empty or not applicable.\nCan contain a liquid format template which must be executed on client side."""
        ...
    @summary_fallback.setter
    def summary_fallback(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``summary_fallback`` field."""
        ...
    @property
    def details(self) -> _builtins.str:
        """User-facing details text. Can contain a liquid format template which must be executed on client side.\nEmpty means use details\\_fallback."""
        ...
    @details.setter
    def details(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``details`` field."""
        ...
    @property
    def details_fallback(self) -> _builtins.str:
        """Details text to use when details is empty or not applicable.\nCan contain a liquid format template which must be executed on client side."""
        ...
    @details_fallback.setter
    def details_fallback(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``details_fallback`` field."""
        ...
    @property
    def path(self) -> _builtins.str:
        """Contains a Full Service/Method name or a select mask for a field.\nExamples:\n\n.. code-block::\n\n   nebius.compute.v1.InstanceService\n   nebius.compute.v1.InstanceService/Get\n   spec.control_plane.version\n   spec.network_interfaces.0.subnet_id\n   items.0.spec.control_plane.version"""
        ...
    @path.setter
    def path(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``path`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        target: Warning__Target | None | _UnsetType = ...,
        code: Warning__Code | None | _UnsetType = ...,
        summary: _builtins.str | None | _UnsetType = ...,
        summary_fallback: _builtins.str | None | _UnsetType = ...,
        details: _builtins.str | None | _UnsetType = ...,
        details_fallback: _builtins.str | None | _UnsetType = ...,
        path: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class OperationServiceClient(_Client):
    """Service for reading operations.\n\nThis class provides client methods for the ``nebius.common.v1.OperationService`` service."""
    def get(
        self, request: GetOperationRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetOperationRequest, Operation]:
        """Returns the current state of the specified operation.\n\nThe request object is returned without starting the RPC."""
        ...
    def list(
        self, request: ListOperationsRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListOperationsRequest, ListOperationsResponse]:
        """Lists operations for the specified resource.\n\nThe request object is returned without starting the RPC."""
        ...

__all__ = [
    "BadRequest",
    "BadResourceState",
    "GetByNameRequest",
    "GetOperationRequest",
    "InternalError",
    "ListOperationsRequest",
    "ListOperationsResponse",
    "NotEnoughResources",
    "Operation",
    "OperationAborted",
    "OperationConflict",
    "OperationServiceClient",
    "OutOfRange",
    "PermissionDenied",
    "PreflightCheckContext",
    "PreflightCheckDiagnostic",
    "PreflightCheckResult",
    "ProgressTracker",
    "QuotaFailure",
    "RecurrentResourceEvent",
    "ResourceAlreadyExists",
    "ResourceConflict",
    "ResourceEvent",
    "ResourceMetadata",
    "ResourceNotFound",
    "ServiceError",
    "TooManyRequests",
    "Warning",
    "Warnings",
]
