# Generated by nebius_generator. DO NOT EDIT!
"""Direct protobuf classes for this package."""

from __future__ import annotations

from builtins import (
    bool as _NebiusBool, bytes as _NebiusBytes, dict as _NebiusDict,
    float as _NebiusFloat, int as _NebiusInt, object as _NebiusObject,
    property as _NebiusProperty, str as _NebiusStr,
)
from collections.abc import (
    AsyncIterable as _NebiusAsyncIterable, Iterable as _NebiusIterable,
    Mapping as _NebiusMapping, MutableMapping as _NebiusMutableMapping,
    MutableSequence as _NebiusMutableSequence,
)
from datetime import datetime as _NebiusDatetime, timedelta as _NebiusTimedelta
from logging import getLogger as _nebius_get_logger
from typing import (
    TYPE_CHECKING as _NEBIUS_TYPE_CHECKING, ClassVar as _NebiusClassVar,
    Literal as _NebiusLiteral, TypeAlias as _NebiusTypeAlias, cast as _nebius_cast,
)
from typing_extensions import Unpack as _NebiusUnpack

from nebius.aio.client import Client as _NebiusClient, ClientWithOperations as _NebiusClientWithOperations
from nebius.aio.operation import Operation as _NebiusOperation
from nebius.aio.request import Request as _NebiusRequest
from nebius.aio.request_kwargs import RequestKwargs as _NebiusRequestKwargs, StreamRequestKwargs as _NebiusStreamRequestKwargs
from nebius.aio.stream import StreamRequest as _NebiusStreamRequest
from nebius.base.protos.codec import (
    BOOL, BYTES, DOUBLE, FIXED32, FIXED64, FLOAT, INT32, INT64,
    SFIXED32, SFIXED64, SINT32, SINT64, STRING, UINT32, UINT64, enum_codec,
)
from nebius.base.protos.direct import (
    Field, Message, OneOf as _NebiusOneOf,
    OneOfMatchError as _NebiusOneOfMatchError,
    SerializableMessage as _NebiusSerializableMessage, message_codec,
)
from nebius.base.fieldmask_protobuf import ensure_reset_mask_in_metadata
from nebius.base.protos.pb_enum import Enum
from nebius.base.protos.extensions import Extension as _NebiusExtension
from nebius.base.protos.unset import Unset as _NEBIUS_UNSET, UnsetType as _NebiusUnsetType
from nebius.aio.request_status import RequestStatus as _NebiusRequestStatus
from nebius.base.protos.well_known_direct import (
    datetime_to_timestamp as _nebius_datetime_to_timestamp,
    duration_to_timedelta as _nebius_duration_to_timedelta,
    request_status_to_status as _nebius_request_status_to_status,
    status_to_request_status as _nebius_status_to_request_status,
    timedelta_to_duration as _nebius_timedelta_to_duration,
    timestamp_to_datetime as _nebius_timestamp_to_datetime,
)
from ...._registry import EXTENSION_HANDLES, EXTENSIONS, REGISTRY

# @@nebius-section:type_imports@@
if _NEBIUS_TYPE_CHECKING:
    from ....google import protobuf as _type_google_protobuf_dfd76a75
    from ...common import v1 as _type_nebius_common_v1_e3b886bd

# @@nebius-section:enums@@
class AggregationUnit__UnitType(Enum):
    "Aggregation unit type\nIf unit type is one of minute, hour, day, week, month, then it's time-based\nOtherwise it's usage-based"
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.AggregationUnit.UnitType'
    __REGISTRY__ = REGISTRY
    __PROTO_DESCRIPTOR__ = REGISTRY.enum_descriptor('nebius.billing.v1.AggregationUnit.UnitType')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    UNIT_TYPE_UNSPECIFIED = 0
    UNIT_TYPE_TIME_BASED = 1
    UNIT_TYPE_USAGE_BASED = 2
_NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114 = AggregationUnit__UnitType

class FilterAggregationUnit__FilterAggregationUnitValue(Enum):
    "List of time aggregation unit values to filter by.\nOnly costs for these time units will be included in the response, but it doesn't filter not time-based units."
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.FilterAggregationUnit.FilterAggregationUnitValue'
    __REGISTRY__ = REGISTRY
    __PROTO_DESCRIPTOR__ = REGISTRY.enum_descriptor('nebius.billing.v1.FilterAggregationUnit.FilterAggregationUnitValue')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    FILTER_AGGREGATION_UNIT_UNSPECIFIED = 0
    FILTER_AGGREGATION_UNIT_MINUTE = 1
    FILTER_AGGREGATION_UNIT_HOUR = 2
    FILTER_AGGREGATION_UNIT_DAY = 3
    FILTER_AGGREGATION_UNIT_WEEK = 4
    FILTER_AGGREGATION_UNIT_MONTH = 5
_NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3 = FilterAggregationUnit__FilterAggregationUnitValue

class OfferType(Enum):
    'OfferType is a enum that specifies the type of offer.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.OfferType'
    __REGISTRY__ = REGISTRY
    __PROTO_DESCRIPTOR__ = REGISTRY.enum_descriptor('nebius.billing.v1.OfferType')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    OFFER_TYPE_UNSPECIFIED = 0
    OFFER_TYPE_CONTRACT_PRICE = 1
    'Contract price is a special price for SKU.'
_NebiusType_nebius_billing_v1_OfferType_13852ec2 = OfferType

# @@nebius-section:messages@@
class AggregationUnit(Message):
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.AggregationUnit'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.AggregationUnit')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    UnitType: _NebiusTypeAlias = _NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        unit: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        unit_type: _NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114 | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if unit is not _NEBIUS_UNSET:
            values['unit'] = unit
        if unit_type is not _NEBIUS_UNSET:
            values['unit_type'] = unit_type
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def unit(self) -> _NebiusStr:
        'Resource unit value.'
        value = self._get_field(_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @unit.setter
    def unit(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT, value)

    @_NebiusProperty
    def unit_type(self) -> _NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114:
        'Resource unit type.'
        value = self._get_field(_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT_TYPE, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114', None if value is None else REGISTRY.enum_class('nebius.billing.v1.AggregationUnit.UnitType')(value))

    @unit_type.setter
    def unit_type(self, value: _NebiusType_nebius_billing_v1_AggregationUnit_UnitType_e0b2a114 | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT_TYPE, value)

    __PY_TO_PB2__ = {'unit': 'unit', 'unit_type': 'unit_type', 'UnitType': 'UnitType'}
_NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c = AggregationUnit


class AutoscaleResourceCost(Message):
    'Autoscale resource cost.\nUsed for resources that can automatically scale.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.AutoscaleResourceCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.AutoscaleResourceCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        min_cost: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        max_cost: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        per_instance: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        min_instances: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
        max_instances: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if min_cost is not _NEBIUS_UNSET:
            values['min_cost'] = min_cost
        if max_cost is not _NEBIUS_UNSET:
            values['max_cost'] = max_cost
        if per_instance is not _NEBIUS_UNSET:
            values['per_instance'] = per_instance
        if min_instances is not _NEBIUS_UNSET:
            values['min_instances'] = min_instances
        if max_instances is not _NEBIUS_UNSET:
            values['max_instances'] = max_instances
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def min_cost(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Minimum possible cost when scaled to minimum instances.'
        value = self._get_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_COST, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @min_cost.setter
    def min_cost(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_COST, value)

    @_NebiusProperty
    def max_cost(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Maximum possible cost when scaled to maximum instances.'
        value = self._get_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_COST, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @max_cost.setter
    def max_cost(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_COST, value)

    @_NebiusProperty
    def per_instance(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Cost per individual instance.\nUsed to calculate costs at any scaling level between min and max.'
        value = self._get_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_PER_INSTANCE, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @per_instance.setter
    def per_instance(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_PER_INSTANCE, value)

    @_NebiusProperty
    def min_instances(self) -> _NebiusInt:
        'Minimum number of instances in the auto-scaling group.'
        value = self._get_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_INSTANCES, absent_is_none=False)
        return _nebius_cast('_NebiusInt', value)

    @min_instances.setter
    def min_instances(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_INSTANCES, value)

    @_NebiusProperty
    def max_instances(self) -> _NebiusInt:
        'Maximum number of instances in the auto-scaling group.'
        value = self._get_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_INSTANCES, absent_is_none=False)
        return _nebius_cast('_NebiusInt', value)

    @max_instances.setter
    def max_instances(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_INSTANCES, value)

    __PY_TO_PB2__ = {'min_cost': 'min_cost', 'max_cost': 'max_cost', 'per_instance': 'per_instance', 'min_instances': 'min_instances', 'max_instances': 'max_instances'}
_NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819 = AutoscaleResourceCost


class CostBreakdown(Message):
    'Detailed cost breakdown showing individual SKU costs and totals.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.CostBreakdown'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.CostBreakdown')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        sku_costs: _NebiusIterable[_NebiusType_nebius_billing_v1_SkuCost_03854e7d] | None | _NebiusUnsetType = _NEBIUS_UNSET,
        cost: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        cost_rounded: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if sku_costs is not _NEBIUS_UNSET:
            values['sku_costs'] = sku_costs
        if cost is not _NEBIUS_UNSET:
            values['cost'] = cost
        if cost_rounded is not _NEBIUS_UNSET:
            values['cost_rounded'] = cost_rounded
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def sku_costs(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_SkuCost_03854e7d]:
        'Individual costs for each SKU (Stock Keeping Unit) component.\nEach SKU represents a different billable component (e.g., CPU, memory, RAM, etc.).'
        value = self._get_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_SKU_COSTS, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_SkuCost_03854e7d]', value)

    @sku_costs.setter
    def sku_costs(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_SkuCost_03854e7d] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_SKU_COSTS, value)

    @_NebiusProperty
    def cost(self) -> _NebiusStr:
        'Total cost as a decimal string.\nRepresents the sum of all SKU costs with full precision.\nExample: "42.123456789" for precise billing calculations.'
        value = self._get_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @cost.setter
    def cost(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST, value)

    @_NebiusProperty
    def cost_rounded(self) -> _NebiusStr:
        'Total cost rounded up to 2 decimal places.\nExample: "42.13"'
        value = self._get_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST_ROUNDED, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @cost_rounded.setter
    def cost_rounded(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST_ROUNDED, value)

    __PY_TO_PB2__ = {'sku_costs': 'sku_costs', 'cost': 'cost', 'cost_rounded': 'cost_rounded'}
_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe = CostBreakdown


class FilterAggregationUnit(Message):
    'Filters only time-based aggregation units, e.g. hour, day, month, etc.\nIf response contains other aggregation units like request, token, etc., it will always be presented in response.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.FilterAggregationUnit'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.FilterAggregationUnit')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__
    FilterAggregationUnitValue: _NebiusTypeAlias = _NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        filter_aggregation_unit_values: _NebiusIterable[_NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3] | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if filter_aggregation_unit_values is not _NEBIUS_UNSET:
            values['filter_aggregation_unit_values'] = filter_aggregation_unit_values
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def filter_aggregation_unit_values(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3]:
        "List of time aggregation unit values to filter by.\nOnly costs for these time units will be included in the response, but it doesn't filter not time-based units."
        value = self._get_field(_NEBIUS_BILLING_V1_FILTERAGGREGATIONUNIT_FILTER_AGGREGATION_UNIT_VALUES, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3]', value)

    @filter_aggregation_unit_values.setter
    def filter_aggregation_unit_values(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_FilterAggregationUnit_FilterAggregationUnitValue_b7fa25c3] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_FILTERAGGREGATIONUNIT_FILTER_AGGREGATION_UNIT_VALUES, value)

    __PY_TO_PB2__ = {'filter_aggregation_unit_values': 'filter_aggregation_unit_values', 'FilterAggregationUnitValue': 'FilterAggregationUnitValue'}
_NebiusType_nebius_billing_v1_FilterAggregationUnit_bd0735fa = FilterAggregationUnit


class FixedInstanceResourceCost(Message):
    'Fixed instance resource cost.\nUsed for resources that have a fixed number of instances.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.FixedInstanceResourceCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.FixedInstanceResourceCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        total: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        per_instance: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        instance_count: _NebiusInt | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if total is not _NEBIUS_UNSET:
            values['total'] = total
        if per_instance is not _NEBIUS_UNSET:
            values['per_instance'] = per_instance
        if instance_count is not _NEBIUS_UNSET:
            values['instance_count'] = instance_count
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def total(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Total cost for all instances combined.'
        value = self._get_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_TOTAL, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @total.setter
    def total(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_TOTAL, value)

    @_NebiusProperty
    def per_instance(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Cost per individual instance.\nMultiply by instance_count to get total cost.'
        value = self._get_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_PER_INSTANCE, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @per_instance.setter
    def per_instance(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_PER_INSTANCE, value)

    @_NebiusProperty
    def instance_count(self) -> _NebiusInt:
        'Number of instances in the configuration.'
        value = self._get_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_INSTANCE_COUNT, absent_is_none=False)
        return _nebius_cast('_NebiusInt', value)

    @instance_count.setter
    def instance_count(self, value: _NebiusInt | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_INSTANCE_COUNT, value)

    __PY_TO_PB2__ = {'total': 'total', 'per_instance': 'per_instance', 'instance_count': 'instance_count'}
_NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc = FixedInstanceResourceCost


class GeneralResourceCost(Message):
    'General resource cost for single-unit resources.\nUsed for resources like compute instances or disks where the unit count is not variable.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.GeneralResourceCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.GeneralResourceCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        total: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if total is not _NEBIUS_UNSET:
            values['total'] = total
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def total(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Cost breakdown for the resource including all SKU costs and total cost.'
        value = self._get_field(_NEBIUS_BILLING_V1_GENERALRESOURCECOST_TOTAL, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @total.setter
    def total(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_GENERALRESOURCECOST_TOTAL, value)

    __PY_TO_PB2__ = {'total': 'total'}
_NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 = GeneralResourceCost


class GeneralTotalCost(Message):
    'General total cost with a single fixed amount.\nUsed for resources with predictable, non-variable pricing.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.GeneralTotalCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.GeneralTotalCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        total: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if total is not _NEBIUS_UNSET:
            values['total'] = total
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def total(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Cost breakdown including all SKUs and their individual costs.'
        value = self._get_field(_NEBIUS_BILLING_V1_GENERALTOTALCOST_TOTAL, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @total.setter
    def total(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_GENERALTOTALCOST_TOTAL, value)

    __PY_TO_PB2__ = {'total': 'total'}
_NebiusType_nebius_billing_v1_GeneralTotalCost_c4c98160 = GeneralTotalCost


class RangeTotalCost(Message):
    'Range-based total cost with minimum and maximum bounds.\nUsed for resources with variable pricing based on usage or scaling.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.RangeTotalCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.RangeTotalCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        min: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
        max: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if min is not _NEBIUS_UNSET:
            values['min'] = min
        if max is not _NEBIUS_UNSET:
            values['max'] = max
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def min(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Minimum possible cost for the resource group.\nRepresents the cost when resources are at their minimum configuration.'
        value = self._get_field(_NEBIUS_BILLING_V1_RANGETOTALCOST_MIN, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @min.setter
    def min(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RANGETOTALCOST_MIN, value)

    @_NebiusProperty
    def max(self) -> _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe:
        'Maximum possible cost for the resource group.\nRepresents the cost when resources are at their maximum configuration.'
        value = self._get_field(_NEBIUS_BILLING_V1_RANGETOTALCOST_MAX, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe', value)

    @max.setter
    def max(self, value: _NebiusType_nebius_billing_v1_CostBreakdown_45c7aafe | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RANGETOTALCOST_MAX, value)

    __PY_TO_PB2__ = {'min': 'min', 'max': 'max'}
_NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76 = RangeTotalCost


class ResourceCost(Message):
    'Cost information for a single resource.\nContains metadata about the resource and its cost.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.ResourceCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.ResourceCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    class __OneOfClass_cost_type__(_NebiusOneOf):
        name: str = 'cost_type'

    class __OneOfClass_cost_type_general__(__OneOfClass_cost_type__):
        field: _NebiusLiteral['general'] = 'general'

        @_NebiusProperty
        def value(self) -> _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9:
            return _nebius_cast('_NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9', self._message._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_GENERAL),)

    class __OneOfClass_cost_type_fixed_instance__(__OneOfClass_cost_type__):
        field: _NebiusLiteral['fixed_instance'] = 'fixed_instance'

        @_NebiusProperty
        def value(self) -> _NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc:
            return _nebius_cast('_NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc', self._message._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_FIXED_INSTANCE),)

    class __OneOfClass_cost_type_autoscale__(__OneOfClass_cost_type__):
        field: _NebiusLiteral['autoscale'] = 'autoscale'

        @_NebiusProperty
        def value(self) -> _NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819:
            return _nebius_cast('_NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819', self._message._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_AUTOSCALE),)

    @_NebiusProperty
    def cost_type(self) -> __OneOfClass_cost_type_general__ | __OneOfClass_cost_type_fixed_instance__ | __OneOfClass_cost_type_autoscale__ | None:
        selected = self.which_field_in_oneof('cost_type')
        match selected:
            case 'general':
                return self.__OneOfClass_cost_type_general__(self)
            case 'fixed_instance':
                return self.__OneOfClass_cost_type_fixed_instance__(self)
            case 'autoscale':
                return self.__OneOfClass_cost_type_autoscale__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_e3b886bd.ResourceMetadata | None | _NebiusUnsetType = _NEBIUS_UNSET,
        override_metadata: _type_nebius_common_v1_e3b886bd.ResourceMetadata | None | _NebiusUnsetType = _NEBIUS_UNSET,
        aggregation_unit: _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c | None | _NebiusUnsetType = _NEBIUS_UNSET,
        general: _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None | _NebiusUnsetType = _NEBIUS_UNSET,
        fixed_instance: _NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc | None | _NebiusUnsetType = _NEBIUS_UNSET,
        autoscale: _NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819 | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if metadata is not _NEBIUS_UNSET:
            values['metadata'] = metadata
        if override_metadata is not _NEBIUS_UNSET:
            values['override_metadata'] = override_metadata
        if aggregation_unit is not _NEBIUS_UNSET:
            values['aggregation_unit'] = aggregation_unit
        if general is not _NEBIUS_UNSET:
            values['general'] = general
        if fixed_instance is not _NEBIUS_UNSET:
            values['fixed_instance'] = fixed_instance
        if autoscale is not _NEBIUS_UNSET:
            values['autoscale'] = autoscale
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def metadata(self) -> _type_nebius_common_v1_e3b886bd.ResourceMetadata:
        'Resource metadata.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_METADATA, absent_is_none=False)
        return _nebius_cast('_type_nebius_common_v1_e3b886bd.ResourceMetadata', value)

    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_e3b886bd.ResourceMetadata | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_METADATA, value)

    @_NebiusProperty
    def override_metadata(self) -> _type_nebius_common_v1_e3b886bd.ResourceMetadata:
        'Optional field to override the resource metadata.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_OVERRIDE_METADATA, absent_is_none=False)
        return _nebius_cast('_type_nebius_common_v1_e3b886bd.ResourceMetadata', value)

    @override_metadata.setter
    def override_metadata(self, value: _type_nebius_common_v1_e3b886bd.ResourceMetadata | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_OVERRIDE_METADATA, value)

    @_NebiusProperty
    def aggregation_unit(self) -> _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c:
        'Unit of the SKU measurement within a resource, e.g. "hour", "day", "month", etc.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_AGGREGATION_UNIT, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c', value)

    @aggregation_unit.setter
    def aggregation_unit(self, value: _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_AGGREGATION_UNIT, value)

    @_NebiusProperty
    def general(self) -> _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None:
        'General cost for single-unit resources.\nUsed for resources like compute instances or disks where the unit count is not variable.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_GENERAL, absent_is_none=True)
        return _nebius_cast('_NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None', value)

    @general.setter
    def general(self, value: _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_GENERAL, value)

    @_NebiusProperty
    def fixed_instance(self) -> _NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc | None:
        'Fixed instance cost for resources with instances.\nUsed for resources that have a fixed number of instances.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_FIXED_INSTANCE, absent_is_none=True)
        return _nebius_cast('_NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc | None', value)

    @fixed_instance.setter
    def fixed_instance(self, value: _NebiusType_nebius_billing_v1_FixedInstanceResourceCost_432b02fc | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_FIXED_INSTANCE, value)

    @_NebiusProperty
    def autoscale(self) -> _NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819 | None:
        'Autoscale cost for resources with variable instance count.\nUsed for resources that can automatically scale up or down.'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCECOST_AUTOSCALE, absent_is_none=True)
        return _nebius_cast('_NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819 | None', value)

    @autoscale.setter
    def autoscale(self, value: _NebiusType_nebius_billing_v1_AutoscaleResourceCost_44fea819 | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCECOST_AUTOSCALE, value)

    __PY_TO_PB2__ = {'metadata': 'metadata', 'override_metadata': 'override_metadata', 'aggregation_unit': 'aggregation_unit', 'general': 'general', 'fixed_instance': 'fixed_instance', 'autoscale': 'autoscale', 'cost_type': 'cost_type'}
_NebiusType_nebius_billing_v1_ResourceCost_7e97bc98 = ResourceCost


class ResourceSpec(Message):
    'Resource specification for cost estimation.\nContains the specifications for creating and updating different types of resources.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.ResourceSpec'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.ResourceSpec')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        spec: _type_google_protobuf_dfd76a75.Any | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if spec is not _NEBIUS_UNSET:
            values['spec'] = spec
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def spec(self) -> _type_google_protobuf_dfd76a75.Any:
        'Resource specification for cost estimation. Payload must include billing routing annotations. Must contain\neither a create-request or an update-request message for the target resource type. Examples:\ntype.googleapis.com/nebius.compute.v1.CreateInstanceRequest, type.googleapis.com/nebius.compute.v1.UpdateInstanceRequest and so on'
        value = self._get_field(_NEBIUS_BILLING_V1_RESOURCESPEC_SPEC, absent_is_none=False)
        return _nebius_cast('_type_google_protobuf_dfd76a75.Any', value)

    @spec.setter
    def spec(self, value: _type_google_protobuf_dfd76a75.Any | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_RESOURCESPEC_SPEC, value)

    __PY_TO_PB2__ = {'spec': 'spec'}
_NebiusType_nebius_billing_v1_ResourceSpec_466cf0e2 = ResourceSpec


class SkuCost(Message):
    'Cost information for a specific SKU (Stock Keeping Unit).\nRepresents a single billable component within a resource.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.SkuCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.SkuCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        sku_id: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        quantity: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        quantity_rounded: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        cost: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        cost_rounded: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if sku_id is not _NEBIUS_UNSET:
            values['sku_id'] = sku_id
        if quantity is not _NEBIUS_UNSET:
            values['quantity'] = quantity
        if quantity_rounded is not _NEBIUS_UNSET:
            values['quantity_rounded'] = quantity_rounded
        if cost is not _NEBIUS_UNSET:
            values['cost'] = cost
        if cost_rounded is not _NEBIUS_UNSET:
            values['cost_rounded'] = cost_rounded
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def sku_id(self) -> _NebiusStr:
        'Unique identifier for the SKU.'
        value = self._get_field(_NEBIUS_BILLING_V1_SKUCOST_SKU_ID, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @sku_id.setter
    def sku_id(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_SKUCOST_SKU_ID, value)

    @_NebiusProperty
    def quantity(self) -> _NebiusStr:
        'Quantity of the SKU being used as a decimal string.\nExample: "2.123"'
        value = self._get_field(_NEBIUS_BILLING_V1_SKUCOST_QUANTITY, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @quantity.setter
    def quantity(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_SKUCOST_QUANTITY, value)

    @_NebiusProperty
    def quantity_rounded(self) -> _NebiusStr:
        'Quantity rounded up to 2 decimal places.\nExample: "2.13"'
        value = self._get_field(_NEBIUS_BILLING_V1_SKUCOST_QUANTITY_ROUNDED, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @quantity_rounded.setter
    def quantity_rounded(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_SKUCOST_QUANTITY_ROUNDED, value)

    @_NebiusProperty
    def cost(self) -> _NebiusStr:
        'Cost for this SKU as a decimal string.\nCalculated as quantity * unit_price with full precision.\nExample: "15.6789012345" for precise billing calculations.'
        value = self._get_field(_NEBIUS_BILLING_V1_SKUCOST_COST, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @cost.setter
    def cost(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_SKUCOST_COST, value)

    @_NebiusProperty
    def cost_rounded(self) -> _NebiusStr:
        'Cost for this SKU rounded up to 2 decimal places.\nExample: "15.68"'
        value = self._get_field(_NEBIUS_BILLING_V1_SKUCOST_COST_ROUNDED, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @cost_rounded.setter
    def cost_rounded(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_SKUCOST_COST_ROUNDED, value)

    __PY_TO_PB2__ = {'sku_id': 'sku_id', 'quantity': 'quantity', 'quantity_rounded': 'quantity_rounded', 'cost': 'cost', 'cost_rounded': 'cost_rounded'}
_NebiusType_nebius_billing_v1_SkuCost_03854e7d = SkuCost


class TotalCost(Message):
    'Total cost for a single resource unit.'
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.TotalCost'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.TotalCost')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    class __OneOfClass_cost_type__(_NebiusOneOf):
        name: str = 'cost_type'

    class __OneOfClass_cost_type_general__(__OneOfClass_cost_type__):
        field: _NebiusLiteral['general'] = 'general'

        @_NebiusProperty
        def value(self) -> _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9:
            return _nebius_cast('_NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9', self._message._get_field(_NEBIUS_BILLING_V1_TOTALCOST_GENERAL),)

    class __OneOfClass_cost_type_range__(__OneOfClass_cost_type__):
        field: _NebiusLiteral['range'] = 'range'

        @_NebiusProperty
        def value(self) -> _NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76:
            return _nebius_cast('_NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76', self._message._get_field(_NEBIUS_BILLING_V1_TOTALCOST_RANGE),)

    @_NebiusProperty
    def cost_type(self) -> __OneOfClass_cost_type_general__ | __OneOfClass_cost_type_range__ | None:
        selected = self.which_field_in_oneof('cost_type')
        match selected:
            case 'general':
                return self.__OneOfClass_cost_type_general__(self)
            case 'range':
                return self.__OneOfClass_cost_type_range__(self)
            case None:
                return None
            case _:
                raise _NebiusOneOfMatchError(selected)

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        aggregation_unit: _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c | None | _NebiusUnsetType = _NEBIUS_UNSET,
        general: _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None | _NebiusUnsetType = _NEBIUS_UNSET,
        range: _NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76 | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if aggregation_unit is not _NEBIUS_UNSET:
            values['aggregation_unit'] = aggregation_unit
        if general is not _NEBIUS_UNSET:
            values['general'] = general
        if range is not _NEBIUS_UNSET:
            values['range'] = range
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def aggregation_unit(self) -> _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c:
        'Aggregation unit.'
        value = self._get_field(_NEBIUS_BILLING_V1_TOTALCOST_AGGREGATION_UNIT, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c', value)

    @aggregation_unit.setter
    def aggregation_unit(self, value: _NebiusType_nebius_billing_v1_AggregationUnit_5e877f9c | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_TOTALCOST_AGGREGATION_UNIT, value)

    @_NebiusProperty
    def general(self) -> _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None:
        'General total cost for single-unit resources.\nUsed for resources like compute instances or disks where the unit count is not variable.'
        value = self._get_field(_NEBIUS_BILLING_V1_TOTALCOST_GENERAL, absent_is_none=True)
        return _nebius_cast('_NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None', value)

    @general.setter
    def general(self, value: _NebiusType_nebius_billing_v1_GeneralResourceCost_eeccefa9 | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_TOTALCOST_GENERAL, value)

    @_NebiusProperty
    def range(self) -> _NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76 | None:
        'Range-based total cost with minimum and maximum bounds.\nUsed for resources with variable pricing based on usage or scaling.'
        value = self._get_field(_NEBIUS_BILLING_V1_TOTALCOST_RANGE, absent_is_none=True)
        return _nebius_cast('_NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76 | None', value)

    @range.setter
    def range(self, value: _NebiusType_nebius_billing_v1_RangeTotalCost_7a991f76 | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_TOTALCOST_RANGE, value)

    __PY_TO_PB2__ = {'aggregation_unit': 'aggregation_unit', 'general': 'general', 'range': 'range', 'cost_type': 'cost_type'}
_NebiusType_nebius_billing_v1_TotalCost_bcbd0bdf = TotalCost

class EstimateBatchRequest(Message):
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.EstimateBatchRequest'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.EstimateBatchRequest')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        resource_specs: _NebiusIterable[_NebiusType_nebius_billing_v1_ResourceSpec_466cf0e2] | None | _NebiusUnsetType = _NEBIUS_UNSET,
        offer_types: _NebiusIterable[_NebiusType_nebius_billing_v1_OfferType_13852ec2] | None | _NebiusUnsetType = _NEBIUS_UNSET,
        currency: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
        filter_aggregation_unit: _NebiusType_nebius_billing_v1_FilterAggregationUnit_bd0735fa | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if resource_specs is not _NEBIUS_UNSET:
            values['resource_specs'] = resource_specs
        if offer_types is not _NEBIUS_UNSET:
            values['offer_types'] = offer_types
        if currency is not _NEBIUS_UNSET:
            values['currency'] = currency
        if filter_aggregation_unit is not _NEBIUS_UNSET:
            values['filter_aggregation_unit'] = filter_aggregation_unit
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def resource_specs(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_ResourceSpec_466cf0e2]:
        'List of resource specifications for cost estimation.\nEach resource will be priced individually and then aggregated into total costs.'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_RESOURCE_SPECS, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_ResourceSpec_466cf0e2]', value)

    @resource_specs.setter
    def resource_specs(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_ResourceSpec_466cf0e2] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_RESOURCE_SPECS, value)

    @_NebiusProperty
    def offer_types(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_OfferType_13852ec2]:
        'Type of offers to be applied to the cost estimate.'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_OFFER_TYPES, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_OfferType_13852ec2]', value)

    @offer_types.setter
    def offer_types(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_OfferType_13852ec2] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_OFFER_TYPES, value)

    @_NebiusProperty
    def currency(self) -> _NebiusStr:
        'Currency for the cost estimate (e.g., "usd", "ils"). Defaults to "usd".'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_CURRENCY, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @currency.setter
    def currency(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_CURRENCY, value)

    @_NebiusProperty
    def filter_aggregation_unit(self) -> _NebiusType_nebius_billing_v1_FilterAggregationUnit_bd0735fa:
        'Filters only time-based resource units, e.g. hour, day, month, etc.\nIf response contains other resource units like request, token, etc., it will always be presented in response.'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_FILTER_AGGREGATION_UNIT, absent_is_none=False)
        return _nebius_cast('_NebiusType_nebius_billing_v1_FilterAggregationUnit_bd0735fa', value)

    @filter_aggregation_unit.setter
    def filter_aggregation_unit(self, value: _NebiusType_nebius_billing_v1_FilterAggregationUnit_bd0735fa | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_FILTER_AGGREGATION_UNIT, value)

    __PY_TO_PB2__ = {'resource_specs': 'resource_specs', 'offer_types': 'offer_types', 'currency': 'currency', 'filter_aggregation_unit': 'filter_aggregation_unit'}
_NebiusType_nebius_billing_v1_EstimateBatchRequest_ab2ec2ec = EstimateBatchRequest


class EstimateBatchResponse(Message):
    __PROTO_FULL_NAME__ = 'nebius.billing.v1.EstimateBatchResponse'
    __REGISTRY__ = REGISTRY
    __EXTENSION_REGISTRY__ = EXTENSIONS
    __PROTO_DESCRIPTOR__ = REGISTRY.message_descriptor('nebius.billing.v1.EstimateBatchResponse')
    __PB2_DESCRIPTOR__ = __PROTO_DESCRIPTOR__

    def __init__(
        self,
        initial_message: _NebiusSerializableMessage | None = None,
        *,
        resource_costs: _NebiusIterable[_NebiusType_nebius_billing_v1_ResourceCost_7e97bc98] | None | _NebiusUnsetType = _NEBIUS_UNSET,
        total_costs: _NebiusIterable[_NebiusType_nebius_billing_v1_TotalCost_bcbd0bdf] | None | _NebiusUnsetType = _NEBIUS_UNSET,
        currency: _NebiusStr | None | _NebiusUnsetType = _NEBIUS_UNSET,
    ) -> None:
        values: _NebiusDict[_NebiusStr, _NebiusObject] = {}
        if resource_costs is not _NEBIUS_UNSET:
            values['resource_costs'] = resource_costs
        if total_costs is not _NEBIUS_UNSET:
            values['total_costs'] = total_costs
        if currency is not _NEBIUS_UNSET:
            values['currency'] = currency
        super().__init__(initial_message, **values)

    @_NebiusProperty
    def resource_costs(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_ResourceCost_7e97bc98]:
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_RESOURCE_COSTS, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_ResourceCost_7e97bc98]', value)

    @resource_costs.setter
    def resource_costs(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_ResourceCost_7e97bc98] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_RESOURCE_COSTS, value)

    @_NebiusProperty
    def total_costs(self) -> _NebiusMutableSequence[_NebiusType_nebius_billing_v1_TotalCost_bcbd0bdf]:
        'Total cost for all resource units.'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_TOTAL_COSTS, absent_is_none=False)
        return _nebius_cast('_NebiusMutableSequence[_NebiusType_nebius_billing_v1_TotalCost_bcbd0bdf]', value)

    @total_costs.setter
    def total_costs(self, value: _NebiusIterable[_NebiusType_nebius_billing_v1_TotalCost_bcbd0bdf] | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_TOTAL_COSTS, value)

    @_NebiusProperty
    def currency(self) -> _NebiusStr:
        'Currency used for the estimate.'
        value = self._get_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_CURRENCY, absent_is_none=False)
        return _nebius_cast('_NebiusStr', value)

    @currency.setter
    def currency(self, value: _NebiusStr | None) -> None:
        self._set_field(_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_CURRENCY, value)

    __PY_TO_PB2__ = {'resource_costs': 'resource_costs', 'total_costs': 'total_costs', 'currency': 'currency'}
_NebiusType_nebius_billing_v1_EstimateBatchResponse_d3f6ce47 = EstimateBatchResponse

# @@nebius-section:fields@@
_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT = Field('unit', 'unit', 1, STRING, json_name='unit')
_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT_TYPE = Field('unit_type', 'unit_type', 2, enum_codec((0, 1, 2), default=0, closed=False, names={'UNIT_TYPE_UNSPECIFIED': 0, 'UNIT_TYPE_TIME_BASED': 1, 'UNIT_TYPE_USAGE_BASED': 2}, enum_type=lambda: REGISTRY.enum_class('nebius.billing.v1.AggregationUnit.UnitType')), json_name='unitType')
AggregationUnit.__FIELDS__ = (_NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT, _NEBIUS_BILLING_V1_AGGREGATIONUNIT_UNIT_TYPE)

_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_COST = Field('min_cost', 'min_cost', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='minCost')
_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_COST = Field('max_cost', 'max_cost', 2, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='maxCost')
_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_PER_INSTANCE = Field('per_instance', 'per_instance', 3, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='perInstance')
_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_INSTANCES = Field('min_instances', 'min_instances', 4, INT32, json_name='minInstances')
_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_INSTANCES = Field('max_instances', 'max_instances', 5, INT32, json_name='maxInstances')
AutoscaleResourceCost.__FIELDS__ = (_NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_COST, _NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_COST, _NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_PER_INSTANCE, _NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MIN_INSTANCES, _NEBIUS_BILLING_V1_AUTOSCALERESOURCECOST_MAX_INSTANCES)

_NEBIUS_BILLING_V1_COSTBREAKDOWN_SKU_COSTS = Field('sku_costs', 'sku_costs', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.SkuCost')), repeated=True, json_name='skuCosts')
_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST = Field('cost', 'cost', 2, STRING, json_name='cost')
_NEBIUS_BILLING_V1_COSTBREAKDOWN_COST_ROUNDED = Field('cost_rounded', 'cost_rounded', 3, STRING, json_name='costRounded')
CostBreakdown.__FIELDS__ = (_NEBIUS_BILLING_V1_COSTBREAKDOWN_SKU_COSTS, _NEBIUS_BILLING_V1_COSTBREAKDOWN_COST, _NEBIUS_BILLING_V1_COSTBREAKDOWN_COST_ROUNDED)

_NEBIUS_BILLING_V1_FILTERAGGREGATIONUNIT_FILTER_AGGREGATION_UNIT_VALUES = Field('filter_aggregation_unit_values', 'filter_aggregation_unit_values', 1, enum_codec((0, 1, 2, 3, 4, 5), default=0, closed=False, names={'FILTER_AGGREGATION_UNIT_UNSPECIFIED': 0, 'FILTER_AGGREGATION_UNIT_MINUTE': 1, 'FILTER_AGGREGATION_UNIT_HOUR': 2, 'FILTER_AGGREGATION_UNIT_DAY': 3, 'FILTER_AGGREGATION_UNIT_WEEK': 4, 'FILTER_AGGREGATION_UNIT_MONTH': 5}, enum_type=lambda: REGISTRY.enum_class('nebius.billing.v1.FilterAggregationUnit.FilterAggregationUnitValue')), repeated=True, packed=True, json_name='filterAggregationUnitValues')
FilterAggregationUnit.__FIELDS__ = (_NEBIUS_BILLING_V1_FILTERAGGREGATIONUNIT_FILTER_AGGREGATION_UNIT_VALUES,)

_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_TOTAL = Field('total', 'total', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='total')
_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_PER_INSTANCE = Field('per_instance', 'per_instance', 2, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='perInstance')
_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_INSTANCE_COUNT = Field('instance_count', 'instance_count', 3, INT32, json_name='instanceCount')
FixedInstanceResourceCost.__FIELDS__ = (_NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_TOTAL, _NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_PER_INSTANCE, _NEBIUS_BILLING_V1_FIXEDINSTANCERESOURCECOST_INSTANCE_COUNT)

_NEBIUS_BILLING_V1_GENERALRESOURCECOST_TOTAL = Field('total', 'total', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='total')
GeneralResourceCost.__FIELDS__ = (_NEBIUS_BILLING_V1_GENERALRESOURCECOST_TOTAL,)

_NEBIUS_BILLING_V1_GENERALTOTALCOST_TOTAL = Field('total', 'total', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='total')
GeneralTotalCost.__FIELDS__ = (_NEBIUS_BILLING_V1_GENERALTOTALCOST_TOTAL,)

_NEBIUS_BILLING_V1_RANGETOTALCOST_MIN = Field('min', 'min', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='min')
_NEBIUS_BILLING_V1_RANGETOTALCOST_MAX = Field('max', 'max', 2, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.CostBreakdown')), json_name='max')
RangeTotalCost.__FIELDS__ = (_NEBIUS_BILLING_V1_RANGETOTALCOST_MIN, _NEBIUS_BILLING_V1_RANGETOTALCOST_MAX)

_NEBIUS_BILLING_V1_RESOURCECOST_METADATA = Field('metadata', 'metadata', 1, message_codec(lambda: REGISTRY.message_class('nebius.common.v1.ResourceMetadata')), json_name='metadata')
_NEBIUS_BILLING_V1_RESOURCECOST_OVERRIDE_METADATA = Field('override_metadata', 'override_metadata', 2, message_codec(lambda: REGISTRY.message_class('nebius.common.v1.ResourceMetadata')), json_name='overrideMetadata')
_NEBIUS_BILLING_V1_RESOURCECOST_AGGREGATION_UNIT = Field('aggregation_unit', 'aggregation_unit', 4, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.AggregationUnit')), json_name='aggregationUnit')
_NEBIUS_BILLING_V1_RESOURCECOST_GENERAL = Field('general', 'general', 20, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.GeneralResourceCost')), oneof='cost_type', json_name='general')
_NEBIUS_BILLING_V1_RESOURCECOST_FIXED_INSTANCE = Field('fixed_instance', 'fixed_instance', 21, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.FixedInstanceResourceCost')), oneof='cost_type', json_name='fixedInstance')
_NEBIUS_BILLING_V1_RESOURCECOST_AUTOSCALE = Field('autoscale', 'autoscale', 22, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.AutoscaleResourceCost')), oneof='cost_type', json_name='autoscale')
ResourceCost.__FIELDS__ = (_NEBIUS_BILLING_V1_RESOURCECOST_METADATA, _NEBIUS_BILLING_V1_RESOURCECOST_OVERRIDE_METADATA, _NEBIUS_BILLING_V1_RESOURCECOST_AGGREGATION_UNIT, _NEBIUS_BILLING_V1_RESOURCECOST_GENERAL, _NEBIUS_BILLING_V1_RESOURCECOST_FIXED_INSTANCE, _NEBIUS_BILLING_V1_RESOURCECOST_AUTOSCALE)

_NEBIUS_BILLING_V1_RESOURCESPEC_SPEC = Field('spec', 'spec', 1, message_codec(lambda: REGISTRY.message_class('google.protobuf.Any')), json_name='spec')
ResourceSpec.__FIELDS__ = (_NEBIUS_BILLING_V1_RESOURCESPEC_SPEC,)

_NEBIUS_BILLING_V1_SKUCOST_SKU_ID = Field('sku_id', 'sku_id', 1, STRING, json_name='skuId')
_NEBIUS_BILLING_V1_SKUCOST_QUANTITY = Field('quantity', 'quantity', 20, STRING, json_name='quantity')
_NEBIUS_BILLING_V1_SKUCOST_QUANTITY_ROUNDED = Field('quantity_rounded', 'quantity_rounded', 21, STRING, json_name='quantityRounded')
_NEBIUS_BILLING_V1_SKUCOST_COST = Field('cost', 'cost', 30, STRING, json_name='cost')
_NEBIUS_BILLING_V1_SKUCOST_COST_ROUNDED = Field('cost_rounded', 'cost_rounded', 31, STRING, json_name='costRounded')
SkuCost.__FIELDS__ = (_NEBIUS_BILLING_V1_SKUCOST_SKU_ID, _NEBIUS_BILLING_V1_SKUCOST_QUANTITY, _NEBIUS_BILLING_V1_SKUCOST_QUANTITY_ROUNDED, _NEBIUS_BILLING_V1_SKUCOST_COST, _NEBIUS_BILLING_V1_SKUCOST_COST_ROUNDED)

_NEBIUS_BILLING_V1_TOTALCOST_AGGREGATION_UNIT = Field('aggregation_unit', 'aggregation_unit', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.AggregationUnit')), json_name='aggregationUnit')
_NEBIUS_BILLING_V1_TOTALCOST_GENERAL = Field('general', 'general', 20, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.GeneralResourceCost')), oneof='cost_type', json_name='general')
_NEBIUS_BILLING_V1_TOTALCOST_RANGE = Field('range', 'range', 21, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.RangeTotalCost')), oneof='cost_type', json_name='range')
TotalCost.__FIELDS__ = (_NEBIUS_BILLING_V1_TOTALCOST_AGGREGATION_UNIT, _NEBIUS_BILLING_V1_TOTALCOST_GENERAL, _NEBIUS_BILLING_V1_TOTALCOST_RANGE)

_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_RESOURCE_SPECS = Field('resource_specs', 'resource_specs', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.ResourceSpec')), repeated=True, json_name='resourceSpecs')
_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_OFFER_TYPES = Field('offer_types', 'offer_types', 10, enum_codec((0, 1), default=0, closed=False, names={'OFFER_TYPE_UNSPECIFIED': 0, 'OFFER_TYPE_CONTRACT_PRICE': 1}, enum_type=lambda: REGISTRY.enum_class('nebius.billing.v1.OfferType')), repeated=True, packed=True, json_name='offerTypes')
_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_CURRENCY = Field('currency', 'currency', 11, STRING, json_name='currency')
_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_FILTER_AGGREGATION_UNIT = Field('filter_aggregation_unit', 'filter_aggregation_unit', 20, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.FilterAggregationUnit')), json_name='filterAggregationUnit')
EstimateBatchRequest.__FIELDS__ = (_NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_RESOURCE_SPECS, _NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_OFFER_TYPES, _NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_CURRENCY, _NEBIUS_BILLING_V1_ESTIMATEBATCHREQUEST_FILTER_AGGREGATION_UNIT)

_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_RESOURCE_COSTS = Field('resource_costs', 'resource_costs', 1, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.ResourceCost')), repeated=True, json_name='resourceCosts')
_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_TOTAL_COSTS = Field('total_costs', 'total_costs', 10, message_codec(lambda: REGISTRY.message_class('nebius.billing.v1.TotalCost')), repeated=True, json_name='totalCosts')
_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_CURRENCY = Field('currency', 'currency', 20, STRING, json_name='currency')
EstimateBatchResponse.__FIELDS__ = (_NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_RESOURCE_COSTS, _NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_TOTAL_COSTS, _NEBIUS_BILLING_V1_ESTIMATEBATCHRESPONSE_CURRENCY)

# @@nebius-section:attachments@@
AggregationUnit__UnitType.__name__ = 'UnitType'
AggregationUnit__UnitType.__qualname__ = 'AggregationUnit.UnitType'
FilterAggregationUnit__FilterAggregationUnitValue.__name__ = 'FilterAggregationUnitValue'
FilterAggregationUnit__FilterAggregationUnitValue.__qualname__ = 'FilterAggregationUnit.FilterAggregationUnitValue'

# @@nebius-section:extensions@@
# @@nebius-section:services@@
class CalculatorServiceClient(_NebiusClient):
    'Calculator service for estimating resource costs.\n\nThis class provides client methods for the ``nebius.billing.v1.CalculatorService`` service.'
    __service_name__ = 'nebius.billing.v1.CalculatorService'
    __api_service_name__ = 'api.calculator.billing-data-plane'
    __registry__ = REGISTRY

    @classmethod
    def get_descriptor(cls) -> _NebiusObject:
        return REGISTRY.service_descriptor('nebius.billing.v1.CalculatorService')

    __PB2_DESCRIPTOR__ = REGISTRY.service_descriptor('nebius.billing.v1.CalculatorService')

    def estimate_batch(
        self,
        request: _NebiusType_nebius_billing_v1_EstimateBatchRequest_ab2ec2ec,
        **kwargs: _NebiusUnpack[_NebiusRequestKwargs],
    ) -> _NebiusRequest[_NebiusType_nebius_billing_v1_EstimateBatchRequest_ab2ec2ec, _NebiusType_nebius_billing_v1_EstimateBatchResponse_d3f6ce47]:
        'Estimates prices for multiple resources.\nReturns aggregated hourly and monthly cost estimates for all specified resources.\n\nThe request object is returned without starting the RPC.'
        return super().request(
            method='EstimateBatch',
            request=request,
            result_pb2_class=REGISTRY.message_class('nebius.billing.v1.EstimateBatchResponse'),
            **kwargs,
        )

# @@nebius-section:exports@@
__all__ = ['AggregationUnit', 'AutoscaleResourceCost', 'CalculatorServiceClient', 'CostBreakdown', 'EstimateBatchRequest', 'EstimateBatchResponse', 'FilterAggregationUnit', 'FixedInstanceResourceCost', 'GeneralResourceCost', 'GeneralTotalCost', 'OfferType', 'RangeTotalCost', 'ResourceCost', 'ResourceSpec', 'SkuCost', 'TotalCost']
