# Code generated by protoc-gen-pysdk. DO NOT EDIT.
from __future__ import annotations

import builtins as _builtins
from collections.abc import (
    AsyncIterable as _AsyncIterable,
    Iterable as _Iterable,
    Mapping as _Mapping,
    MutableMapping as _MutableMapping,
    MutableSequence as _MutableSequence,
)
from datetime import datetime as _datetime, timedelta as _timedelta
from typing import Any as _Any, Literal as _Literal, TypeAlias as _TypeAlias
from typing_extensions import Unpack as _Unpack
from ......aio.client import Client as _Client, ClientWithOperations as _ClientWithOperations
from ......aio.operation import Operation as _AsyncOperation
from ......aio.request import Request as _Request
from ......aio.request_kwargs import RequestKwargs as _RequestKwargs, StreamRequestKwargs as _StreamRequestKwargs
from ......aio.request_status import RequestStatus as _RequestStatus
from ......aio.stream import StreamRequest as _StreamRequest
from ......base.protos.direct import Message as _Message, OneOf as _OneOf, SerializableMessage as _SerializableMessage
from ......base.protos.extensions import Extension as _Extension
from ......base.protos.extensions import ExtensionRegistry as _ExtensionRegistry
from ......base.protos.pb_enum import Enum as _Enum
from ......base.protos.registry import Registry as _Registry
from ......base.protos.unset import UnsetType as _UnsetType
from ....common.v1alpha1 import Operation as _type_nebius_common_v1alpha1_Operation
from ....common.v1 import GetByNameRequest as _type_nebius_common_v1_GetByNameRequest
from ....common.v1 import ResourceMetadata as _type_nebius_common_v1_ResourceMetadata
from .config import PostgresqlConfig16 as _type_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16
from ...v1alpha1.resource import DiskSpec as _type_nebius_msp_v1alpha1_resource_DiskSpec
from ...v1alpha1.resource import HostSpec as _type_nebius_msp_v1alpha1_resource_HostSpec
from ...v1alpha1.resource import PresetDetails as _type_nebius_msp_v1alpha1_resource_PresetDetails
from ...v1alpha1.resource import ResourcesSpec as _type_nebius_msp_v1alpha1_resource_ResourcesSpec
from ...v1alpha1 import ClusterStatus__Phase as _type_nebius_msp_v1alpha1_ClusterStatus_Phase
from ...v1alpha1 import ClusterStatus__State as _type_nebius_msp_v1alpha1_ClusterStatus_State

REGISTRY: _Registry
EXTENSIONS: _ExtensionRegistry
EXTENSION_HANDLES: dict[str, _Extension[_Any]]

class Backup(_Message):
    @property
    def id(self) -> _builtins.str:
        """Required. ID of the backup."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def source_cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster that the backup was created for."""
        ...
    @source_cluster_id.setter
    def source_cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``source_cluster_id`` field."""
        ...
    @property
    def creation_start(self) -> _datetime | None:
        """Creation start timestamp."""
        ...
    @creation_start.setter
    def creation_start(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``creation_start`` field."""
        ...
    @property
    def creation_finish(self) -> _datetime | None:
        """Creation finish timestamp."""
        ...
    @creation_finish.setter
    def creation_finish(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``creation_finish`` field."""
        ...
    @property
    def source_cluster_name(self) -> _builtins.str:
        """Name of the PostgreSQL cluster that the backup was created for."""
        ...
    @source_cluster_name.setter
    def source_cluster_name(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``source_cluster_name`` field."""
        ...
    @property
    def source_cluster_visible(self) -> _builtins.bool:
        """Is PostgreSQL cluster that the backup was created for visible."""
        ...
    @source_cluster_visible.setter
    def source_cluster_visible(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``source_cluster_visible`` field."""
        ...
    @property
    def on_demand(self) -> _builtins.bool:
        """Is the backup an on-demand manual backup."""
        ...
    @on_demand.setter
    def on_demand(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``on_demand`` field."""
        ...
    @property
    def size_bytes(self) -> _builtins.int:
        """Size of the backup in bytes."""
        ...
    @size_bytes.setter
    def size_bytes(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``size_bytes`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        source_cluster_id: _builtins.str | None | _UnsetType = ...,
        creation_start: _datetime | _SerializableMessage | None | _UnsetType = ...,
        creation_finish: _datetime | _SerializableMessage | None | _UnsetType = ...,
        source_cluster_name: _builtins.str | None | _UnsetType = ...,
        source_cluster_visible: _builtins.bool | None | _UnsetType = ...,
        on_demand: _builtins.bool | None | _UnsetType = ...,
        size_bytes: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetBackupRequest(_Message):
    @property
    def cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster that holds backup."""
        ...
    @cluster_id.setter
    def cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_id`` field."""
        ...
    @property
    def backup_id(self) -> _builtins.str:
        """ID of the designated backup."""
        ...
    @backup_id.setter
    def backup_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``backup_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_id: _builtins.str | None | _UnsetType = ...,
        backup_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListBackupsRequest(_Message):
    @property
    def parent_id(self) -> _builtins.str:
        """Identifier of IAM container to list backups from."""
        ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, parent_id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListBackupsByClusterRequest(_Message):
    @property
    def cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster to list backups from."""
        ...
    @cluster_id.setter
    def cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListBackupsResponse(_Message):
    @property
    def backups(self) -> _MutableSequence[Backup]:
        """List of backups."""
        ...
    @backups.setter
    def backups(self, value: _Iterable[Backup] | None) -> None:
        """Set or clear the generated ``backups`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        backups: _Iterable[Backup] | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class CreateBackupRequest(_Message):
    @property
    def cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster that holds backup."""
        ...
    @cluster_id.setter
    def cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class DeleteBackupRequest(_Message):
    @property
    def cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster that holds backup."""
        ...
    @cluster_id.setter
    def cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``cluster_id`` field."""
        ...
    @property
    def backup_id(self) -> _builtins.str:
        """ID of the designated backup."""
        ...
    @backup_id.setter
    def backup_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``backup_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        cluster_id: _builtins.str | None | _UnsetType = ...,
        backup_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Cluster(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata: ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec: ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    @property
    def status(self) -> ClusterStatus: ...
    @status.setter
    def status(self, value: ClusterStatus | None) -> None:
        """Set or clear the generated ``status`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
        status: ClusterStatus | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ConnectionPoolerConfig__PoolingMode(_Enum):
    POOLING_MODE_UNSPECIFIED = ...
    SESSION = ...
    """Session pooling mode."""
    TRANSACTION = ...
    """Transaction pooling mode."""

class ConnectionPoolerConfig(_Message):
    PoolingMode: _TypeAlias = ConnectionPoolerConfig__PoolingMode
    @property
    def pooling_mode(self) -> ConnectionPoolerConfig__PoolingMode:
        """Mode that the connection pooler is working in."""
        ...
    @pooling_mode.setter
    def pooling_mode(self, value: ConnectionPoolerConfig__PoolingMode | None) -> None:
        """Set or clear the generated ``pooling_mode`` field."""
        ...
    @property
    def max_pool_size(self) -> _builtins.int | None:
        """Maximum number of connections in the pool for a single user/database pair."""
        ...
    @max_pool_size.setter
    def max_pool_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``max_pool_size`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        pooling_mode: ConnectionPoolerConfig__PoolingMode | None | _UnsetType = ...,
        max_pool_size: _builtins.int | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterSpec(_Message):
    @property
    def description(self) -> _builtins.str:
        """Description of the PostgreSQL cluster."""
        ...
    @description.setter
    def description(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``description`` field."""
        ...
    @property
    def network_id(self) -> _builtins.str:
        """Network ID in which the cluster is created."""
        ...
    @network_id.setter
    def network_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``network_id`` field."""
        ...
    @property
    def config(self) -> ConfigSpec: ...
    @config.setter
    def config(self, value: ConfigSpec | None) -> None:
        """Set or clear the generated ``config`` field."""
        ...
    @property
    def bootstrap(self) -> BootstrapSpec: ...
    @bootstrap.setter
    def bootstrap(self, value: BootstrapSpec | None) -> None:
        """Set or clear the generated ``bootstrap`` field."""
        ...
    @property
    def backup(self) -> BackupSpec: ...
    @backup.setter
    def backup(self, value: BackupSpec | None) -> None:
        """Set or clear the generated ``backup`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        description: _builtins.str | None | _UnsetType = ...,
        network_id: _builtins.str | None | _UnsetType = ...,
        config: ConfigSpec | None | _UnsetType = ...,
        bootstrap: BootstrapSpec | None | _UnsetType = ...,
        backup: BackupSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ClusterStatus(_Message):
    @property
    def phase(self) -> _type_nebius_msp_v1alpha1_ClusterStatus_Phase:
        """Current phase of the cluster."""
        ...
    @phase.setter
    def phase(self, value: _type_nebius_msp_v1alpha1_ClusterStatus_Phase | None) -> None:
        """Set or clear the generated ``phase`` field."""
        ...
    @property
    def state(self) -> _type_nebius_msp_v1alpha1_ClusterStatus_State:
        """State reflects substatus of the phase to define whether it's healthy or not."""
        ...
    @state.setter
    def state(self, value: _type_nebius_msp_v1alpha1_ClusterStatus_State | None) -> None:
        """Set or clear the generated ``state`` field."""
        ...
    @property
    def preset_details(self) -> _type_nebius_msp_v1alpha1_resource_PresetDetails:
        """Cluster resource preset details"""
        ...
    @preset_details.setter
    def preset_details(self, value: _type_nebius_msp_v1alpha1_resource_PresetDetails | None) -> None:
        """Set or clear the generated ``preset_details`` field."""
        ...
    @property
    def connection_endpoints(self) -> Endpoints:
        """Connection endpoints of the PostgreSQL cluster."""
        ...
    @connection_endpoints.setter
    def connection_endpoints(self, value: Endpoints | None) -> None:
        """Set or clear the generated ``connection_endpoints`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        phase: _type_nebius_msp_v1alpha1_ClusterStatus_Phase | None | _UnsetType = ...,
        state: _type_nebius_msp_v1alpha1_ClusterStatus_State | None | _UnsetType = ...,
        preset_details: _type_nebius_msp_v1alpha1_resource_PresetDetails | None | _UnsetType = ...,
        connection_endpoints: Endpoints | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class Endpoints(_Message):
    @property
    def private_read_write(self) -> _builtins.str:
        """Read write endpoint of the PostgreSQL cluster accessible from the private VPC."""
        ...
    @private_read_write.setter
    def private_read_write(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``private_read_write`` field."""
        ...
    @property
    def private_read_only(self) -> _builtins.str:
        """Read only endpoint of the PostgreSQL cluster accessible from the private VPC."""
        ...
    @private_read_only.setter
    def private_read_only(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``private_read_only`` field."""
        ...
    @property
    def public_read_write(self) -> _builtins.str:
        """Read write endpoint of the PostgreSQL cluster accessible from the internet."""
        ...
    @public_read_write.setter
    def public_read_write(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``public_read_write`` field."""
        ...
    @property
    def public_read_only(self) -> _builtins.str:
        """Read only endpoint of the PostgreSQL cluster accessible from the internet."""
        ...
    @public_read_only.setter
    def public_read_only(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``public_read_only`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        private_read_write: _builtins.str | None | _UnsetType = ...,
        private_read_only: _builtins.str | None | _UnsetType = ...,
        public_read_write: _builtins.str | None | _UnsetType = ...,
        public_read_only: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ConfigSpec(_Message):
    class __OneOfClass_config__(_OneOf):
        """Config of the PostgreSQL cluster."""

        name: _Literal["config"] = ...

    class __OneOfClass_config_postgresql_config_16__(__OneOfClass_config__):
        """Configuration parameters for postgres"""

        field: _Literal["postgresql_config_16"] = ...
        @property
        def value(self) -> _type_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16:
            """Configuration parameters for postgres"""
            ...

    @property
    def config(self) -> __OneOfClass_config_postgresql_config_16__ | None:
        """Config of the PostgreSQL cluster."""
        ...
    @property
    def version(self) -> _builtins.str:
        """Version of PostgreSQL used in the cluster.\nPossible values: ``16``"""
        ...
    @version.setter
    def version(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``version`` field."""
        ...
    @property
    def pooler_config(self) -> ConnectionPoolerConfig:
        """Configuration of the connection pooler."""
        ...
    @pooler_config.setter
    def pooler_config(self, value: ConnectionPoolerConfig | None) -> None:
        """Set or clear the generated ``pooler_config`` field."""
        ...
    @property
    def postgresql_config_16(self) -> _type_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16 | None:
        """Configuration parameters for postgres"""
        ...
    @postgresql_config_16.setter
    def postgresql_config_16(
        self, value: _type_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16 | None
    ) -> None:
        """Set or clear the generated ``postgresql_config_16`` field."""
        ...
    @property
    def public_access(self) -> _builtins.bool:
        """Either make cluster public accessible or accessible only via private VPC."""
        ...
    @public_access.setter
    def public_access(self, value: _builtins.bool | None) -> None:
        """Set or clear the generated ``public_access`` field."""
        ...
    @property
    def template(self) -> TemplateSpec:
        """Resources allocated to PostgreSQL hosts."""
        ...
    @template.setter
    def template(self, value: TemplateSpec | None) -> None:
        """Set or clear the generated ``template`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        version: _builtins.str | None | _UnsetType = ...,
        pooler_config: ConnectionPoolerConfig | None | _UnsetType = ...,
        postgresql_config_16: _type_nebius_msp_postgresql_v1alpha1_config_PostgresqlConfig16 | None | _UnsetType = ...,
        public_access: _builtins.bool | None | _UnsetType = ...,
        template: TemplateSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BootstrapSpec(_Message):
    @property
    def user_name(self) -> _builtins.str:
        """Name of the bootstrap PostgreSQL user."""
        ...
    @user_name.setter
    def user_name(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``user_name`` field."""
        ...
    @property
    def user_password(self) -> _builtins.str:
        """Password of the bootstrap PostgreSQL user."""
        ...
    @user_password.setter
    def user_password(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``user_password`` field."""
        ...
    @property
    def db_name(self) -> _builtins.str:
        """Name of the PostgreSQL database. 1-63 characters long."""
        ...
    @db_name.setter
    def db_name(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``db_name`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        user_name: _builtins.str | None | _UnsetType = ...,
        user_password: _builtins.str | None | _UnsetType = ...,
        db_name: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BackupSpec(_Message):
    @property
    def backup_window_start(self) -> _builtins.str:
        """Backup window start in \"HH:MM:SS\" format (UTC Time)"""
        ...
    @backup_window_start.setter
    def backup_window_start(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``backup_window_start`` field."""
        ...
    @property
    def retention_policy(self) -> _builtins.str:
        """Retention policy to be used for backups and WALs (i.e. '7d')"""
        ...
    @retention_policy.setter
    def retention_policy(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``retention_policy`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        backup_window_start: _builtins.str | None | _UnsetType = ...,
        retention_policy: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str:
        """ID of the PostgreSQL Cluster resource to return.\nTo get the cluster ID use a [ClusterService.List] request."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class GetClusterForBackupRequest(_Message):
    @property
    def id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster that holds backup."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    @property
    def backup_id(self) -> _builtins.str:
        """ID of the backup for which source cluster is requested."""
        ...
    @backup_id.setter
    def backup_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``backup_id`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        id: _builtins.str | None | _UnsetType = ...,
        backup_id: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClustersRequest(_Message):
    @property
    def parent_id(self) -> _builtins.str:
        """Identifier of IAM container to list clusters from."""
        ...
    @parent_id.setter
    def parent_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``parent_id`` field."""
        ...
    @property
    def page_size(self) -> _builtins.int:
        """Specifies the maximum number of items to return in the response."""
        ...
    @page_size.setter
    def page_size(self, value: _builtins.int | None) -> None:
        """Set or clear the generated ``page_size`` field."""
        ...
    @property
    def page_token(self) -> _builtins.str:
        """Token for pagination, allowing the retrieval of the next set of results."""
        ...
    @page_token.setter
    def page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        parent_id: _builtins.str | None | _UnsetType = ...,
        page_size: _builtins.int | None | _UnsetType = ...,
        page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class ListClustersResponse(_Message):
    @property
    def clusters(self) -> _MutableSequence[Cluster]:
        """List of PostgreSQL Cluster resources."""
        ...
    @clusters.setter
    def clusters(self, value: _Iterable[Cluster] | None) -> None:
        """Set or clear the generated ``clusters`` field."""
        ...
    @property
    def next_page_token(self) -> _builtins.str:
        """This token allows you to get the next page of results for list requests. If the number of results\nis larger than [ListClustersRequest.page\\_size], use the [next\\_page\\_token] as the value\nfor the [ListClustersRequest.page\\_token] parameter in the next list request. Each subsequent\nlist request will have its own [next\\_page\\_token] to continue paging through the results."""
        ...
    @next_page_token.setter
    def next_page_token(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``next_page_token`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        clusters: _Iterable[Cluster] | None | _UnsetType = ...,
        next_page_token: _builtins.str | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class CreateClusterRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata:
        """Metadata associated with the new cluster."""
        ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec:
        """Specification for the new cluster."""
        ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class RestoreClusterRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata:
        """Metadata associated with the new cluster."""
        ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec:
        """Specification for the new cluster."""
        ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    @property
    def backup_id(self) -> _builtins.str:
        """ID of the backup to restore from."""
        ...
    @backup_id.setter
    def backup_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``backup_id`` field."""
        ...
    @property
    def source_cluster_id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster to restore from."""
        ...
    @source_cluster_id.setter
    def source_cluster_id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``source_cluster_id`` field."""
        ...
    @property
    def recovery_time(self) -> _datetime | None:
        """Timestamp for point in time recovery."""
        ...
    @recovery_time.setter
    def recovery_time(self, value: _datetime | _SerializableMessage | None) -> None:
        """Set or clear the generated ``recovery_time`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
        backup_id: _builtins.str | None | _UnsetType = ...,
        source_cluster_id: _builtins.str | None | _UnsetType = ...,
        recovery_time: _datetime | _SerializableMessage | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class DeleteClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str:
        """ID of the PostgreSQL cluster to delete.\nTo get the PostgreSQL cluster ID, use a [ClusterService.List] request."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class UpdateClusterRequest(_Message):
    @property
    def metadata(self) -> _type_nebius_common_v1_ResourceMetadata:
        """Metadata associated with the cluster. Must include id of the cluster we are going to update."""
        ...
    @metadata.setter
    def metadata(self, value: _type_nebius_common_v1_ResourceMetadata | None) -> None:
        """Set or clear the generated ``metadata`` field."""
        ...
    @property
    def spec(self) -> ClusterSpec:
        """Updated specification for the cluster."""
        ...
    @spec.setter
    def spec(self, value: ClusterSpec | None) -> None:
        """Set or clear the generated ``spec`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        metadata: _type_nebius_common_v1_ResourceMetadata | None | _UnsetType = ...,
        spec: ClusterSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class StopClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str:
        """ID of the PostgreSQL Cluster resource to pause.\nTo get the cluster ID use a [ClusterService.List] request."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class StartClusterRequest(_Message):
    @property
    def id(self) -> _builtins.str:
        """ID of the PostgreSQL Cluster resource to resume.\nTo get the cluster ID use a [ClusterService.List] request."""
        ...
    @id.setter
    def id(self, value: _builtins.str | None) -> None:
        """Set or clear the generated ``id`` field."""
        ...
    def __init__(
        self, initial_message: _SerializableMessage | None = None, *, id: _builtins.str | None | _UnsetType = ...
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class TemplateSpec(_Message):
    @property
    def resources(self) -> _type_nebius_msp_v1alpha1_resource_ResourcesSpec:
        """reduced msp.v1alpha1.resource.TemplateSpec"""
        ...
    @resources.setter
    def resources(self, value: _type_nebius_msp_v1alpha1_resource_ResourcesSpec | None) -> None:
        """Set or clear the generated ``resources`` field."""
        ...
    @property
    def hosts(self) -> _type_nebius_msp_v1alpha1_resource_HostSpec: ...
    @hosts.setter
    def hosts(self, value: _type_nebius_msp_v1alpha1_resource_HostSpec | None) -> None:
        """Set or clear the generated ``hosts`` field."""
        ...
    @property
    def disk(self) -> _type_nebius_msp_v1alpha1_resource_DiskSpec: ...
    @disk.setter
    def disk(self, value: _type_nebius_msp_v1alpha1_resource_DiskSpec | None) -> None:
        """Set or clear the generated ``disk`` field."""
        ...
    def __init__(
        self,
        initial_message: _SerializableMessage | None = None,
        *,
        resources: _type_nebius_msp_v1alpha1_resource_ResourcesSpec | None | _UnsetType = ...,
        hosts: _type_nebius_msp_v1alpha1_resource_HostSpec | None | _UnsetType = ...,
        disk: _type_nebius_msp_v1alpha1_resource_DiskSpec | None | _UnsetType = ...,
    ) -> None:
        """Create a message from a source message and field values."""
        ...

class BackupServiceClient(_ClientWithOperations[_type_nebius_common_v1alpha1_Operation, _Any]):
    """A set of methods for managing PostgreSQL Cluster backups.\n\nThis class provides client methods for the ``nebius.msp.postgresql.v1alpha1.BackupService`` service."""
    def get(self, request: GetBackupRequest, **kwargs: _Unpack[_RequestKwargs]) -> _Request[GetBackupRequest, Backup]:
        """Returns the specified PostgreSQL Cluster backup.\nTo get the list of available PostgreSQL Cluster backups, make a [List] or [ListByCluster] request.\n\nThe request object is returned without starting the RPC."""
        ...
    def list(
        self, request: ListBackupsRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListBackupsRequest, ListBackupsResponse]:
        """Retrieves the list of PostgreSQL Cluster backups by project.\n\nThe request object is returned without starting the RPC."""
        ...
    def list_by_cluster(
        self, request: ListBackupsByClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListBackupsByClusterRequest, ListBackupsResponse]:
        """Retrieves the list of PostgreSQL Cluster backups by cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def create(
        self, request: CreateBackupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[CreateBackupRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Creates a new on-demand backup.\n\nThe request object is returned without starting the RPC."""
        ...
    def delete(
        self, request: DeleteBackupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[DeleteBackupRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Deletes an on-demand backup.\n\nThe request object is returned without starting the RPC."""
        ...

class ClusterServiceClient(_ClientWithOperations[_type_nebius_common_v1alpha1_Operation, _Any]):
    """A set of methods for managing PostgreSQL Cluster resources.\n\nThis class provides client methods for the ``nebius.msp.postgresql.v1alpha1.ClusterService`` service."""
    def get(
        self, request: GetClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetClusterRequest, Cluster]:
        """Returns the specified PostgreSQL Cluster resource.\nTo get the list of available PostgreSQL Cluster resources, make a [List] request.\n\nThe request object is returned without starting the RPC."""
        ...
    def get_by_name(
        self, request: _type_nebius_common_v1_GetByNameRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[_type_nebius_common_v1_GetByNameRequest, Cluster]:
        """Returns the specified PostgreSQL Cluster resource by name.\n\nThe request object is returned without starting the RPC."""
        ...
    def get_for_backup(
        self, request: GetClusterForBackupRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[GetClusterForBackupRequest, Cluster]:
        """Returns the specified PostgreSQL Cluster resource for backup.\nIt should be used as a hint of cluster configuration in case of backup restoration.\n\nThe request object is returned without starting the RPC."""
        ...
    def list(
        self, request: ListClustersRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[ListClustersRequest, ListClustersResponse]:
        """Retrieves the list of PostgreSQL Cluster resources that belong\nto the specified folder.\n\nThe request object is returned without starting the RPC."""
        ...
    def create(
        self, request: CreateClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[CreateClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Creates a PostgreSQL cluster in the specified folder.\n\nThe request object is returned without starting the RPC."""
        ...
    def delete(
        self, request: DeleteClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[DeleteClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Deletes the specified PostgreSQL cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def update(
        self, request: UpdateClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[UpdateClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Updates the PostgreSQL cluster.\n\nThe request object is returned without starting the RPC."""
        ...
    def restore(
        self, request: RestoreClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[RestoreClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Creates a new PostgreSQL cluster from a previously created backup.\n\nThe request object is returned without starting the RPC."""
        ...
    def stop(
        self, request: StopClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[StopClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Suspends the PostgreSQL cluster to save resources.\n\nThe request object is returned without starting the RPC."""
        ...
    def start(
        self, request: StartClusterRequest, **kwargs: _Unpack[_RequestKwargs]
    ) -> _Request[StartClusterRequest, _AsyncOperation[_type_nebius_common_v1alpha1_Operation]]:
        """Wakes up suspended PostgreSQL cluster.\n\nThe request object is returned without starting the RPC."""
        ...

__all__ = [
    "Backup",
    "BackupServiceClient",
    "BackupSpec",
    "BootstrapSpec",
    "Cluster",
    "ClusterServiceClient",
    "ClusterSpec",
    "ClusterStatus",
    "ConfigSpec",
    "ConnectionPoolerConfig",
    "CreateBackupRequest",
    "CreateClusterRequest",
    "DeleteBackupRequest",
    "DeleteClusterRequest",
    "Endpoints",
    "GetBackupRequest",
    "GetClusterForBackupRequest",
    "GetClusterRequest",
    "ListBackupsByClusterRequest",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListClustersRequest",
    "ListClustersResponse",
    "RestoreClusterRequest",
    "StartClusterRequest",
    "StopClusterRequest",
    "TemplateSpec",
    "UpdateClusterRequest",
]
