#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/audit/v2/audit_event.proto``."""

#@ local imports here @#

from . import AuditEvent as AuditEvent
DESCRIPTOR = AuditEvent.get_descriptor().file
