#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/audit/v2/service.proto``."""

#@ local imports here @#

from . import Service as Service
DESCRIPTOR = Service.get_descriptor().file
