#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""gRPC compatibility helpers for ``nebius/mysterybox/v1/secret_service.proto``."""

import grpc as grpc
import grpc.experimental as experimental
from ...common import v1 as v1
import typing as typing
#@ local imports here @#

from . import CreateSecretRequest as CreateSecretRequest
from . import DeleteSecretRequest as DeleteSecretRequest
from . import GetSecretByNameRequest as GetSecretByNameRequest
from . import GetSecretRequest as GetSecretRequest
from . import ListSecretsRequest as ListSecretsRequest
from . import ListSecretsResponse as ListSecretsResponse
from . import Secret as Secret
from . import UndeleteSecretRequest as UndeleteSecretRequest
from . import UpdateSecretRequest as UpdateSecretRequest
class SecretServiceStub:
    __service_name__ = "nebius.mysterybox.v1.SecretService"
    __service_name_override__ = "cpl.mysterybox"

    def __init__(self, channel: typing.Any) -> None:
        self.Create = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/Create",
            request_serializer=CreateSecretRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.Update = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/Update",
            request_serializer=UpdateSecretRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.Get = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/Get",
            request_serializer=GetSecretRequest.SerializeToString,
            response_deserializer=Secret.FromString,
        )
        self.GetByName = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/GetByName",
            request_serializer=GetSecretByNameRequest.SerializeToString,
            response_deserializer=Secret.FromString,
        )
        self.List = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/List",
            request_serializer=ListSecretsRequest.SerializeToString,
            response_deserializer=ListSecretsResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/Delete",
            request_serializer=DeleteSecretRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.Undelete = channel.unary_unary(
            "/nebius.mysterybox.v1.SecretService/Undelete",
            request_serializer=UndeleteSecretRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )

class SecretServiceServicer:
    def Create(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Update(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Get(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def GetByName(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def List(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Delete(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Undelete(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

class SecretService(SecretServiceServicer):
    """Backward-compatible experimental service API."""
    @staticmethod
    def Create(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/Create",
            CreateSecretRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/Update",
            UpdateSecretRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Get(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/Get",
            GetSecretRequest.SerializeToString,
            Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetByName(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/GetByName",
            GetSecretByNameRequest.SerializeToString,
            Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/List",
            ListSecretsRequest.SerializeToString,
            ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Delete(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/Delete",
            DeleteSecretRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Undelete(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.mysterybox.v1.SecretService/Undelete",
            UndeleteSecretRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


def add_SecretServiceServicer_to_server(servicer: typing.Any, server: typing.Any) -> None:
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=CreateSecretRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=UpdateSecretRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=GetSecretRequest.FromString,
            response_serializer=Secret.SerializeToString,
        ),
        "GetByName": grpc.unary_unary_rpc_method_handler(
            servicer.GetByName,
            request_deserializer=GetSecretByNameRequest.FromString,
            response_serializer=Secret.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=ListSecretsRequest.FromString,
            response_serializer=ListSecretsResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=DeleteSecretRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "Undelete": grpc.unary_unary_rpc_method_handler(
            servicer.Undelete,
            request_deserializer=UndeleteSecretRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nebius.mysterybox.v1.SecretService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, "add_registered_method_handlers"):
        server.add_registered_method_handlers(
            "nebius.mysterybox.v1.SecretService", rpc_method_handlers
        )
