#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/capacity/v1/resource_advice_service.proto``."""

#@ local imports here @#

from . import ListResourceAdviceRequest as ListResourceAdviceRequest
from . import ListResourceAdviceResponse as ListResourceAdviceResponse
DESCRIPTOR = ListResourceAdviceRequest.get_descriptor().file
