#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""gRPC compatibility helpers for ``nebius/iam/v1/federation_certificate_service.proto``."""

import grpc as grpc
import grpc.experimental as experimental
from ...common import v1 as v1
import typing as typing
#@ local imports here @#

from . import CreateFederationCertificateRequest as CreateFederationCertificateRequest
from . import DeleteFederationCertificateRequest as DeleteFederationCertificateRequest
from . import FederationCertificate as FederationCertificate
from . import GetFederationCertificateRequest as GetFederationCertificateRequest
from . import ListFederationCertificateByFederationRequest as ListFederationCertificateByFederationRequest
from . import ListFederationCertificateResponse as ListFederationCertificateResponse
from . import UpdateBulkFederationCertificateRequest as UpdateBulkFederationCertificateRequest
from . import UpdateFederationCertificateRequest as UpdateFederationCertificateRequest
class FederationCertificateServiceStub:
    __service_name__ = "nebius.iam.v1.FederationCertificateService"
    __service_name_override__ = "cpl.iam"

    def __init__(self, channel: typing.Any) -> None:
        self.Create = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/Create",
            request_serializer=CreateFederationCertificateRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.Get = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/Get",
            request_serializer=GetFederationCertificateRequest.SerializeToString,
            response_deserializer=FederationCertificate.FromString,
        )
        self.ListByFederation = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/ListByFederation",
            request_serializer=ListFederationCertificateByFederationRequest.SerializeToString,
            response_deserializer=ListFederationCertificateResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/Update",
            request_serializer=UpdateFederationCertificateRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.UpdateBulk = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/UpdateBulk",
            request_serializer=UpdateBulkFederationCertificateRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )
        self.Delete = channel.unary_unary(
            "/nebius.iam.v1.FederationCertificateService/Delete",
            request_serializer=DeleteFederationCertificateRequest.SerializeToString,
            response_deserializer=v1.Operation.FromString,
        )

class FederationCertificateServiceServicer:
    def Create(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Get(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def ListByFederation(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Update(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def UpdateBulk(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def Delete(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

class FederationCertificateService(FederationCertificateServiceServicer):
    """Backward-compatible experimental service API."""
    @staticmethod
    def Create(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/Create",
            CreateFederationCertificateRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Get(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/Get",
            GetFederationCertificateRequest.SerializeToString,
            FederationCertificate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListByFederation(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/ListByFederation",
            ListFederationCertificateByFederationRequest.SerializeToString,
            ListFederationCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/Update",
            UpdateFederationCertificateRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateBulk(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/UpdateBulk",
            UpdateBulkFederationCertificateRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Delete(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.FederationCertificateService/Delete",
            DeleteFederationCertificateRequest.SerializeToString,
            v1.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


def add_FederationCertificateServiceServicer_to_server(servicer: typing.Any, server: typing.Any) -> None:
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=CreateFederationCertificateRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=GetFederationCertificateRequest.FromString,
            response_serializer=FederationCertificate.SerializeToString,
        ),
        "ListByFederation": grpc.unary_unary_rpc_method_handler(
            servicer.ListByFederation,
            request_deserializer=ListFederationCertificateByFederationRequest.FromString,
            response_serializer=ListFederationCertificateResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=UpdateFederationCertificateRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "UpdateBulk": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateBulk,
            request_deserializer=UpdateBulkFederationCertificateRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=DeleteFederationCertificateRequest.FromString,
            response_serializer=v1.Operation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nebius.iam.v1.FederationCertificateService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, "add_registered_method_handlers"):
        server.add_registered_method_handlers(
            "nebius.iam.v1.FederationCertificateService", rpc_method_handlers
        )
