#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/iam/v1/federation.proto``."""

#@ local imports here @#

from . import Federation as Federation
from . import FederationSpec as FederationSpec
from . import SamlSettings as SamlSettings
from . import FederationStatus as FederationStatus
DESCRIPTOR = Federation.get_descriptor().file
