#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/iam/v1/federation_certificate_service.proto``."""

#@ local imports here @#

from . import CreateFederationCertificateRequest as CreateFederationCertificateRequest
from . import GetFederationCertificateRequest as GetFederationCertificateRequest
from . import ListFederationCertificateByFederationRequest as ListFederationCertificateByFederationRequest
from . import UpdateFederationCertificateRequest as UpdateFederationCertificateRequest
from . import UpdateBulkFederationCertificateRequest as UpdateBulkFederationCertificateRequest
from . import DeleteFederationCertificateRequest as DeleteFederationCertificateRequest
from . import ListFederationCertificateResponse as ListFederationCertificateResponse
DESCRIPTOR = CreateFederationCertificateRequest.get_descriptor().file
