#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""gRPC compatibility helpers for ``nebius/iam/v1/tenant_service.proto``."""

import grpc as grpc
import grpc.experimental as experimental
import typing as typing
#@ local imports here @#

from . import Container as Container
from . import GetTenantRequest as GetTenantRequest
from . import ListTenantsRequest as ListTenantsRequest
from . import ListTenantsResponse as ListTenantsResponse
class TenantServiceStub:
    __service_name__ = "nebius.iam.v1.TenantService"
    __service_name_override__ = "cpl.iam"

    def __init__(self, channel: typing.Any) -> None:
        self.Get = channel.unary_unary(
            "/nebius.iam.v1.TenantService/Get",
            request_serializer=GetTenantRequest.SerializeToString,
            response_deserializer=Container.FromString,
        )
        self.List = channel.unary_unary(
            "/nebius.iam.v1.TenantService/List",
            request_serializer=ListTenantsRequest.SerializeToString,
            response_deserializer=ListTenantsResponse.FromString,
        )

class TenantServiceServicer:
    def Get(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
    def List(self, request: typing.Any, context: typing.Any) -> typing.Any:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

class TenantService(TenantServiceServicer):
    """Backward-compatible experimental service API."""
    @staticmethod
    def Get(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.TenantService/Get",
            GetTenantRequest.SerializeToString,
            Container.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def List(
        request: typing.Any,
        target: str,
        options: typing.Any = (),
        channel_credentials: typing.Any = None,
        call_credentials: typing.Any = None,
        insecure: bool = False,
        compression: typing.Any = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: typing.Any = None,
    ) -> typing.Any:
        return experimental.unary_unary(
            request,
            target,
            "/nebius.iam.v1.TenantService/List",
            ListTenantsRequest.SerializeToString,
            ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


def add_TenantServiceServicer_to_server(servicer: typing.Any, server: typing.Any) -> None:
    rpc_method_handlers = {
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=GetTenantRequest.FromString,
            response_serializer=Container.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=ListTenantsRequest.FromString,
            response_serializer=ListTenantsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nebius.iam.v1.TenantService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, "add_registered_method_handlers"):
        server.add_registered_method_handlers(
            "nebius.iam.v1.TenantService", rpc_method_handlers
        )
