#
# Generated by nebius_generator.  DO NOT EDIT!
#

"""Compatibility facade for ``nebius/iam/v1/token_exchange_service.proto``."""

from ... import _registry as _registry
#@ local imports here @#

DESCRIPTOR = _registry.service_descriptor(".nebius.iam.v1.TokenExchangeService").file
