name: Update API and regenerate project

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # when triggered remotely
    types:
    - updated-api
  # push:
  #   paths:
  #   - 'nebius-api'
  #   - 'nebius-api/**'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v5
      with:
        ssh-key: ${{ secrets.AUTOCOMMITTER_PRIVATE_KEY }}
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[generators,dev]
        pip install tox

    - uses: bufbuild/buf-action@v1
      with:
        token: ${{ secrets.BUF_TOKEN }}
        setup_only: true

    - name: Run generation script
      run: |
        make

    - name: Check for Changes
      id: check_changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        fi

    - name: Bump version
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        python src/scripts/version_updater.py ./pyproject.toml ./src/nebius/base/version.py patch
        git add pyproject.toml
        git add ./src/nebius/base/version.py

    - name: Test
      if: steps.check_changes.outputs.changes_detected == 'true'
      env:
        NEBIUS_E2E_CONFIG_B64: ${{ secrets.NEBIUS_E2E_CONFIG_B64 }}
      run: |
        tox
        tox -e test_earliest

    - name: Commit changes
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Auto-update API to: $(git -C nebius-api log -1 --format='%h, %ci')"

    - name: Push and pull changes
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git push origin main
        git pull
        git status
        git branch -r --contains HEAD

    - name: Tag commit
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        make tag-ver

    - name: Push changes
      if: steps.check_changes.outputs.changes_detected == 'true'
      uses: ad-m/github-push-action@master
      with:
        tags: true
        ssh: true
        force_with_lease: true

  # Probably no need, as the release will be triggered by the tag
  # release:
  #   if: ${{ needs.update.outputs.changes_detected == 'true' }}
  #   needs: update
  #   uses: ./.github/workflows/release.yml

  notify-slack-on-failure:
    name: Notify Slack on failure
    if: failure()
    needs: [update]
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: |
              🚨 Workflow *${{ github.workflow }}* failed on <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
              <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
